'use strict';
(() => {
const $=s=>document.querySelector(s), catalog=window.AGENT_TOOL_CATALOG||[];
let mode='none',rootHandle=null,memFiles=new Map(),changes=new Map(),customTools=new Map(),workspaceName='';
const handlers=new Map(),enc=new TextEncoder();
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function norm(p='.') {p=String(p||'.').replace(/\\/g,'/').replace(/^\.\//,'');if(p==='.'||p==='')return'';const out=[];for(const part of p.split('/')){if(!part||part==='.')continue;if(part==='..'){if(!out.length)throw Error('Path escapes workspace');out.pop()}else out.push(part)}return out.join('/')}
function parentPath(p){p=norm(p);let a=p.split('/');a.pop();return a.join('/')}
function baseName(p){p=norm(p);return p.split('/').pop()||''}
async function getDir(path='',create=false){if(mode!=='direct')throw Error('Direct workspace unavailable');let d=rootHandle;for(const part of norm(path).split('/').filter(Boolean))d=await d.getDirectoryHandle(part,{create});return d}
async function getFileHandle(path,create=false){path=norm(path);return(await getDir(parentPath(path),create)).getFileHandle(baseName(path),{create})}
async function directExists(path){try{path=norm(path);if(!path)return true;const d=await getDir(parentPath(path)),n=baseName(path);try{await d.getFileHandle(n);return true}catch{}try{await d.getDirectoryHandle(n);return true}catch{}return false}catch{return false}}
async function readText(path){path=norm(path);if(mode==='direct')return(await(await getFileHandle(path)).getFile()).text();if(memFiles.has(path))return memFiles.get(path).text;throw Error('File not found: '+path)}
async function safeRead(path){try{return await readText(path)}catch{return''}}
async function writeText(path,text){path=norm(path);if(!path)throw Error('Invalid file path');text=String(text??'');if(mode==='direct'){const h=await getFileHandle(path,true),w=await h.createWritable();await w.write(text);await w.close()}else memFiles.set(path,{text,size:enc.encode(text).length,type:'text/plain'});changes.set(path,{type:'write',size:enc.encode(text).length});renderChanges();return{path,bytes:enc.encode(text).length}}
async function deletePath(path){path=norm(path);if(!path)throw Error('Cannot delete workspace root');if(mode==='direct'){await(await getDir(parentPath(path))).removeEntry(baseName(path),{recursive:true})}else for(const k of [...memFiles.keys()])if(k===path||k.startsWith(path+'/'))memFiles.delete(k);changes.set(path,{type:'delete'});renderChanges();return{path,deleted:true}}
async function makeDir(path){path=norm(path);if(mode==='direct')await getDir(path,true);else memFiles.set(path+'/.agentbridge-dir',{text:'',dir:true,size:0});changes.set(path,{type:'mkdir'});renderChanges();return{path,created:true}}
async function walk(path='',maxDepth=20){path=norm(path);const out=[];if(mode==='direct'){const start=await getDir(path);async function rec(dir,p,d){if(d>maxDepth)return;for await(const[name,h]of dir.entries()){const rel=[p,name].filter(Boolean).join('/');if(h.kind==='file'){const f=await h.getFile();out.push({path:rel,type:'file',size:f.size,lastModified:f.lastModified})}else{out.push({path:rel,type:'dir'});await rec(h,rel,d+1)}}}await rec(start,path,0)}else for(const[k,v]of memFiles){if(path&&(k!==path&&!k.startsWith(path+'/')))continue;if(v.dir||k.endsWith('/.agentbridge-dir'))continue;out.push({path:k,type:'file',size:v.size??enc.encode(v.text||'').length,lastModified:v.lastModified})}return out}
async function list(path=''){path=norm(path);const all=await walk(path,1),prefix=path?path+'/':'';return all.filter(x=>{const r=x.path.slice(prefix.length);return r&&!r.includes('/')})}
function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<=text.length;i++){const c=text[i]??'\n';if(q){if(c==='"'&&text[i+1]==='"'){cell+='"';i++}else if(c==='"')q=false;else cell+=c}else if(c==='"')q=true;else if(c===','){row.push(cell);cell=''}else if(c==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell=''}else cell+=c}if(rows.length&&rows.at(-1).length===1&&rows.at(-1)[0]==='')rows.pop();return rows}
function toCSV(rows){return rows.map(r=>r.map(v=>{v=String(v??'');return /[",\n\r]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v}).join(',')).join('\n')}
function deepGet(obj,path){for(const k of String(path||'').split('.').filter(Boolean)){if(obj==null)return undefined;obj=obj[k]}return obj}
function deepSet(obj,path,val){const parts=String(path).split('.').filter(Boolean);if(!parts.length)return val;const root=structuredClone(obj??{});let o=root;for(let i=0;i<parts.length-1;i++){const k=parts[i],next=parts[i+1];if(!o[k]||typeof o[k]!=='object')o[k]=/^\d+$/.test(next)?[]:{};o=o[k]}o[parts.at(-1)]=val;return root}
function sortKeys(x){if(Array.isArray(x))return x.map(sortKeys);if(x&&typeof x==='object')return Object.fromEntries(Object.keys(x).sort().map(k=>[k,sortKeys(x[k])])) ;return x}
function copyFallback(text){const ta=document.createElement('textarea');ta.value=text;ta.style.cssText='position:fixed;opacity:0';document.body.append(ta);ta.select();let ok=false;try{ok=document.execCommand('copy')}catch{}ta.remove();return ok}
async function copyText(text){try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);return true}}catch{}return copyFallback(text)}
function register(id,fn){handlers.set(id,fn)}
window.AgentBridge={register,api:{norm,parentPath,baseName,getDir,getFileHandle,directExists,readText,safeRead,writeText,deletePath,makeDir,walk,list,parseCSV,toCSV,deepGet,deepSet,sortKeys,esc},state:()=>({mode,workspaceName,changes})};
function setInfo(){const direct=mode==='direct';$('#mode-badge').textContent=mode==='none'?'未接続':direct?'直接編集':'読み込み専用';$('#workspace-info').innerHTML=mode==='none'?'まだフォルダが選択されていません。':`<strong>${esc(workspaceName||'workspace')}</strong><br>${direct?'選択フォルダへ直接保存できます。':'変更はメモリ上に保持し、ファイルとして書き出します。'}`;refreshHandshake()}
async function chooseDirect(){if(!window.showDirectoryPicker){alert('このブラウザでは直接フォルダ編集が利用できません。「読み込み専用で選ぶ」を使ってください。');return}try{rootHandle=await showDirectoryPicker({mode:'readwrite'});mode='direct';workspaceName=rootHandle.name;memFiles.clear();changes.clear();await loadCustomTools();setInfo();renderChanges()}catch(e){if(e.name!=='AbortError')alert('フォルダを開けませんでした: '+e.message)}}
async function loadMemoryFiles(fileList){memFiles.clear();workspaceName=fileList[0]?.webkitRelativePath?.split('/')[0]||'workspace';for(const f of fileList){let raw=f.webkitRelativePath||f.name;if(workspaceName&&raw.startsWith(workspaceName+'/'))raw=raw.slice(workspaceName.length+1);const p=norm(raw);let text='';try{text=await f.text()}catch{}memFiles.set(p,{text,size:f.size,type:f.type,lastModified:f.lastModified})}mode='memory';changes.clear();await loadCustomTools();setInfo();renderChanges()}
function toolPrompt(){const all=[...catalog,...[...customTools.values()].map(x=>({id:x.id,description:x.description||'Custom macro',args:x.args||{}}))];return `You are controlling Agent Bridge, a local browser tool runner. You know nothing about the workspace until you inspect it with tools.\n\nRULES:\n1. Reply with JSON only. No markdown fences.\n2. Use only tool IDs listed below.\n3. All paths are relative to the selected workspace. Never use absolute paths or .. to escape it.\n4. Prefer reading/listing before editing.\n5. Keep each batch reasonably small. After execution, I will send you the result JSON; continue from that result.\n6. Do not assume Python, shell, network, admin rights, or installed software. This school-PC build intentionally does not expose them.\n7. For destructive edits, first inspect the target.\n\nREQUEST FORMAT:\n{"version":1,"actions":[{"id":"a1","tool":"file.list","args":{"path":"."}},{"id":"a2","tool":"file.read_text","args":{"path":"README.md"}}]}\n\nRESULT FORMAT YOU WILL RECEIVE:\n{"version":1,"ok":true,"results":[{"id":"a1","tool":"file.list","ok":true,"result":...}]}\n\nAVAILABLE TOOLS (${all.length}):\n`+all.map(t=>`- ${t.id}${t.args?`(${typeof t.args==='string'?t.args:Object.keys(t.args).join(',')})`:''}: ${t.description}`).join('\n')}
function refreshHandshake(){$('#tool-count').textContent=(catalog.length+customTools.size)+' tools';$('#custom-count').textContent='Custom '+customTools.size;$('#handshake').value=toolPrompt()}
function template(v,ctx){if(Array.isArray(v))return v.map(x=>template(x,ctx));if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,template(x,ctx)]));if(typeof v!=='string')return v;let m=v.match(/^\{\{([^}]+)}}$/);if(m){let x=deepGet(ctx,m[1]);return x===undefined?v:x}return v.replace(/\{\{([^}]+)}}/g,(_,p)=>{let x=deepGet(ctx,p);return x==null?'':typeof x==='string'?x:JSON.stringify(x)})}
async function execBuiltin(id,args){const fn=handlers.get(id);if(!fn)throw Error('Tool implementation unavailable: '+id);return fn(args||{})}
async function execCustom(def,args){if(!Array.isArray(def.steps)||def.steps.length>25)throw Error('Invalid custom macro steps');const ctx={args,steps:[]},out=[];for(const s of def.steps){if(customTools.has(s.tool))throw Error('Custom macro cannot call another custom macro');const r=await execBuiltin(s.tool,template(s.args||{},ctx));ctx.steps.push({result:r});out.push({tool:s.tool,result:r})}return{macro:def.id,steps:out,result:out.at(-1)?.result}}
async function executeAction(a){return customTools.has(a.tool)?execCustom(customTools.get(a.tool),a.args||{}):execBuiltin(a.tool,a.args||{})}
async function runCommand(){if(mode==='none'){alert('先に作業フォルダを選んでください。');return}let req;try{req=JSON.parse($('#command').value)}catch(e){$('#run-status').textContent='JSONエラー: '+e.message;return}if(req.version!==1||!Array.isArray(req.actions)){$('#run-status').textContent='version:1 と actions配列が必要です。';return}if(req.actions.length>50){$('#run-status').textContent='1回50アクションまでです。';return}$('#run').disabled=true;let results=[],ok=true;for(let i=0;i<req.actions.length;i++){const a=req.actions[i],item={id:a.id||`a${i+1}`,tool:a.tool};$('#run-status').textContent=`${i+1}/${req.actions.length} 実行中`;try{item.result=await executeAction(a);item.ok=true}catch(e){item.ok=false;item.error=String(e.message||e);ok=false}results.push(item);if(!item.ok&&$('#stop-on-error').checked)break}const payload={version:1,ok,workspace:workspaceName,mode,results,changes:[...changes].map(([path,v])=>({path,...v}))},text=JSON.stringify(payload,null,2);$('#result').value=text;$('#run-status').textContent=ok?'完了。結果をAIへ送ってください。':'エラーあり。結果をAIへ送って続行できます。';if($('#auto-copy').checked){const c=await copyText(text);$('#run-status').textContent+=c?' 自動コピー済み。':' 「コピー」を押してください。'}$('#run').disabled=false}
async function loadCustomTools(){customTools.clear();try{let files=[];if(mode==='direct'){let d;try{d=await getDir('tool')}catch{return}for await(const[name,h]of d.entries())if(h.kind==='file'&&name.endsWith('.agenttool.json'))files.push([name,await(await h.getFile()).text()])}else for(const[p,v]of memFiles)if(/^tool\/[^/]+\.agenttool\.json$/i.test(p))files.push([p,v.text]);for(const[,text]of files)try{const d=JSON.parse(text);if(/^[a-z0-9_.-]{3,80}$/i.test(d.id)&&Array.isArray(d.steps)&&!catalog.some(x=>x.id===d.id))customTools.set(d.id,d)}catch{}}finally{refreshHandshake()}}
function renderChanges(){const h=$('#changes');h.innerHTML=changes.size?[...changes].map(([p,v])=>`<div class="change"><code>${esc(p)}</code><span class="tag">${esc(v.type)}</span></div>`).join(''):'<p class="muted">変更はまだありません。</p>'}
async function downloadChanged(){if(!changes.size){alert('変更はありません。');return}for(const[p,v]of changes){if(v.type==='delete'||v.type==='mkdir')continue;const blob=new Blob([await readText(p)],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=baseName(p)||'file.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);await new Promise(r=>setTimeout(r,100))}}
$('#pick-folder').onclick=chooseDirect;$('#folder-input').onchange=e=>loadMemoryFiles([...e.target.files]);$('#copy-handshake').onclick=async()=>{refreshHandshake();const ok=await copyText($('#handshake').value);$('#copy-handshake').textContent=ok?'✓ コピーしました':'コピー失敗';setTimeout(()=>$('#copy-handshake').textContent='📋 AI用説明をコピー',1200)};$('#preview-handshake').onclick=()=>$('#handshake').classList.toggle('compact');$('#run').onclick=runCommand;$('#copy-result').onclick=()=>copyText($('#result').value);$('#clear-json').onclick=()=>$('#command').value='';$('#sample-json').onclick=()=>$('#command').value=JSON.stringify({version:1,actions:[{id:'a1',tool:'file.list',args:{path:'.'}},{id:'a2',tool:'project.summary',args:{path:'.'}}]},null,2);$('#download-all').onclick=downloadChanged;$('#reload-custom-tools').onclick=loadCustomTools;
setInfo();refreshHandshake();
})();
