'use strict';
(() => {
const $=s=>document.querySelector(s), catalog=window.AGENT_TOOL_CATALOG||[];
let mode='none',rootHandle=null,memFiles=new Map(),changes=new Map(),customTools=new Map(),workspaceName='';
const handlers=new Map(),enc=new TextEncoder();
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function norm(p='.') {p=String(p||'.').replace(/\\/g,'/').replace(/^\.\//,'');if(p==='.'||p==='')return'';const out=[];for(const part of p.split('/')){if(!part||part==='.')continue;if(part==='..'){if(!out.length)throw Error('Path escapes workspace');out.pop()}else out.push(part)}return out.join('/')}
function parentPath(p){p=norm(p);let a=p.split('/');a.pop();return a.join('/')}
function baseName(p){p=norm(p);return p.split('/').pop()||''}
async function getDir(path='',create=false){if(mode!=='direct')throw Error('Direct workspace unavailable');let d=rootHandle;for(const part of norm(path).split('/').filter(Boolean))d=await d.getDirectoryHandle(part,{create});return d}
async function getFileHandle(path,create=false){path=norm(path);return(await getDir(parentPath(path),create)).getFileHandle(baseName(path),{create})}
async function directExists(path){try{path=norm(path);if(!path)return true;const d=await getDir(parentPath(path)),n=baseName(path);try{await d.getFileHandle(n);return true}catch{}try{await d.getDirectoryHandle(n);return true}catch{}return false}catch{return false}}
async function readText(path){path=norm(path);if(mode==='direct')return(await(await getFileHandle(path)).getFile()).text();if(memFiles.has(path))return memFiles.get(path).text;throw Error('File not found: '+path)}
async function safeRead(path){try{return await readText(path)}catch{return''}}
async function writeText(path,text){path=norm(path);if(!path)throw Error('Invalid file path');text=String(text??'');if(mode==='direct'){const h=await getFileHandle(path,true),w=await h.createWritable();await w.write(text);await w.close()}else memFiles.set(path,{text,size:enc.encode(text).length,type:'text/plain'});changes.set(path,{type:'write',size:enc.encode(text).length});renderChanges();return{path,bytes:enc.encode(text).length}}
async function deletePath(path){path=norm(path);if(!path)throw Error('Cannot delete workspace root');if(mode==='direct'){await(await getDir(parentPath(path))).removeEntry(baseName(path),{recursive:true})}else for(const k of [...memFiles.keys()])if(k===path||k.startsWith(path+'/'))memFiles.delete(k);changes.set(path,{type:'delete'});renderChanges();return{path,deleted:true}}
async function makeDir(path){path=norm(path);if(mode==='direct')await getDir(path,true);else memFiles.set(path+'/.agentbridge-dir',{text:'',dir:true,size:0});changes.set(path,{type:'mkdir'});renderChanges();return{path,created:true}}
async function walk(path='',maxDepth=20){path=norm(path);const out=[];if(mode==='direct'){const start=await getDir(path);async function rec(dir,p,d){if(d>maxDepth)return;for await(const[name,h]of dir.entries()){const rel=[p,name].filter(Boolean).join('/');if(h.kind==='file'){const f=await h.getFile();out.push({path:rel,type:'file',size:f.size,lastModified:f.lastModified})}else{out.push({path:rel,type:'dir'});await rec(h,rel,d+1)}}}await rec(start,path,0)}else for(const[k,v]of memFiles){if(path&&(k!==path&&!k.startsWith(path+'/')))continue;if(v.dir||k.endsWith('/.agentbridge-dir'))continue;out.push({path:k,type:'file',size:v.size??enc.encode(v.text||'').length,lastModified:v.lastModified})}return out}
async function list(path=''){path=norm(path);const all=await walk(path,1),prefix=path?path+'/':'';return all.filter(x=>{const r=x.path.slice(prefix.length);return r&&!r.includes('/')})}
function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<=text.length;i++){const c=text[i]??'\n';if(q){if(c==='"'&&text[i+1]==='"'){cell+='"';i++}else if(c==='"')q=false;else cell+=c}else if(c==='"')q=true;else if(c===','){row.push(cell);cell=''}else if(c==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell=''}else cell+=c}if(rows.length&&rows.at(-1).length===1&&rows.at(-1)[0]==='')rows.pop();return rows}
function toCSV(rows){return rows.map(r=>r.map(v=>{v=String(v??'');return /[",\n\r]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v}).join(',')).join('\n')}
function deepGet(obj,path){for(const k of String(path||'').split('.').filter(Boolean)){if(obj==null)return undefined;obj=obj[k]}return obj}
function deepSet(obj,path,val){const parts=String(path).split('.').filter(Boolean);if(!parts.length)return val;const root=structuredClone(obj??{});let o=root;for(let i=0;i<parts.length-1;i++){const k=parts[i],next=parts[i+1];if(!o[k]||typeof o[k]!=='object')o[k]=/^\d+$/.test(next)?[]:{};o=o[k]}o[parts.at(-1)]=val;return root}
function sortKeys(x){if(Array.isArray(x))return x.map(sortKeys);if(x&&typeof x==='object')return Object.fromEntries(Object.keys(x).sort().map(k=>[k,sortKeys(x[k])])) ;return x}
function copyFallback(text){const ta=document.createElement('textarea');ta.value=text;ta.style.cssText='position:fixed;opacity:0';document.body.append(ta);ta.select();let ok=false;try{ok=document.execCommand('copy')}catch{}ta.remove();return ok}
async function copyText(text){try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);return true}}catch{}return copyFallback(text)}
function register(id,fn){handlers.set(id,fn)}
function extractBalanced(text){text=String(text);let start=-1;for(let i=0;i<text.length;i++){if(text[i]==='{'||text[i]==='['){start=i;break}}if(start<0)return null;const stack=[],pairs={'}':'{',']':'['};let str=false,escp=false;for(let i=start;i<text.length;i++){const c=text[i];if(str){if(escp){escp=false;continue}if(c==='\\'){escp=true;continue}if(c==='"')str=false;continue}if(c==='"'){str=true;continue}if(c==='{'||c==='[')stack.push(c);else if(c==='}'||c===']'){if(stack.pop()!==pairs[c])return null;if(!stack.length)return text.slice(start,i+1)}}return null}
function stripJsonComments(text){let out='',str=false,escp=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(str){if(c==='\n'){out+='\\n';continue}if(c==='\r'){out+='\\r';continue}if(c==='\t'){out+='\\t';continue}out+=c;if(escp){escp=false;continue}if(c==='\\'){escp=true;continue}if(c==='"')str=false;continue}if(c==='"'){str=true;out+=c;continue}if(c==='/'&&n==='/'){while(i<text.length&&text[i]!=='\n')i++;out+='\n';continue}if(c==='/'&&n==='*'){i+=2;while(i<text.length-1&&!(text[i]==='*'&&text[i+1]==='/'))i++;i++;continue}out+=c}return out}
function removeTrailingCommas(text){let out='',str=false,escp=false;for(let i=0;i<text.length;i++){const c=text[i];if(str){out+=c;if(escp){escp=false;continue}if(c==='\\'){escp=true;continue}if(c==='"')str=false;continue}if(c==='"'){str=true;out+=c;continue}if(c===','){let j=i+1;while(j<text.length&&/\s/.test(text[j]))j++;if(text[j]==='}'||text[j]===']')continue}out+=c}return out}
function sanitizeJsonish(text){return removeTrailingCommas(stripJsonComments(String(text).replace(/^\uFEFF/,''))).trim()}
function normalizeAction(a,i){if(!a||typeof a!=='object'||Array.isArray(a))throw Error(`Action ${i+1} must be an object`);const tool=a.tool||a.name||a.toolId;const args=a.args??a.arguments??a.parameters??{};if(typeof tool!=='string'||!tool.trim())throw Error(`Action ${i+1} has no tool`);return{id:a.id||`a${i+1}`,tool:tool.trim(),args:args&&typeof args==='object'?args:{value:args}}}
function normalizeRequestValue(v){let actions;if(Array.isArray(v))actions=v;else if(v&&typeof v==='object'&&Array.isArray(v.actions))actions=v.actions;else if(v&&typeof v==='object'&&Array.isArray(v.commands))actions=v.commands;else if(v&&typeof v==='object'&&v.action)actions=[v.action];else if(v&&typeof v==='object'&&(v.tool||v.name||v.toolId))actions=[v];else throw Error('actions配列、action、または単一toolオブジェクトが必要です。');return{version:1,actions:actions.map(normalizeAction)}}
function parseOneCandidate(text){let last;for(const candidate of [String(text).trim(),sanitizeJsonish(text)]){if(!candidate)continue;try{return normalizeRequestValue(JSON.parse(candidate))}catch(e){last=e}}throw last||Error('JSONを解析できません')}
function parseAgentRequest(raw){raw=String(raw??'').trim();if(!raw)throw Error('JSON入力が空です。');const warnings=[],candidates=[{text:raw,source:'raw'}];for(const m of raw.matchAll(/```(?:json|javascript|js)?\s*([\s\S]*?)```/gi))candidates.unshift({text:m[1],source:'code-fence'});const balanced=extractBalanced(raw);if(balanced&&balanced!==raw)candidates.push({text:balanced,source:'extracted'});let lastErr=null;for(const c of candidates){try{const request=parseOneCandidate(c.text);if(c.source!=='raw')warnings.push(`${c.source}からJSON部分を抽出しました。`);return{request,warnings,source:c.source}}catch(e){lastErr=e}}const nd=raw.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(nd.length>1){try{const vals=nd.map(x=>JSON.parse(sanitizeJsonish(x)));if(vals.every(x=>x&&typeof x==='object'&&(x.tool||x.name||x.toolId))){warnings.push('JSON Linesとして読み込みました。');return{request:normalizeRequestValue(vals),warnings,source:'json-lines'}}}catch{}}throw Error(`JSONを解析できません: ${lastErr?.message||'形式を確認してください'}。コードブロック付きでも構いません。単一action、action配列、{actions:[...]} に対応しています。`)}
async function execBuiltin(id,args){const fn=handlers.get(id);if(!fn)throw Error('Tool implementation unavailable: '+id);return fn(args||{})}
window.AgentBridge={register,api:{norm,parentPath,baseName,getDir,getFileHandle,directExists,readText,safeRead,writeText,deletePath,makeDir,walk,list,parseCSV,toCSV,deepGet,deepSet,sortKeys,esc,parseAgentRequest,runTool:execBuiltin},state:()=>({mode,workspaceName,changes})};
function setInfo(){const direct=mode==='direct';$('#mode-badge').textContent=mode==='none'?'未接続':direct?'直接編集':'読み込み専用';$('#workspace-info').innerHTML=mode==='none'?'まだフォルダが選択されていません。':`<strong>${esc(workspaceName||'workspace')}</strong><br>${direct?'選択フォルダへ直接保存できます。':'変更はメモリ上に保持し、ファイルとして書き出します。'}`;refreshHandshake()}
async function chooseDirect(){if(!window.showDirectoryPicker){alert('このブラウザでは直接フォルダ編集が利用できません。「読み込み専用で選ぶ」を使ってください。');return}try{rootHandle=await showDirectoryPicker({mode:'readwrite'});mode='direct';workspaceName=rootHandle.name;memFiles.clear();changes.clear();await loadCustomTools();setInfo();renderChanges()}catch(e){if(e.name!=='AbortError')alert('フォルダを開けませんでした: '+e.message)}}
async function loadMemoryFiles(fileList){memFiles.clear();workspaceName=fileList[0]?.webkitRelativePath?.split('/')[0]||'workspace';for(const f of fileList){let raw=f.webkitRelativePath||f.name;if(workspaceName&&raw.startsWith(workspaceName+'/'))raw=raw.slice(workspaceName.length+1);const p=norm(raw);let text='';try{text=await f.text()}catch{}memFiles.set(p,{text,size:f.size,type:f.type,lastModified:f.lastModified})}mode='memory';changes.clear();await loadCustomTools();setInfo();renderChanges()}
function allTools(){return[...catalog,...[...customTools.values()].map(x=>({id:x.id,description:x.description||'Custom macro',args:x.args||{},usage:x.usage,example:x.example,notes:x.notes}))]}
function toolPrompt(detailed=false){const all=allTools();const header=`あなたは Agent Bridge と組み合わせて作業するAIです。Agent Bridgeは、ユーザーが選択した作業フォルダ内だけを操作するローカルブラウザツールです。\n\n【最重要：最初の返答】\nこの説明を受け取った直後はJSONを出してはいけません。まず日本語で「何を作成・修正・調査したいですか？目的や対象を教えてください。」とユーザーに質問し、依頼を待ってください。\nユーザーから具体的な作業依頼を受けた後にだけ、必要なtool actionをJSONで返してください。\n\n【JSONを出す期間】\n- ツール実行が必要な間だけJSONを返す。\n- 実行結果JSONを受け取って追加調査や修正が必要なら、次のJSONを返す。\n- 作業が完了したらJSON出力をやめ、通常の日本語で何をしたか説明する。JSONしか返し続けてはいけない。\n\n【重要ルール】\n1. 作業開始時は project.quick_context / file.list / file.read_* などで確認し、知らない内容を推測しない。\n2. パスは作業フォルダからの相対パスだけ。絶対パスや .. で外へ出ない。\n3. 巨大ファイルは file.read_chunk / file.read_around を使い、全文を何度もJSONへ埋め込まない。\n4. JSONファイルの編集は file.write_text より json.file_get / json.file_set / json.file_merge / json.file_write を優先する。これで引用符・改行のエスケープ事故を避ける。\n5. 部分編集は file.apply_patch_exact / file.apply_edits / file.patch_by_context を優先し、可能なら最初に dryRun:true で確認する。\n6. 1回のJSONは原則3〜10 actions程度。巨大なJSONを1回で返さず、結果を見ながら分割する。\n7. 後続actionは {{results.a1.result.text}} のように前action結果を参照できる。長い内容を再掲しない。\n8. 引数が不明なら推測せず agent.tool_help / agent.search_tools を使う。\n9. 編集後は project.verify_after_edit、必要なら project.diagnostics を実行する。\n10. Python、shell、PowerShell、cmd、ネットワーク、管理者権限はこの学校PC版では使えない。制限回避を試みない。\n\n【受け付けるJSON】\n標準: {"version":1,"actions":[{"id":"a1","tool":"file.list","args":{"path":"."}}]}\n単一action: {"tool":"file.list","args":{"path":"."}}\naction配列: [{"tool":"file.list","args":{"path":"."}}]\nコードブロック付きJSONや前後に短い説明が混ざったJSONもAgent Bridge側で抽出を試みる。\n\n【action間参照例】\n{"version":1,"actions":[{"id":"a1","tool":"file.read_text","args":{"path":"README.md"}},{"id":"a2","tool":"text.char_count","args":{"text":"{{results.a1.result.text}}"}}]}\n\n【長いJSONファイルの安全な変更例】\n{"version":1,"actions":[{"id":"a1","tool":"json.file_get","args":{"path":"config.json","jsonPath":"ui"}},{"id":"a2","tool":"json.file_set","args":{"path":"config.json","jsonPath":"ui.theme","value":"dark"}},{"id":"a3","tool":"json.file_validate","args":{"path":"config.json"}}]}\n\n【利用可能ツール: ${all.length}】\n`;const rows=all.map(t=>{let s=`- ${t.id}${t.args?`(${typeof t.args==='string'?t.args:Object.keys(t.args).join(',')})`:''}: ${t.description}`;if(detailed){if(t.usage)s+=`\n  使い方: ${t.usage}`;if(t.example)s+=`\n  例: ${t.example}`;if(t.notes)s+=`\n  注意: ${t.notes}`}return s}).join('\n');return header+rows+`\n\nツールが多いため、迷った場合は agent.search_tools → agent.tool_help の順で確認してください。`}
function refreshHandshake(){$('#tool-count').textContent=(catalog.length+customTools.size)+' tools';$('#custom-count').textContent='Custom '+customTools.size;$('#handshake').value=toolPrompt(false)}
function template(v,ctx){if(Array.isArray(v))return v.map(x=>template(x,ctx));if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,template(x,ctx)]));if(typeof v!=='string')return v;let m=v.match(/^\{\{([^}]+)}}$/);if(m){let x=deepGet(ctx,m[1]);return x===undefined?v:x}return v.replace(/\{\{([^}]+)}}/g,(_,p)=>{let x=deepGet(ctx,p);return x==null?'':typeof x==='string'?x:JSON.stringify(x)})}
async function execCustom(def,args){if(!Array.isArray(def.steps)||def.steps.length>25)throw Error('Invalid custom macro steps');const ctx={args,steps:[]},out=[];for(const s of def.steps){if(customTools.has(s.tool))throw Error('Custom macro cannot call another custom macro');const r=await execBuiltin(s.tool,template(s.args||{},ctx));ctx.steps.push({result:r});out.push({tool:s.tool,result:r})}return{macro:def.id,steps:out,result:out.at(-1)?.result}}
async function executeAction(a){return customTools.has(a.tool)?execCustom(customTools.get(a.tool),a.args||{}):execBuiltin(a.tool,a.args||{})}
async function runCommand(){if(mode==='none'){alert('先に作業フォルダを選んでください。');return}let parsed;try{parsed=parseAgentRequest($('#command').value)}catch(e){$('#run-status').textContent='JSON入力エラー: '+e.message;return}const req=parsed.request;if(req.actions.length>50){$('#run-status').textContent='1回50アクションまでです。3〜10個程度に分割するのがおすすめです。';return}$('#run').disabled=true;let results=[],ok=true;const ctx={results:{},steps:[]};try{for(let i=0;i<req.actions.length;i++){const source=req.actions[i],id=source.id||`a${i+1}`,resolved=template(source.args||{},ctx),a={...source,id,args:resolved},item={id,tool:a.tool};$('#run-status').textContent=`${i+1}/${req.actions.length} 実行中${parsed.warnings.length?' · JSON自動補正あり':''}`;try{item.result=await executeAction(a);item.ok=true}catch(e){item.ok=false;item.error=String(e.message||e);ok=false}results.push(item);ctx.results[id]=item;ctx.steps.push(item);if(!item.ok&&$('#stop-on-error').checked)break}const payload={version:1,ok,workspace:workspaceName,mode,input:{source:parsed.source,warnings:parsed.warnings},results,changes:[...changes].map(([path,v])=>({path,...v}))},text=JSON.stringify(payload,null,2);$('#result').value=text;$('#run-status').textContent=ok?'完了。結果をAIへ送ってください。':'エラーあり。結果JSONをAIへ送り、内容を見て修正させてください。';if(parsed.warnings.length)$('#run-status').textContent+=` 入力補正: ${parsed.warnings.join(' ')}`;if($('#auto-copy').checked){const c=await copyText(text);$('#run-status').textContent+=c?' 自動コピー済み。':' 「コピー」を押してください。'}}finally{$('#run').disabled=false}}
async function loadCustomTools(){customTools.clear();try{let files=[];if(mode==='direct'){let d;try{d=await getDir('tool')}catch{return}for await(const[name,h]of d.entries())if(h.kind==='file'&&name.endsWith('.agenttool.json'))files.push([name,await(await h.getFile()).text()])}else for(const[p,v]of memFiles)if(/^tool\/[^/]+\.agenttool\.json$/i.test(p))files.push([p,v.text]);for(const[,text]of files)try{const d=JSON.parse(text);if(/^[a-z0-9_.-]{3,80}$/i.test(d.id)&&Array.isArray(d.steps)&&!catalog.some(x=>x.id===d.id))customTools.set(d.id,d)}catch{}}finally{refreshHandshake()}}
function renderChanges(){const h=$('#changes');h.innerHTML=changes.size?[...changes].map(([p,v])=>`<div class="change"><code>${esc(p)}</code><span class="tag">${esc(v.type)}</span></div>`).join(''):'<p class="muted">変更はまだありません。</p>'}
async function downloadChanged(){if(!changes.size){alert('変更はありません。');return}for(const[p,v]of changes){if(v.type==='delete'||v.type==='mkdir')continue;const blob=new Blob([await readText(p)],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=baseName(p)||'file.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);await new Promise(r=>setTimeout(r,100))}}
$('#pick-folder').onclick=chooseDirect;$('#folder-input').onchange=e=>loadMemoryFiles([...e.target.files]);$('#copy-handshake').onclick=async()=>{refreshHandshake();const ok=await copyText($('#handshake').value);$('#copy-handshake').textContent=ok?'✓ コピーしました':'コピー失敗';setTimeout(()=>$('#copy-handshake').textContent='📋 AI用説明をコピー',1200)};$('#copy-detailed')?.addEventListener('click',async()=>{const text=toolPrompt(true),ok=await copyText(text);$('#handshake').value=text;$('#handshake').classList.remove('compact');const b=$('#copy-detailed');b.textContent=ok?'✓ 詳細説明をコピー':'コピー失敗';setTimeout(()=>b.textContent='📚 詳細説明をコピー',1200)});$('#preview-handshake').onclick=()=>$('#handshake').classList.toggle('compact');$('#run').onclick=runCommand;$('#copy-result').onclick=()=>copyText($('#result').value);$('#clear-json').onclick=()=>$('#command').value='';$('#sample-json').onclick=()=>$('#command').value=JSON.stringify({version:1,actions:[{id:'a1',tool:'project.quick_context',args:{path:'.'}},{id:'a2',tool:'agent.search_tools',args:{query:'部分編集 エラーチェック',maxResults:8}}]},null,2);$('#format-json')?.addEventListener('click',()=>{try{const p=parseAgentRequest($('#command').value);$('#command').value=JSON.stringify(p.request,null,2);$('#run-status').textContent='JSONを正規化しました。'}catch(e){$('#run-status').textContent='JSON正規化エラー: '+e.message}});$('#download-all').onclick=downloadChanged;$('#reload-custom-tools').onclick=loadCustomTools;setInfo();refreshHandshake();
})();
