'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const STORE='pclocaltool_universal_timer_v1';
const state={settings:{volume:65,muted:false,sound:'gentle'},countdown:{duration:300000,remaining:300000,running:false,endAt:0,finishedAt:0,repeat:1,doneRepeats:0,countUp:false,name:'タイマー',marks:[]},sw:{running:false,startAt:0,elapsed:0,laps:[]},interval:{work:30000,rest:15000,prepare:5000,rounds:5,endRest:false,phase:'prepare',round:1,remaining:5000,endAt:0,running:false},pomo:{work:1500000,short:300000,long:900000,cycles:4,phase:'work',cycle:1,remaining:1500000,endAt:0,running:false,done:0,focusTotal:0},alarms:[],multis:[]};
let audioCtx=null,alertLoop=null,toastTimer=null;

function load(){try{const v=JSON.parse(localStorage.getItem(STORE)||'null');if(!v)return;Object.assign(state.settings,v.settings||{});for(const k of ['countdown','sw','interval','pomo'])Object.assign(state[k],v[k]||{});state.alarms=Array.isArray(v.alarms)?v.alarms:[];state.multis=Array.isArray(v.multis)?v.multis:[]}catch{}}
function save(){try{localStorage.setItem(STORE,JSON.stringify(state))}catch{}}
function clamp(n,a,b){return Math.min(b,Math.max(a,n))}
function pad(n,l=2){return String(Math.floor(Math.abs(n))).padStart(l,'0')}
function formatMs(ms,centi=false){ms=Math.max(0,ms);const total=Math.floor(ms/1000),h=Math.floor(total/3600),m=Math.floor(total%3600/60),s=total%60;if(centi){const c=Math.floor(ms%1000/10);return h?`${pad(h)}:${pad(m)}:${pad(s)}.${pad(c)}`:`${pad(m)}:${pad(s)}.${pad(c)}`}return h?`${pad(h)}:${pad(m)}:${pad(s)}`:`${pad(m)}:${pad(s)}`}
function formatOver(ms){return `+${formatMs(ms)}`}
function parseDuration(text){let s=String(text||'').trim().toLowerCase().replace(/[０-９]/g,c=>String.fromCharCode(c.charCodeAt(0)-0xFEE0)).replace(/：/g,':');if(!s)return NaN;if(/^\d+(?:\.\d+)?$/.test(s))return Number(s)*1000;const colon=s.match(/^(\d+):([0-5]?\d)(?::([0-5]?\d))?$/);if(colon){return colon[3]?(+colon[1]*3600 + +colon[2]*60 + +colon[3])*1000:(+colon[1]*60 + +colon[2])*1000}let total=0,found=false;const units=[[/([\d.]+)\s*(?:時間|hours?|hrs?|h)/g,3600000],[/([\d.]+)\s*(?:分|minutes?|mins?|m)(?!s)/g,60000],[/([\d.]+)\s*(?:秒|seconds?|secs?|s)/g,1000],[/([\d.]+)\s*(?:ミリ秒|milliseconds?|ms)/g,1]];for(const [re,mul] of units){for(const x of s.matchAll(re)){total+=Number(x[1])*mul;found=true}}return found&&Number.isFinite(total)?total:NaN}
function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),1800)}
function progressRing(el,remaining,total){const p=total>0?clamp(1-remaining/total,0,1):0;el.style.setProperty('--progress',`${p*360}deg`)}
function currentView(){return $('.view.active')?.id||'timer'}
function setView(id){$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));}

function ensureAudio(){if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}
function tone(freq,start,dur,gain=.12){if(state.settings.muted||state.settings.volume<=0)return;try{const c=ensureAudio(),o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(0,c.currentTime+start);g.gain.linearRampToValueAtTime(gain*(state.settings.volume/100),c.currentTime+start+.015);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+start+dur);o.connect(g).connect(c.destination);o.start(c.currentTime+start);o.stop(c.currentTime+start+dur+.03)}catch{}}
function playSound(){const p=state.settings.sound;if(p==='gentle'){tone(660,0,.18);tone(880,.22,.3)}else if(p==='clear'){tone(880,0,.18,.16);tone(880,.25,.18,.16)}else{tone(740,0,.15,.14);tone(740,.2,.15,.14);tone(980,.4,.3,.14)}}
function showAlert(title,text){playSound();$('#alertTitle').textContent=title;$('#alertText').textContent=text||'';$('#alertOverlay').classList.remove('hidden');clearInterval(alertLoop);alertLoop=setInterval(playSound,3500)}
function dismissAlert(){clearInterval(alertLoop);alertLoop=null;$('#alertOverlay').classList.add('hidden')}

function setCountdownDuration(ms){ms=clamp(Math.round(ms),100,99*3600000+59*60000+59000);state.countdown.duration=ms;state.countdown.remaining=ms;state.countdown.running=false;state.countdown.endAt=0;state.countdown.finishedAt=0;state.countdown.doneRepeats=0;renderCountdown();save()}
function startCountdown(){const c=state.countdown;if(c.running)return;if(c.remaining<=0)c.remaining=c.duration;c.finishedAt=0;c.endAt=Date.now()+c.remaining;c.running=true;renderCountdown();save()}
function pauseCountdown(){const c=state.countdown;if(!c.running)return;c.remaining=Math.max(0,c.endAt-Date.now());c.running=false;c.endAt=0;renderCountdown();save()}
function resetCountdown(){const c=state.countdown;c.running=false;c.endAt=0;c.finishedAt=0;c.remaining=c.duration;c.doneRepeats=0;c.marks=[];renderCountdown();save()}
function finishCountdown(){const c=state.countdown;c.doneRepeats++;const shouldRepeat=c.repeat===0||c.doneRepeats<c.repeat;if(shouldRepeat){playSound();c.remaining=c.duration;c.endAt=Date.now()+c.duration;c.running=true;toast(`繰り返し ${c.doneRepeats+1}${c.repeat?` / ${c.repeat}`:''}`)}else{c.running=false;c.finishedAt=Date.now();c.endAt=0;c.remaining=0;showAlert(c.name||'タイマー','時間になりました。')}save()}
function tickCountdown(now){const c=state.countdown;if(c.running){const rem=c.endAt-now;if(rem<=0)finishCountdown();else c.remaining=rem}renderCountdown(now)}
function renderCountdown(now=Date.now()){const c=state.countdown;$('#timerLabel').textContent=c.name||'タイマー';const over=!c.running&&c.remaining<=0&&c.countUp&&c.finishedAt?now-c.finishedAt:0;$('#timerDisplay').textContent=over>0?formatOver(over):formatMs(c.remaining);$('#timerSub').textContent=c.running?`実行中${c.repeat!==1?` ・ ${c.doneRepeats+1}${c.repeat?` / ${c.repeat}`:''}回目`:''}`:c.remaining<=0?'終了':'停止中';progressRing($('#timerRing'),c.remaining,c.duration);$('#timerStart').disabled=c.running;$('#timerPause').disabled=!c.running;$('#timerMarks').classList.toggle('empty',!c.marks.length);$('#timerMarks').innerHTML=c.marks.length?c.marks.map((m,i)=>`<div class="list-item"><span>#${i+1}</span><strong>${formatMs(m)}</strong></div>`).join(''):'まだありません。'}

function swElapsed(now=Date.now()){const s=state.sw;return s.elapsed+(s.running?now-s.startAt:0)}
function toggleSw(){const s=state.sw;if(s.running){s.elapsed+=Date.now()-s.startAt;s.running=false}else{s.startAt=Date.now();s.running=true}save();renderSw()}
function resetSw(){state.sw={running:false,startAt:0,elapsed:0,laps:[]};save();renderSw()}
function lapSw(){const total=swElapsed();if(total<1)return;const prev=state.sw.laps.length?state.sw.laps.at(-1).total:0;state.sw.laps.push({total,split:total-prev});save();renderSw()}
function renderSw(now=Date.now()){const s=state.sw,e=swElapsed(now);$('#swDisplay').textContent=formatMs(e,true);$('#swSub').textContent=s.running?'計測中':'停止中';$('#swStart').textContent=s.running?'⏸ 一時停止':'▶ 開始';const laps=[...s.laps].reverse();$('#laps').classList.toggle('empty',!laps.length);$('#laps').innerHTML=laps.length?laps.map((x,idx)=>{const n=s.laps.length-idx;return `<div class="list-item"><span>Lap ${n}<br><small>区間 ${formatMs(x.split,true)}</small></span><strong>${formatMs(x.total,true)}</strong></div>`}).join(''):'まだラップがありません。'}

function intervalPhaseDuration(i){if(i.phase==='prepare')return i.prepare;if(i.phase==='work')return i.work;return i.rest}
function resetInterval(){const i=state.interval;i.running=false;i.phase=i.prepare>0?'prepare':'work';i.round=1;i.remaining=intervalPhaseDuration(i);i.endAt=0;renderInterval();save()}
function toggleInterval(){const i=state.interval;if(i.running){i.remaining=Math.max(0,i.endAt-Date.now());i.running=false;i.endAt=0}else{i.endAt=Date.now()+Math.max(1,i.remaining);i.running=true}renderInterval();save()}
function advanceInterval(){const i=state.interval;playSound();if(i.phase==='prepare'){i.phase='work'}else if(i.phase==='work'){if(i.round>=i.rounds&&!i.endRest){i.running=false;i.remaining=0;showAlert('インターバル完了',`${i.rounds}ラウンド終了しました。`);save();return}i.phase='rest'}else{if(i.round>=i.rounds){i.running=false;i.remaining=0;showAlert('インターバル完了',`${i.rounds}ラウンド終了しました。`);save();return}i.round++;i.phase='work'}i.remaining=intervalPhaseDuration(i);i.endAt=Date.now()+i.remaining;save()}
function tickInterval(now){const i=state.interval;if(i.running){i.remaining=i.endAt-now;if(i.remaining<=0)advanceInterval()}renderInterval()}
function renderInterval(){const i=state.interval;const names={prepare:'準備',work:'運動',rest:'休憩'};$('#intervalPhase').textContent=names[i.phase];$('#intervalDisplay').textContent=formatMs(Math.max(0,i.remaining));$('#intervalSub').textContent=`ラウンド ${i.round} / ${i.rounds}${i.running?' ・ 実行中':''}`;progressRing($('#intervalRing'),Math.max(0,i.remaining),intervalPhaseDuration(i));$('#intervalStart').textContent=i.running?'▶ 実行中':'▶ 開始';$('#intervalPause').disabled=!i.running}

function pomoDuration(p){return p.phase==='work'?p.work:p.phase==='short'?p.short:p.long}
function resetPomo(){const p=state.pomo;p.running=false;p.phase='work';p.cycle=1;p.remaining=p.work;p.endAt=0;renderPomo();save()}
function togglePomo(){const p=state.pomo;if(p.running){p.remaining=Math.max(0,p.endAt-Date.now());p.running=false;p.endAt=0}else{p.endAt=Date.now()+Math.max(1,p.remaining);p.running=true}renderPomo();save()}
function advancePomo(manual=false){const p=state.pomo;if(!manual)playSound();if(p.phase==='work'){p.done++;p.focusTotal+=p.work;const long=p.cycle%p.cycles===0;p.phase=long?'long':'short'}else{p.cycle++;p.phase='work'}p.remaining=pomoDuration(p);if(p.running)p.endAt=Date.now()+p.remaining;save();renderPomo()}
function tickPomo(now){const p=state.pomo;if(p.running){p.remaining=p.endAt-now;if(p.remaining<=0)advancePomo()}renderPomo()}
function renderPomo(){const p=state.pomo,n={work:'集中',short:'短い休憩',long:'長い休憩'};$('#pomoPhase').textContent=n[p.phase];$('#pomoDisplay').textContent=formatMs(Math.max(0,p.remaining));$('#pomoSub').textContent=`${p.cycle} / ${p.cycles} セッション${p.running?' ・ 実行中':''}`;progressRing($('#pomoRing'),Math.max(0,p.remaining),pomoDuration(p));$('#pomoStart').textContent=p.running?'⏸ 一時停止':'▶ 開始';$('#pomoDone').textContent=p.done;$('#pomoFocusTotal').textContent=`${Math.round(p.focusTotal/60000)}分`}

function alarmNext(time){const [h,m]=time.split(':').map(Number),d=new Date();d.setHours(h,m,0,0);if(d.getTime()<=Date.now())d.setDate(d.getDate()+1);return d.getTime()}
function addAlarm(){const time=$('#alarmTime').value;if(!time){toast('時刻を設定してください');return}state.alarms.push({id:cryptoRandom(),time,name:$('#alarmName').value.trim()||'アラーム',nextAt:alarmNext(time),enabled:true,lastFire:0});$('#alarmName').value='';save();renderAlarms()}
function cryptoRandom(){try{return crypto.randomUUID()}catch{return `${Date.now()}_${Math.random()}`}}
function tickAlarms(now){let changed=false;for(const a of state.alarms){if(a.enabled&&a.nextAt<=now&&now-a.lastFire>30000){a.lastFire=now;showAlert(a.name,`${a.time} のアラームです。`);a.nextAt=alarmNext(a.time);changed=true}}if(changed){save();renderAlarms()}}
function renderAlarms(){const b=$('#alarms'),a=state.alarms;b.classList.toggle('empty',!a.length);b.innerHTML=a.length?a.sort((x,y)=>x.time.localeCompare(y.time)).map(x=>`<div class="list-item" data-alarm="${x.id}"><span><strong>${x.time}</strong><br><small>${esc(x.name)} ・ 次回 ${new Date(x.nextAt).toLocaleDateString('ja-JP')}</small></span><span><button class="btn mini alarm-toggle">${x.enabled?'ON':'OFF'}</button> <button class="btn mini alarm-del">削除</button></span></div>`).join(''):'アラームはありません。'}

function newMulti(){return{id:cryptoRandom(),name:`タイマー ${state.multis.length+1}`,duration:300000,remaining:300000,endAt:0,running:false,done:false}}
function multiRemaining(x,now=Date.now()){return x.running?Math.max(0,x.endAt-now):x.remaining}
function toggleMulti(id){const x=state.multis.find(v=>v.id===id);if(!x)return;if(x.done){x.done=false;x.remaining=x.duration}if(x.running){x.remaining=Math.max(0,x.endAt-Date.now());x.running=false;x.endAt=0}else{x.endAt=Date.now()+Math.max(1,x.remaining);x.running=true}save();renderMultis()}
function tickMultis(now){let changed=false;for(const x of state.multis){if(x.running&&x.endAt<=now){x.running=false;x.remaining=0;x.done=true;x.endAt=0;changed=true;showAlert(x.name,'複数タイマーが終了しました。')}}if(changed)save();renderMultis(now)}
function renderMultis(now=Date.now()){const g=$('#multiGrid');if(!state.multis.length){g.innerHTML='<div class="hint">右上の「タイマー追加」から複数の時間を同時に管理できます。</div>';return}g.innerHTML=state.multis.map(x=>{const rem=multiRemaining(x,now),pct=x.duration?clamp((1-rem/x.duration)*100,0,100):0;return `<div class="multi-card ${x.done?'done':''}" data-id="${x.id}"><div class="multi-title"><input class="input multi-name" value="${escAttr(x.name)}" maxlength="30"><button class="btn mini multi-del">削除</button></div><div class="multi-time">${x.done?'終了':formatMs(rem)}</div><div class="multi-progress"><i style="width:${pct}%"></i></div><div class="input-row"><input class="input multi-duration" value="${durationShort(x.duration)}"><button class="btn mini multi-set">設定</button></div><div class="controls compact"><button class="btn primary multi-toggle">${x.running?'⏸ 停止':'▶ 開始'}</button><button class="btn multi-reset">↺</button></div></div>`}).join('')}
function durationShort(ms){if(ms%3600000===0)return `${ms/3600000}時間`;if(ms%60000===0)return `${ms/60000}分`;return `${Math.round(ms/1000)}秒`}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function escAttr(s){return esc(s)}

function toggleFocus(){document.body.classList.toggle('focus-mode');if(document.body.classList.contains('focus-mode')&&document.documentElement.requestFullscreen){document.documentElement.requestFullscreen().catch(()=>{})}else if(!document.body.classList.contains('focus-mode')&&document.fullscreenElement){document.exitFullscreen().catch(()=>{})}}
function syncInputs(){const c=state.countdown;$('#durationText').value=durationShort(c.duration);$('#countdownName').value=c.name;$('#countdownRepeat').value=String(c.repeat);$('#countUpAfter').checked=c.countUp;$('#volume').value=state.settings.volume;$('#soundPattern').value=state.settings.sound;$('#muteBtn').textContent=state.settings.muted?'🔇':'🔊';const i=state.interval;$('#workTime').value=durationShort(i.work);$('#restTime').value=durationShort(i.rest);$('#prepareTime').value=durationShort(i.prepare);$('#rounds').value=i.rounds;$('#intervalEndRest').checked=i.endRest;const p=state.pomo;$('#pomoWork').value=durationShort(p.work);$('#pomoShort').value=durationShort(p.short);$('#pomoLong').value=durationShort(p.long);$('#pomoCycles').value=p.cycles;const d=new Date(Date.now()+3600000);$('#alarmTime').value=`${pad(d.getHours())}:${pad(d.getMinutes())}`}
function renderAll(){renderCountdown();renderSw();renderInterval();renderPomo();renderAlarms();renderMultis();}

$$('.tab').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
$('#applyDuration').onclick=()=>{const v=parseDuration($('#durationText').value);if(!Number.isFinite(v)||v<=0)return toast('時間を「5分」「90s」「12:30」などで入力してください');setCountdownDuration(v)};
$('#presets').onclick=e=>{const b=e.target.closest('[data-sec]');if(b)setCountdownDuration(+b.dataset.sec*1000)};
$('#timerStart').onclick=startCountdown;$('#timerPause').onclick=pauseCountdown;$('#timerReset').onclick=resetCountdown;
$$('[data-add-ms]').forEach(b=>b.onclick=()=>{const c=state.countdown,delta=+b.dataset.addMs;if(c.running)c.endAt=Math.max(Date.now()+100,c.endAt+delta);else c.remaining=clamp(c.remaining+delta,100,99*3600000);c.duration=Math.max(c.duration,c.remaining);save();renderCountdown()});
$('#timerAddLap').onclick=()=>{const r=state.countdown.running?Math.max(0,state.countdown.endAt-Date.now()):state.countdown.remaining;state.countdown.marks.push(r);save();renderCountdown()};
$('#countdownName').onchange=e=>{state.countdown.name=e.target.value.trim()||'タイマー';save();renderCountdown()};$('#countdownRepeat').onchange=e=>{state.countdown.repeat=+e.target.value;save()};$('#countUpAfter').onchange=e=>{state.countdown.countUp=e.target.checked;save()};
$('#timerFullscreen').onclick=toggleFocus;$('#swFullscreen').onclick=toggleFocus;
$('#swStart').onclick=toggleSw;$('#swLap').onclick=lapSw;$('#swReset').onclick=resetSw;$('#copyLaps').onclick=async()=>{const t=state.sw.laps.map((x,i)=>`Lap ${i+1}\t${formatMs(x.total,true)}\t区間 ${formatMs(x.split,true)}`).join('\n');if(!t)return toast('ラップがありません');try{await navigator.clipboard.writeText(t);toast('ラップをコピーしました')}catch{toast('このブラウザではコピーできません')}};
$('#applyInterval').onclick=()=>{const work=parseDuration($('#workTime').value),rest=parseDuration($('#restTime').value),prep=parseDuration($('#prepareTime').value)||0,rounds=+$('#rounds').value;if(!(work>0&&rest>=0&&rounds>=1))return toast('インターバル設定を確認してください');Object.assign(state.interval,{work,rest,prepare:prep,rounds:clamp(Math.floor(rounds),1,999),endRest:$('#intervalEndRest').checked});resetInterval();toast('設定しました')};$('#intervalStart').onclick=()=>{if(!state.interval.running)toggleInterval()};$('#intervalPause').onclick=toggleInterval;$('#intervalReset').onclick=resetInterval;
$('#applyPomo').onclick=()=>{const work=parseDuration($('#pomoWork').value),short=parseDuration($('#pomoShort').value),long=parseDuration($('#pomoLong').value),cycles=+$('#pomoCycles').value;if(!(work>0&&short>0&&long>0&&cycles>=1))return toast('ポモドーロ設定を確認してください');Object.assign(state.pomo,{work,short,long,cycles:clamp(Math.floor(cycles),1,20)});resetPomo();toast('設定しました')};$('#pomoStart').onclick=togglePomo;$('#pomoSkip').onclick=()=>advancePomo(true);$('#pomoReset').onclick=resetPomo;
$('#addAlarm').onclick=addAlarm;$('#clearAlarms').onclick=()=>{state.alarms=[];save();renderAlarms()};$('#alarms').onclick=e=>{const row=e.target.closest('[data-alarm]');if(!row)return;const x=state.alarms.find(a=>a.id===row.dataset.alarm);if(!x)return;if(e.target.closest('.alarm-del'))state.alarms=state.alarms.filter(a=>a.id!==x.id);if(e.target.closest('.alarm-toggle')){x.enabled=!x.enabled;if(x.enabled)x.nextAt=alarmNext(x.time)}save();renderAlarms()};
$('#addMulti').onclick=()=>{if(state.multis.length>=12)return toast('同時タイマーは12個までです');state.multis.push(newMulti());save();renderMultis()};$('#multiGrid').onclick=e=>{const card=e.target.closest('[data-id]');if(!card)return;const id=card.dataset.id,x=state.multis.find(v=>v.id===id);if(!x)return;if(e.target.closest('.multi-toggle'))toggleMulti(id);else if(e.target.closest('.multi-reset')){x.running=false;x.done=false;x.endAt=0;x.remaining=x.duration;save();renderMultis()}else if(e.target.closest('.multi-del')){state.multis=state.multis.filter(v=>v.id!==id);save();renderMultis()}else if(e.target.closest('.multi-set')){const v=parseDuration($('.multi-duration',card).value);if(!(v>0))return toast('時間を確認してください');x.duration=v;x.remaining=v;x.running=false;x.done=false;x.endAt=0;save();renderMultis()}};$('#multiGrid').onchange=e=>{if(!e.target.classList.contains('multi-name'))return;const card=e.target.closest('[data-id]'),x=state.multis.find(v=>v.id===card.dataset.id);if(x){x.name=e.target.value.trim()||'タイマー';save()}};
$('#muteBtn').onclick=()=>{state.settings.muted=!state.settings.muted;$('#muteBtn').textContent=state.settings.muted?'🔇':'🔊';save()};$('#volume').oninput=e=>{state.settings.volume=+e.target.value;save()};$('#soundPattern').onchange=e=>{state.settings.sound=e.target.value;save()};$('#testSound').onclick=playSound;$('#dismissAlert').onclick=dismissAlert;$('#alertOverlay').onclick=e=>{if(e.target===$('#alertOverlay'))dismissAlert()};
document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;if(e.code==='Space'){e.preventDefault();const v=currentView();if(v==='timer')state.countdown.running?pauseCountdown():startCountdown();else if(v==='stopwatch')toggleSw();else if(v==='interval')toggleInterval();else if(v==='pomodoro')togglePomo()}else if(e.key.toLowerCase()==='r'){const v=currentView();if(v==='timer')resetCountdown();else if(v==='stopwatch')resetSw();else if(v==='interval')resetInterval();else if(v==='pomodoro')resetPomo()}else if(e.key.toLowerCase()==='f')toggleFocus()});
document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement)document.body.classList.remove('focus-mode')});

function tick(){const now=Date.now();$('#clockPill').textContent=new Date(now).toLocaleTimeString('ja-JP',{hour12:false});tickCountdown(now);renderSw(now);tickInterval(now);tickPomo(now);tickAlarms(now);tickMultis(now);}
load();syncInputs();renderAll();setInterval(tick,100);tick();
