'use strict';
(() => {
const B=window.AgentBridge,R=B.register,A=B.api;
R('file.list',a=>A.list(a.path||''));
R('file.tree',a=>A.walk(a.path||'',Number(a.maxDepth??8)));
R('file.read_text',async a=>({path:A.norm(a.path),text:await A.readText(a.path)}));
R('file.read_lines',async a=>{const ls=(await A.readText(a.path)).split(/\r?\n/),s=Math.max(1,+a.start||1),e=Math.min(ls.length,+a.end||s+99);return{path:A.norm(a.path),start:s,end:e,text:ls.slice(s-1,e).join('\n')}});
R('file.write_text',a=>A.writeText(a.path,a.text));
R('file.append_text',async a=>A.writeText(a.path,(await A.safeRead(a.path))+String(a.text??'')));
R('file.prepend_text',async a=>A.writeText(a.path,String(a.text??'')+(await A.safeRead(a.path))));
R('file.create_empty',a=>A.writeText(a.path,''));
R('file.exists',async a=>{const s=B.state();return s.mode==='direct'?A.directExists(a.path):(await A.walk('',99)).some(x=>x.path===A.norm(a.path))});
R('file.stat',async a=>{const p=A.norm(a.path),s=B.state();if(s.mode==='direct'){try{const f=await(await A.getFileHandle(p)).getFile();return{path:p,type:'file',size:f.size,lastModified:f.lastModified}}catch{try{await A.getDir(p);return{path:p,type:'dir'}}catch{return null}}}return(await A.walk('',99)).find(x=>x.path===p)||null});
R('file.mkdir',a=>A.makeDir(a.path));R('file.delete',a=>A.deletePath(a.path));
for(const id of ['file.rename','file.move'])R(id,async a=>{const t=await A.readText(a.path);await A.writeText(a.newPath,t);await A.deletePath(a.path);return{from:A.norm(a.path),to:A.norm(a.newPath)}});
R('file.copy',async a=>A.writeText(a.newPath,await A.readText(a.path)));
R('file.search_text',async a=>{const q=String(a.query??''),cs=!!a.caseSensitive,max=+a.maxResults||100,res=[];for(const f of await A.walk(a.path||'',99)){if(f.type!=='file'||res.length>=max)continue;let t;try{t=await A.readText(f.path)}catch{continue}const hay=cs?t:t.toLowerCase(),needle=cs?q:q.toLowerCase();let idx=0;while((idx=hay.indexOf(needle,idx))>=0&&res.length<max){const line=t.slice(0,idx).split(/\r?\n/).length;res.push({path:f.path,line,preview:t.split(/\r?\n/)[line-1]?.slice(0,240)});idx+=Math.max(1,needle.length)}}return res});
R('file.find_name',async a=>(await A.walk(a.path||'',99)).filter(x=>x.path.toLowerCase().includes(String(a.query??'').toLowerCase())).slice(0,+a.maxResults||100));
R('file.replace_text',async a=>{let t=await A.readText(a.path),s=String(a.search),i=t.indexOf(s);if(i<0)return{changed:false};t=t.slice(0,i)+String(a.replace??'')+t.slice(i+s.length);await A.writeText(a.path,t);return{changed:true}});
R('file.replace_all',async a=>{let t=await A.readText(a.path),s=String(a.search);if(!s)return{changed:false,count:0};const n=t.split(s).length-1;await A.writeText(a.path,t.split(s).join(String(a.replace??'')));return{changed:n>0,count:n}});
R('file.regex_replace',async a=>{let t=await A.readText(a.path),re=new RegExp(a.pattern,a.flags||'g'),n=0;t=t.replace(re,(...m)=>{n++;return typeof a.replace==='string'?a.replace.replace(/\$(\d+)/g,(_,d)=>m[+d]??''):String(a.replace??'')});await A.writeText(a.path,t);return{changed:n>0,count:n}});
R('file.patch_lines',async a=>{let t=(await A.readText(a.path)).split(/\r?\n/),s=Math.max(1,+a.start||1),e=Math.max(s,+a.end||s);t.splice(s-1,e-s+1,...String(a.text??'').split(/\r?\n/));await A.writeText(a.path,t.join('\n'));return{changed:true,start:s,end:e}});
R('file.count_lines',async a=>(await A.readText(a.path)).split(/\r?\n/).length);
R('file.batch_read',async a=>{const o={};for(const p of a.paths||[])o[A.norm(p)]=await A.readText(p);return o});
R('file.batch_write',async a=>{const o=[];for(const f of a.files||[])o.push(await A.writeText(f.path,f.text));return o});
R('file.list_extensions',async a=>{const m={};for(const f of await A.walk(a.path||'',99)){if(f.type!=='file')continue;const b=A.baseName(f.path),e=b.includes('.')?'.'+b.split('.').pop().toLowerCase():'(none)';m[e]=(m[e]||0)+1}return m});
R('file.snapshot',async a=>(await A.walk(a.path||'',99)).filter(x=>x.type==='file').map(({path,size})=>({path,size})));
R('file.changed',()=>[...B.state().changes].map(([path,v])=>({path,...v})));
R('file.basename',a=>A.baseName(a.path));R('file.dirname',a=>A.parentPath(a.path));R('file.normalize_path',a=>A.norm(a.path));
R('project.readme_files',async a=>(await A.walk(a.path||'',99)).filter(x=>/\b(readme|contributing|license)(\.|$)/i.test(A.baseName(x.path))));
R('project.package_json',async a=>JSON.parse(await A.readText(A.norm((a.path?A.norm(a.path)+'/':'')+'package.json'))));
R('project.find_entrypoints',async a=>(await A.walk(a.path||'',99)).filter(x=>/\/(index|main|app)\.(html?|js|mjs|cjs|ts|tsx|jsx|py)$/i.test('/'+x.path)));
R('project.find_config',async a=>(await A.walk(a.path||'',99)).filter(x=>/(^|\/)(package\.json|tsconfig\.json|jsconfig\.json|vite\.config\.|webpack\.config\.|vercel\.json|\.gitignore|pyproject\.toml|requirements\.txt)$/i.test(x.path)));
R('project.scan_todos',async a=>{const out=[];let n=0,max=+a.maxFiles||100;for(const f of await A.walk(a.path||'',99)){if(f.type!=='file'||n++>=max)continue;let t;try{t=await A.readText(f.path)}catch{continue}const hits=t.split(/\r?\n/).map((x,i)=>({line:i+1,text:x})).filter(x=>/\b(TODO|FIXME|HACK|XXX)\b/i.test(x.text));if(hits.length)out.push({path:f.path,hits})}return out});
R('project.scan_extensions',async a=>{const m={};for(const f of await A.walk(a.path||'',99)){if(f.type!=='file')continue;const b=A.baseName(f.path),e=b.includes('.')?'.'+b.split('.').pop().toLowerCase():'(none)';m[e]=(m[e]||0)+1}return m});
R('project.search_symbol',async a=>{const q=String(a.query??''),res=[];for(const f of await A.walk(a.path||'',99)){if(f.type!=='file')continue;let t;try{t=await A.readText(f.path)}catch{continue}const lines=t.split(/\r?\n/);lines.forEach((x,i)=>{if(x.includes(q)&&res.length<200)res.push({path:f.path,line:i+1,preview:x.slice(0,240)})});if(res.length>=200)break}return res});
R('project.collect_text',async a=>{let out='',max=+a.maxChars||50000;for(const p of a.paths||[]){out+=`\n--- ${A.norm(p)} ---\n${await A.readText(p)}`;if(out.length>=max){out=out.slice(0,max);break}}return out});
R('project.make_manifest',async a=>(await A.walk(a.path||'',99)).filter(x=>x.type==='file').map(x=>({path:x.path,size:x.size||0})));
R('project.summary',async a=>{const fs=(await A.walk(a.path||'',99)).filter(x=>x.type==='file'),max=+a.maxFiles||500,ext={};for(const f of fs.slice(0,max)){const b=A.baseName(f.path),e=b.includes('.')?'.'+b.split('.').pop().toLowerCase():'(none)';ext[e]=(ext[e]||0)+1}return{files:fs.length,totalBytes:fs.reduce((s,x)=>s+(x.size||0),0),extensions:ext,topFiles:fs.slice(0,40)}});
})();
