'use strict';
(() => {
const B=window.AgentBridge,R=B.register,A=B.api;
const catalog=()=>window.AGENT_TOOL_CATALOG||[];
const enc=new TextEncoder();
const lines=t=>String(t??'').split(/\r?\n/);
const hash=async text=>{const b=await crypto.subtle.digest('SHA-256',enc.encode(String(text)));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')};
const clone=x=>structuredClone(x);
function deepDelete(obj,path){const parts=String(path||'').split('.').filter(Boolean),root=clone(obj);if(!parts.length)return undefined;let o=root;for(let i=0;i<parts.length-1;i++){if(o==null||typeof o!=='object')return root;o=o[parts[i]]}if(Array.isArray(o)&&/^\d+$/.test(parts.at(-1)))o.splice(+parts.at(-1),1);else if(o&&typeof o==='object')delete o[parts.at(-1)];return root}
async function readJson(path){const text=await A.readText(path);try{return JSON.parse(text)}catch(e){throw Error(`Invalid JSON in ${A.norm(path)}: ${e.message}`)}}
async function writeJson(path,value,indent=2){const n=Math.max(0,Math.min(8,Number(indent??2)));return A.writeText(path,JSON.stringify(value,null,n)+(n?'\n':''))}
function details(t){return t?{id:t.id,description:t.description,args:t.args||{},usage:t.usage||null,example:t.example||null,notes:t.notes||null,group:t.group||t.id.split('.')[0]}:null}
function scoreTool(t,q){q=String(q||'').toLowerCase().trim();if(!q)return 1;const words=q.split(/\s+/).filter(Boolean),hay=[t.id,t.description,t.args,t.usage,t.notes].map(x=>typeof x==='string'?x:JSON.stringify(x||'')).join(' ').toLowerCase();let s=0;for(const w of words){if(t.id.toLowerCase().includes(w))s+=5;if(hay.includes(w))s+=2}return s}

R('agent.protocol_help',()=>({
  version:1,
  acceptedInput:['標準 {version:1,actions:[...]}','actionsだけのオブジェクト','単一 {tool,args}','action配列 [...]','```jsonコードブロック','前後に説明文があるJSON','JSON Lines(1行1action)'],
  actionReference:'後続actionのargs内で {{results.a1.result.text}} のように前action結果を参照可能。文字列全体が{{...}}だけなら配列/オブジェクトも型を保ったまま渡す。',
  recommended:'1回3〜10 action程度。巨大ファイルはread_chunk/read_around、JSONはjson.file_*、編集はdryRun可能な部分編集を優先。',
  completion:'作業が終わったらJSONではなく通常の日本語で完了内容を説明する。追加tool実行が必要な間だけJSONを返す。'
}));
R('agent.search_tools',a=>catalog().map(t=>({t,score:scoreTool(t,a.query)})).filter(x=>x.score>0).sort((x,y)=>y.score-x.score).slice(0,+a.maxResults||20).map(x=>details(x.t)));
R('agent.tool_help',a=>{const t=catalog().find(x=>x.id===a.toolId);if(!t)throw Error('Unknown tool: '+a.toolId);return details(t)});
R('agent.group_help',a=>catalog().filter(t=>(t.group||t.id.split('.')[0])===String(a.group)).map(details));
R('agent.list_tools',a=>catalog().filter(t=>!a.group||(t.group||t.id.split('.')[0])===a.group).map(t=>({id:t.id,description:t.description,args:t.args||{}})));
R('agent.list_groups',()=>{const m={};for(const t of catalog()){const g=t.group||t.id.split('.')[0];m[g]=(m[g]||0)+1}return m});
R('agent.examples',a=>{const topic=String(a.topic||'').toLowerCase();const all={
read:{version:1,actions:[{id:'a1',tool:'project.quick_context',args:{path:'.'}},{id:'a2',tool:'file.read_around',args:{path:'app.js',search:'function startGame',beforeLines:5,afterLines:25}}]},
edit:{version:1,actions:[{id:'a1',tool:'file.apply_patch_exact',args:{path:'app.js',find:'const enabled = false;',replace:'const enabled = true;',expectedCount:1,dryRun:true}},{id:'a2',tool:'file.apply_patch_exact',args:{path:'app.js',find:'const enabled = false;',replace:'const enabled = true;',expectedCount:1,dryRun:false}},{id:'a3',tool:'project.verify_after_edit',args:{}}]},
json:{version:1,actions:[{id:'a1',tool:'json.file_get',args:{path:'config.json',jsonPath:'ui'}},{id:'a2',tool:'json.file_set',args:{path:'config.json',jsonPath:'ui.theme',value:'dark'}},{id:'a3',tool:'json.file_validate',args:{path:'config.json'}}]},
chaining:{version:1,actions:[{id:'a1',tool:'file.read_text',args:{path:'README.md'}},{id:'a2',tool:'text.char_count',args:{text:'{{results.a1.result.text}}'}}]},
diagnose:{version:1,actions:[{id:'a1',tool:'project.diagnostics',args:{path:'.',maxFiles:300,maxResults:300}}]}
};return all[topic]||all});
R('agent.recommended_workflow',a=>{const t=String(a.task||'');return{task:t,steps:[
'project.quick_context か file.list で構造確認','対象が不明なら agent.search_tools / agent.tool_help','file.read_around / file.read_lines で編集対象だけ読む','部分編集は dryRun=true で一致件数確認','dryRun=false で適用','project.verify_after_edit で変更ファイル診断','必要なら project.diagnostics で全体診断','問題が無ければ通常文でユーザーへ完了報告']}});
R('agent.validate_request',a=>{if(!A.parseAgentRequest)throw Error('Request parser unavailable');const raw=a.text!=null?String(a.text):JSON.stringify(a.value);const r=A.parseAgentRequest(raw);return{valid:true,normalized:r.request,warnings:r.warnings||[],source:r.source||'json'}});
R('agent.suggest_tools',a=>catalog().map(t=>({id:t.id,description:t.description,score:scoreTool(t,a.task)})).filter(x=>x.score>0).sort((x,y)=>y.score-x.score).slice(0,+a.maxResults||12));

R('json.file_read',async a=>({path:A.norm(a.path),value:await readJson(a.path)}));
R('json.file_write',async a=>writeJson(a.path,a.value,a.indent));
R('json.file_get',async a=>({path:A.norm(a.path),jsonPath:String(a.jsonPath||''),value:A.deepGet(await readJson(a.path),a.jsonPath)}));
R('json.file_set',async a=>writeJson(a.path,A.deepSet(await readJson(a.path),a.jsonPath,a.value),a.indent));
R('json.file_delete',async a=>writeJson(a.path,deepDelete(await readJson(a.path),a.jsonPath),a.indent));
R('json.file_merge',async a=>{let root=await readJson(a.path),cur=A.deepGet(root,a.jsonPath);if(cur==null)cur={};if(!cur||Array.isArray(cur)||typeof cur!=='object'||!a.value||Array.isArray(a.value)||typeof a.value!=='object')throw Error('Merge target and value must be objects');return writeJson(a.path,A.deepSet(root,a.jsonPath,{...cur,...a.value}),a.indent)});
for(const [id,mode] of [['json.file_push','push'],['json.file_unshift','unshift']])R(id,async a=>{let root=await readJson(a.path),arr=A.deepGet(root,a.jsonPath);if(!Array.isArray(arr))throw Error('Target is not an array: '+a.jsonPath);arr=[...arr];arr[mode](a.value);return writeJson(a.path,A.deepSet(root,a.jsonPath,arr),a.indent)});
R('json.file_insert',async a=>{let root=await readJson(a.path),arr=A.deepGet(root,a.jsonPath);if(!Array.isArray(arr))throw Error('Target is not an array');arr=[...arr];const i=Math.max(0,Math.min(arr.length,+a.index||0));arr.splice(i,0,a.value);return writeJson(a.path,A.deepSet(root,a.jsonPath,arr),a.indent)});
R('json.file_remove_index',async a=>{let root=await readJson(a.path),arr=A.deepGet(root,a.jsonPath);if(!Array.isArray(arr))throw Error('Target is not an array');arr=[...arr];const i=+a.index;if(!Number.isInteger(i)||i<0||i>=arr.length)throw Error('Index out of range');arr.splice(i,1);return writeJson(a.path,A.deepSet(root,a.jsonPath,arr),a.indent)});
R('json.file_format',async a=>writeJson(a.path,await readJson(a.path),a.indent));
R('json.file_validate',async a=>{const p=A.norm(a.path),t=await A.readText(p);try{const v=JSON.parse(t);return{path:p,valid:true,type:Array.isArray(v)?'array':typeof v}}catch(e){return{path:p,valid:false,message:e.message}}});

R('file.read_chunk',async a=>{const p=A.norm(a.path),t=await A.readText(p),s=Math.max(0,+a.startChar||0),n=Math.max(1,Math.min(100000,+a.maxChars||12000)),end=Math.min(t.length,s+n);return{path:p,startChar:s,endChar:end,totalChars:t.length,hasMore:end<t.length,text:t.slice(s,end)}});
R('file.read_around',async a=>{const p=A.norm(a.path),t=await A.readText(p),ls=lines(t),search=String(a.search??'');if(!search)throw Error('search is required');let from=0,idx=-1,occ=Math.max(1,+a.occurrence||1);for(let n=0;n<occ;n++){idx=t.indexOf(search,from);if(idx<0)throw Error(`Occurrence ${occ} not found`);from=idx+Math.max(1,search.length)}const line=t.slice(0,idx).split(/\r?\n/).length,b=Math.max(0,+a.beforeLines||5),af=Math.max(0,+a.afterLines||15),start=Math.max(1,line-b),end=Math.min(ls.length,line+af);return{path:p,matchLine:line,start,end,text:ls.slice(start-1,end).join('\n')}});
R('file.read_matches',async a=>{const p=A.norm(a.path),t=await A.readText(p),ls=lines(t),q=String(a.search??'');if(!q)throw Error('search is required');const out=[];let pos=0,max=+a.maxResults||20;while(out.length<max&&(pos=t.indexOf(q,pos))>=0){const line=t.slice(0,pos).split(/\r?\n/).length,b=Math.max(0,+a.beforeLines||2),af=Math.max(0,+a.afterLines||4),start=Math.max(1,line-b),end=Math.min(ls.length,line+af);out.push({line,start,end,text:ls.slice(start-1,end).join('\n')});pos+=Math.max(1,q.length)}return out});
R('file.apply_edits',async a=>{const p=A.norm(a.path),original=await A.readText(p),edits=Array.isArray(a.edits)?a.edits:[];if(!edits.length)throw Error('edits array is required');let out=original,report=[];for(let i=0;i<edits.length;i++){const e=edits[i],find=String(e.find??'');if(!find)throw Error(`edits[${i}].find is required`);const count=out.split(find).length-1,expected=e.expectedCount==null?1:+e.expectedCount;if(count!==expected)throw Error(`Edit ${i+1} refused: expected ${expected} match(es), found ${count}`);out=out.split(find).join(String(e.replace??''));report.push({index:i,count})}if(a.dryRun)return{path:p,dryRun:true,changed:out!==original,report,bytesBefore:enc.encode(original).length,bytesAfter:enc.encode(out).length};return{...(await A.writeText(p,out)),changed:out!==original,report}});
R('file.patch_by_context',async a=>{const p=A.norm(a.path),t=await A.readText(p),before=String(a.before??''),target=String(a.target??''),after=String(a.after??''),replace=String(a.replace??'');if(!target)throw Error('target is required');const full=before+target+after,count=t.split(full).length-1;if(count!==1)throw Error(`Context patch refused: combined context matched ${count} times`);const patched=before+replace+after,out=t.replace(full,patched);if(a.dryRun)return{path:p,dryRun:true,changed:true,matchCount:1,preview:patched.slice(0,1200)};return{...(await A.writeText(p,out)),changed:true}});
R('file.write_if_unchanged',async a=>{const p=A.norm(a.path),old=await A.readText(p),actual=await hash(old);if(actual!==String(a.expectedSha256||''))throw Error(`Write refused: SHA-256 changed. actual=${actual}`);return A.writeText(p,a.text)});
for(const [id,pos] of [['file.append_lines','append'],['file.prepend_lines','prepend']])R(id,async a=>{const chunk=(Array.isArray(a.lines)?a.lines:[]).map(x=>String(x)).join('\n')+(a.finalNewline===false?'':'\n'),old=await A.safeRead(a.path);return A.writeText(a.path,pos==='append'?old+chunk:chunk+old)});
R('file.write_lines',a=>A.writeText(a.path,(Array.isArray(a.lines)?a.lines:[]).map(x=>String(x)).join('\n')+(a.finalNewline===false?'':'\n')));
R('file.ensure_text',async a=>{const old=await A.safeRead(a.path),text=String(a.text??'');if(!text)throw Error('text is required');if(old.includes(text))return{path:A.norm(a.path),changed:false,alreadyPresent:true};return A.writeText(a.path,a.position==='start'?text+old:old+text)});

R('project.find_text_files',async a=>{const deny=/\.(?:png|jpe?g|gif|webp|ico|pdf|zip|gz|7z|rar|woff2?|ttf|otf|mp[34]|wav|exe|dll|bin)$/i;return(await A.walk(a.path||'',99)).filter(x=>x.type==='file'&&!deny.test(x.path)).slice(0,+a.maxFiles||500)});
R('project.read_changed_files',async a=>{const out=[],maxFiles=+a.maxFiles||30,maxChars=+a.maxCharsPerFile||12000;for(const [path,v] of B.state().changes){if(out.length>=maxFiles||v.type==='delete'||v.type==='mkdir')continue;try{const t=await A.readText(path);out.push({path,text:t.slice(0,maxChars),truncated:t.length>maxChars,totalChars:t.length})}catch{}}return out});
R('project.read_by_extension',async a=>{const exts=new Set((a.extensions||[]).map(x=>String(x).toLowerCase().startsWith('.')?String(x).toLowerCase():'.'+String(x).toLowerCase())),out=[],max=+a.maxFiles||30,chars=+a.maxCharsPerFile||10000;for(const f of await A.walk(a.path||'',99)){if(out.length>=max||f.type!=='file'||![...exts].some(e=>f.path.toLowerCase().endsWith(e)))continue;const t=await A.readText(f.path);out.push({path:f.path,text:t.slice(0,chars),truncated:t.length>chars,totalChars:t.length})}return out});
R('project.quick_context',async a=>{const run=A.runTool;if(!run)throw Error('Tool chaining unavailable');const path=a.path||'.';const [summary,entrypoints,config,readmes]=await Promise.all([run('project.summary',{path,maxFiles:a.maxFiles||300}),run('project.find_entrypoints',{path}),run('project.find_config',{path}),run('project.readme_files',{path})]);return{summary,entrypoints:entrypoints.slice(0,30),config:config.slice(0,30),readmes:readmes.slice(0,20),advice:'次は対象ファイルだけread_around/read_linesで読む。'}});
R('project.verify_after_edit',async a=>{if(!A.runTool)throw Error('Tool chaining unavailable');const changed=await A.runTool('project.changed_diagnostics',{maxResults:a.maxResults||200});let json=[];for(const [path,v] of B.state().changes){if(v.type==='delete'||!path.toLowerCase().endsWith('.json'))continue;json.push(await A.runTool('json.file_validate',{path}))}return{ok:changed.ok&&json.every(x=>x.valid),changedDiagnostics:changed,jsonValidation:json}});

R('text.diff_lines',a=>{const x=lines(a.a),y=lines(a.b),out=[],n=Math.max(x.length,y.length),max=+a.maxDiffs||100;for(let i=0;i<n&&out.length<max;i++)if(x[i]!==y[i])out.push({line:i+1,a:x[i]??null,b:y[i]??null});return{same:out.length===0&&x.length===y.length,diffs:out,linesA:x.length,linesB:y.length}});
R('text.context_excerpt',a=>{const t=String(a.text??''),q=String(a.search??'');if(!q)throw Error('search is required');let pos=0,idx=-1,occ=Math.max(1,+a.occurrence||1);for(let i=0;i<occ;i++){idx=t.indexOf(q,pos);if(idx<0)throw Error('Occurrence not found');pos=idx+q.length}const ls=lines(t),line=t.slice(0,idx).split(/\r?\n/).length,b=+a.beforeLines||3,af=+a.afterLines||5,start=Math.max(1,line-b),end=Math.min(ls.length,line+af);return{matchLine:line,start,end,text:ls.slice(start-1,end).join('\n')}});
R('text.replace_preview',a=>{const t=String(a.text??''),s=String(a.search??''),r=String(a.replace??'');if(!s)throw Error('search is required');const count=t.split(s).length-1,out=t.split(s).join(r),max=+a.maxPreview||1200;return{count,changed:count>0,preview:out.slice(0,max),truncated:out.length>max,totalChars:out.length}});
})();
