'use strict';
(() => {
const R=window.RetroArcade;
const txt=(c,t,x,y,s=18,col='#fff',a='left')=>{c.fillStyle=col;c.font=s+'px monospace';c.textAlign=a;c.fillText(t,x,y)};
const rect=(c,x,y,w,h,col)=>{c.fillStyle=col;c.fillRect(x,y,w,h)};
const line=(c,x1,y1,x2,y2,col='#fff',w=2)=>{c.strokeStyle=col;c.lineWidth=w;c.beginPath();c.moveTo(x1,y1);c.lineTo(x2,y2);c.stroke()};
const press=(e,k,interval=.10)=>{if(e.autoTap&&['Space','KeyX','KeyZ'].includes(k))e.autoTap(k,interval);else e.autoKeys.add(k)};

R.register({id:'arkanoid',title:'Arkanoid',year:1986,system:'ARCADE',genre:'Action',color:'#7be1ff',description:'ブロック崩しを発展させ、硬いブロックやカプセルを加えたパドルアクション。',classic:'反射角を調整して面を攻略。硬い壁や落下カプセルで展開が変化。',modern:'レーザー/ワイド/マルチ系ボーナスを整理し、視認性を向上。',controls:'←→ / スペース（レーザー時）',auto:'ボール軌道と落下カプセルを評価し、パドルを最適位置へ移動'},(host,api)=>{
 let paddle,balls,bricks,caps,laser,cool,lives,stage,wide,over;
 function build(){bricks=[];for(let r=0;r<8;r++)for(let x=0;x<12;x++)bricks.push({x:52+x*45,y:48+r*22,w:42,h:18,hp:(r===0&&x%3===0)?2:1,col:['#f65','#fa4','#fe6','#7e7','#4df','#58f','#a6f','#f6c'][r],alive:true})}
 function serve(){balls=[{x:320,y:385,vx:R.rand(-190,190)||170,vy:-235}]}
 function reset(){paddle=270;caps=[];laser=0;cool=0;lives=3;stage=1;wide=0;over=false;build();serve();api.setStatus('全ブロックを壊せ')};reset();
 function applyCap(t){if(t==='W'){wide=10;api.setStatus('EXPAND')}if(t==='L'){laser=10;api.setStatus('LASER')}if(t==='M'&&balls.length){const b=balls[0];balls.push({...b,vx:-b.vx},{...b,vy:-Math.abs(b.vy)});api.setStatus('マルチボール')}}
 return api.canvas({
  reset,
  auto(e,dt,cfg){const falling=caps.filter(x=>x.y<430).sort((a,b)=>b.y-a.y)[0],b=[...balls].sort((a,b)=>b.y-a.y)[0];const target=falling?.y>300?falling.x:b?.x;if(target!=null){if(paddle+55<target-8)press(e,'ArrowRight');else if(paddle+55>target+8)press(e,'ArrowLeft')}if(laser>0)press(e,'Space')},
  update(e,dt){if(over)return;const sp=370;if(e.keys.has('ArrowLeft'))paddle-=sp*dt;if(e.keys.has('ArrowRight'))paddle+=sp*dt;paddle=R.clamp(paddle,8,522);laser=Math.max(0,laser-dt);wide=Math.max(0,wide-dt);cool-=dt;const pw=wide>0?150:110;if(laser>0&&e.keys.has('Space')&&cool<=0){caps.push({x:paddle+20,y:425,shot:true,vy:-430});caps.push({x:paddle+pw-20,y:425,shot:true,vy:-430});cool=.23;api.beep(720,.02)}for(const b of balls){b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.x<7||b.x>633){b.vx*=-1;b.x=R.clamp(b.x,7,633)}if(b.y<7)b.vy=Math.abs(b.vy);if(R.hit({x:b.x-5,y:b.y-5,w:10,h:10},{x:paddle,y:430,w:pw,h:12})&&b.vy>0){b.vy=-Math.abs(b.vy);b.vx+=(b.x-(paddle+pw/2))*3}for(const q of bricks)if(q.alive&&R.hit({x:b.x-5,y:b.y-5,w:10,h:10},q)){q.hp--;b.vy*=-1;if(q.hp<=0){q.alive=false;api.addScore(50);if(Math.random()<.12)caps.push({x:q.x+q.w/2,y:q.y,t:['W','L','M'][Math.floor(Math.random()*3)],vy:95})}else api.addScore(10);break}}for(const cp of caps){cp.y+=cp.vy*dt;if(cp.shot){for(const q of bricks)if(q.alive&&Math.abs((q.x+q.w/2)-cp.x)<q.w/2&&cp.y>q.y&&cp.y<q.y+q.h){q.hp--;cp.dead=true;if(q.hp<=0){q.alive=false;api.addScore(50)}break}}else if(cp.y>415&&cp.y<450&&cp.x>paddle&&cp.x<paddle+pw){applyCap(cp.t);cp.dead=true}}caps=caps.filter(x=>!x.dead&&x.y<490);balls=balls.filter(b=>b.y<490);if(!balls.length){lives--;if(lives<=0){over=true;api.finish('ゲームオーバー');return}serve()}if(bricks.every(q=>!q.alive)){stage++;api.addScore(1000);build();serve()}},
  draw(e){const c=e.ctx;rect(c,0,0,640,480,'#040818');for(const q of bricks)if(q.alive){rect(c,q.x,q.y,q.w,q.h,q.hp>1?'#aaa':q.col);c.strokeStyle='#fff4';c.strokeRect(q.x,q.y,q.w,q.h)}const pw=wide>0?150:110;rect(c,paddle,430,pw,12,'#d9ebff');for(const b of balls){c.fillStyle='#fff';c.beginPath();c.arc(b.x,b.y,5,0,6.28);c.fill()}for(const cp of caps){if(cp.shot)rect(c,cp.x-2,cp.y-8,4,12,'#f55');else{rect(c,cp.x-12,cp.y-7,24,14,'#66e');txt(c,cp.t,cp.x,cp.y+5,12,'#fff','center')}}txt(c,'残機 '+lives,10,470,12,'#acf');txt(c,'ステージ '+stage,630,470,12,'#acf','right')}
 })
});

R.register({id:'lode-runner',title:'Lode Runner',year:1983,system:'COMPUTER',genre:'Platform',color:'#f5b95c',description:'梯子と足場を巡って金塊を集め、穴を掘って敵をかわすアクションパズル。',classic:'全ての金塊を集めると出口が開く。左右へ穴を掘り敵を落として進む。',modern:'掘れる場所の予告、経路表示、オート探索を追加。',controls:'矢印 / Z 左掘り / X 右掘り',auto:'最寄り金塊まで経路探索し、敵が近い時は穴を掘って逃げる'},(host,api)=>{
 const W=20,H=15,S=28,OX=40,OY=28;let grid,p,enemies,gold,exit,moveCd,holes,over;
 const raw=['####################','#   G      H      E#','# #######  H #######','#      H   H       #','### H ###### H #####','# G  H      G H    #','#####H########H#####','#     H        H   #','# H##########  H G #','# H      G     H   #','#######H############','#   G   H          #','# ######H##### H ###','#        H    G H  #','####################'];
 function reset(){grid=raw.map(r=>r.split(''));gold=[];exit=null;for(let y=0;y<H;y++)for(let x=0;x<W;x++){if(grid[y][x]==='G'){gold.push({x,y,taken:false});grid[y][x]=' '}if(grid[y][x]==='E'){exit={x,y};grid[y][x]=' '}}p={x:1,y:1};enemies=[{x:18,y:13},{x:10,y:5}];moveCd=0;holes=[];over=false;api.setStatus('金塊を全部集めろ')};reset();
 const solid=(x,y)=>grid[y]?.[x]==='#'&&!holes.some(h=>h.x===x&&h.y===y);const ladder=(x,y)=>grid[y]?.[x]==='H';const pass=(x,y)=>x>=0&&x<W&&y>=0&&y<H&&!solid(x,y);
 const dirs=[{dx:1,dy:0,k:'ArrowRight'},{dx:-1,dy:0,k:'ArrowLeft'},{dx:0,dy:1,k:'ArrowDown'},{dx:0,dy:-1,k:'ArrowUp'}];
 function bfs(target){const q=[[p.x,p.y,[]]],seen=new Set([p.x+','+p.y]);while(q.length){const[x,y,path]=q.shift();if(x===target.x&&y===target.y)return path[0];for(const d of dirs){const nx=x+d.dx,ny=y+d.dy,id=nx+','+ny;if(seen.has(id)||!pass(nx,ny))continue;if(d.dy<0&&!ladder(x,y)&&!ladder(nx,ny))continue;seen.add(id);q.push([nx,ny,path.concat(d.k)])}}}
 function dig(dx){const x=p.x+dx,y=p.y+1;if(solid(x,y)&&!holes.some(h=>h.x===x&&h.y===y)){holes.push({x,y,t:4});api.beep(190,.04)}}
 return api.canvas({
  reset,
  auto(e,dt,cfg){if(moveCd>0)return;const near=enemies.find(en=>Math.abs(en.x-p.x)+Math.abs(en.y-p.y)<=2);if(near){if(near.x<p.x)press(e,'KeyZ');else press(e,'KeyX')}const target=gold.filter(g=>!g.taken).sort((a,b)=>Math.abs(a.x-p.x)+Math.abs(a.y-p.y)-Math.abs(b.x-p.x)-Math.abs(b.y-p.y))[0]||exit;const k=target&&bfs(target);if(k)press(e,k)},
  keyDown(e,k){if(k==='KeyZ')dig(-1);if(k==='KeyX')dig(1)},
  update(e,dt){if(over)return;moveCd=Math.max(0,moveCd-dt);for(const h of holes)h.t-=dt;holes=holes.filter(h=>h.t>0);if(moveCd<=0){for(const d of dirs)if(e.keys.has(d.k)&&pass(p.x+d.dx,p.y+d.dy)){if(d.dy<0&&!ladder(p.x,p.y)&&!ladder(p.x,p.y-1))continue;p.x+=d.dx;p.y+=d.dy;moveCd=.09;break}}if(!ladder(p.x,p.y)&&!solid(p.x,p.y+1)&&pass(p.x,p.y+1)){p.y++;moveCd=.08}for(const g of gold)if(!g.taken&&g.x===p.x&&g.y===p.y){g.taken=true;api.addScore(100);api.beep(660,.05)}for(const en of enemies){if(Math.random()<dt*5){const opts=dirs.filter(d=>pass(en.x+d.dx,en.y+d.dy));if(opts.length){opts.sort((a,b)=>Math.abs(en.x+a.dx-p.x)+Math.abs(en.y+a.dy-p.y)-Math.abs(en.x+b.dx-p.x)-Math.abs(en.y+b.dy-p.y));const d=opts[0];en.x+=d.dx;en.y+=d.dy}}if(holes.some(h=>h.x===en.x&&h.y===en.y)){en.x=18;en.y=13;api.addScore(75)}if(en.x===p.x&&en.y===p.y){over=true;api.finish('捕まった')}}if(gold.every(g=>g.taken)&&exit&&p.x===exit.x&&p.y===exit.y){api.addScore(1000);api.setStatus('レベルクリア');reset()}},
  draw(e){const c=e.ctx;rect(c,0,0,640,480,'#06101c');for(let y=0;y<H;y++)for(let x=0;x<W;x++){const px=OX+x*S,py=OY+y*S;if(solid(x,y)){rect(c,px,py+18,S,8,'#c66a45');for(let k=0;k<3;k++)rect(c,px+k*9,py+16,7,2,'#f0a070')}if(ladder(x,y)){line(c,px+8,py,px+8,py+S,'#76cbe8',3);line(c,px+20,py,px+20,py+S,'#76cbe8',3);for(let yy=4;yy<S;yy+=8)line(c,px+8,py+yy,px+20,py+yy,'#76cbe8',2)}}for(const h of holes)rect(c,OX+h.x*S,OY+h.y*S+18,S,8,'#06101c');for(const g of gold)if(!g.taken)txt(c,'◆',OX+g.x*S+14,OY+g.y*S+20,16,'#ffd34a','center');if(gold.every(g=>g.taken))txt(c,'出口',OX+exit.x*S+14,OY+exit.y*S+20,10,'#6f6','center');for(const en of enemies)rect(c,OX+en.x*S+7,OY+en.y*S+5,14,20,'#f45');rect(c,OX+p.x*S+7,OY+p.y*S+5,14,20,'#fff');txt(c,'金塊 '+gold.filter(g=>g.taken).length+'/'+gold.length,10,470,12,'#fd6')}
 })
});

R.register({id:'qix',title:'Qix',year:1981,system:'ARCADE',genre:'Puzzle Action',color:'#ff70d7',description:'危険な線状敵を避けながら領域を囲み、画面を少しずつ占領していく。',classic:'外周から線を引き、閉じた領域を塗りつぶす。線を引いている途中は特に危険。',modern:'占有率メーター、危険予測、オート安全領域獲得を追加。',controls:'矢印 / スペース を押しながら線を引く',auto:'敵の位置から遠い方向へ短い安全な矩形を作って占有'},(host,api)=>{
 const W=32,H=22,S=18,OX=32,OY=34;let filled,p,trail,qix,target,over,moveCd;
 function reset(){filled=Array.from({length:H},(_,y)=>Array.from({length:W},(_,x)=>x===0||y===0||x===W-1||y===H-1));p={x:0,y:H-1};trail=[];qix={x:W/2,y:H/2,vx:.11,vy:.08};target=75;over=false;moveCd=0;api.setStatus('75%を占領せよ')};reset();
 const inside=(x,y)=>x>=0&&x<W&&y>=0&&y<H;const trailed=(x,y)=>trail.some(t=>t.x===x&&t.y===y);
 function closeTrail(){if(!trail.length)return;for(const t of trail)filled[t.y][t.x]=true;trail=[];const side=Math.random()<.5?'x':'y';if(side==='x'){const cut=p.x;if(qix.x<cut)for(let y=1;y<H-1;y++)for(let x=cut;x<W-1;x++)filled[y][x]=true;else for(let y=1;y<H-1;y++)for(let x=1;x<=cut;x++)filled[y][x]=true}else{const cut=p.y;if(qix.y<cut)for(let y=cut;y<H-1;y++)for(let x=1;x<W-1;x++)filled[y][x]=true;else for(let y=1;y<=cut;y++)for(let x=1;x<W-1;x++)filled[y][x]=true}const pct=filled.flat().filter(Boolean).length/(W*H);api.setScore(Math.floor(pct*1000));if(pct*100>=target){over=true;api.finish('領域確保')}}
 return api.canvas({
  reset,
  auto(e,dt,cfg){if(moveCd>0)return;const draw=trail.length>0;if(!draw){press(e,'Space');const dx=qix.x>p.x?-1:1,dy=qix.y>p.y?-1:1;press(e,Math.abs(qix.x-p.x)>Math.abs(qix.y-p.y)?(dx>0?'ArrowRight':'ArrowLeft'):(dy>0?'ArrowDown':'ArrowUp'))}else{const last=trail.at(-1);const opts=[['ArrowLeft',-1,0],['ArrowRight',1,0],['ArrowUp',0,-1],['ArrowDown',0,1]].filter(([k,dx,dy])=>inside(last.x+dx,last.y+dy)&&!trailed(last.x+dx,last.y+dy)).sort((a,b)=>{const da=Math.hypot(last.x+a[1]-qix.x,last.y+a[2]-qix.y),db=Math.hypot(last.x+b[1]-qix.x,last.y+b[2]-qix.y);return db-da});if(opts[0])press(e,opts[0][0])}},
  update(e,dt){if(over)return;moveCd=Math.max(0,moveCd-dt);qix.x+=qix.vx*dt*60;qix.y+=qix.vy*dt*60;if(qix.x<1||qix.x>W-2)qix.vx*=-1;if(qix.y<1||qix.y>H-2)qix.vy*=-1;qix.x=R.clamp(qix.x,1,W-2);qix.y=R.clamp(qix.y,1,H-2);if(trail.some(t=>Math.hypot(t.x-qix.x,t.y-qix.y)<.8)){over=true;api.finish('線に接触');return}if(moveCd<=0){for(const[k,dx,dy]of[['ArrowLeft',-1,0],['ArrowRight',1,0],['ArrowUp',0,-1],['ArrowDown',0,1]])if(e.keys.has(k)){const nx=p.x+dx,ny=p.y+dy;if(!inside(nx,ny))continue;const drawing=e.keys.has('Space')||trail.length>0;if(drawing&&!filled[ny][nx])trail.push({x:nx,y:ny});p={x:nx,y:ny};if(trail.length&&filled[ny][nx])closeTrail();moveCd=.055;break}}},
  draw(e){const c=e.ctx;rect(c,0,0,640,480,'#02040a');for(let y=0;y<H;y++)for(let x=0;x<W;x++)if(filled[y][x])rect(c,OX+x*S,OY+y*S,S-1,S-1,'#25345b');for(const t of trail)rect(c,OX+t.x*S+4,OY+t.y*S+4,S-8,S-8,'#f4e');rect(c,OX+p.x*S+4,OY+p.y*S+4,S-8,S-8,'#fff');c.strokeStyle='#ff61d0';c.lineWidth=3;c.beginPath();for(let i=0;i<9;i++){const a=i/8*Math.PI*2,x=OX+(qix.x+Math.cos(a)*1.1)*S,y=OY+(qix.y+Math.sin(a*3)*1.1)*S;i?c.lineTo(x,y):c.moveTo(x,y)}c.stroke();const pct=Math.floor(filled.flat().filter(Boolean).length/(W*H)*100);txt(c,'占領 '+pct+'%',10,470,12,'#9cf')}
 })
});

R.register({id:'lunar-lander',title:'Lunar Lander',year:1979,system:'ARCADE',genre:'Simulation',color:'#e9f1ff',description:'限られた燃料で降下速度と姿勢を制御し、月面の平地へ着陸する。',classic:'重力下で推力と左右姿勢を調整。接地速度と角度が大きいと失敗。',modern:'速度ベクトル、着陸予測、オート着陸補助を追加。',controls:'↑ 主推力 / ←→ 横推力',auto:'高度と降下速度から逆算し、着陸地点へ自動で減速・水平移動'},(host,api)=>{
 let lander,fuel,over,landed,terrain,pad;
 function reset(){terrain=[];for(let x=0;x<=640;x+=20)terrain.push({x,y:390+Math.sin(x*.027)*35+R.rand(-12,12)});pad={x:270,w:100,y:405};for(const t of terrain)if(t.x>=pad.x&&t.x<=pad.x+pad.w)t.y=pad.y;lander={x:160,y:70,vx:22,vy:0,a:0};fuel=900;over=landed=false;api.setStatus('軟着陸: 縦速度38未満')};reset();
 function groundY(x){let a=terrain[0],b=terrain.at(-1);for(let i=1;i<terrain.length;i++)if(terrain[i].x>=x){a=terrain[i-1];b=terrain[i];break}const t=(x-a.x)/(b.x-a.x||1);return a.y+(b.y-a.y)*t}
 return api.canvas({
  reset,
  auto(e,dt,cfg){if(over)return;const tx=pad.x+pad.w/2,dx=tx-lander.x;if(Math.abs(dx)>18){press(e,dx>0?'ArrowRight':'ArrowLeft')}const alt=groundY(lander.x)-lander.y;if((alt<180&&lander.vy>25)||(alt<90&&lander.vy>10)||(lander.vy>48))press(e,'ArrowUp')},
  update(e,dt){if(over)return;lander.vy+=31*dt;if(fuel>0){if(e.keys.has('ArrowUp')){lander.vy-=78*dt;fuel-=32*dt}if(e.keys.has('ArrowLeft')){lander.vx-=35*dt;fuel-=10*dt}if(e.keys.has('ArrowRight')){lander.vx+=35*dt;fuel-=10*dt}}lander.x+=lander.vx*dt;lander.y+=lander.vy*dt;fuel=Math.max(0,fuel);if(lander.x<8){lander.x=8;lander.vx*=-.4}if(lander.x>632){lander.x=632;lander.vx*=-.4}const gy=groundY(lander.x);if(lander.y>=gy-12){lander.y=gy-12;const onPad=lander.x>pad.x&&lander.x<pad.x+pad.w,safe=Math.abs(lander.vy)<38&&Math.abs(lander.vx)<28;if(onPad&&safe){landed=over=true;api.addScore(Math.floor(1000+fuel));api.setStatus('着陸成功')}else{over=true;api.finish('墜落')}}},
  draw(e){const c=e.ctx;rect(c,0,0,640,480,'#000');c.strokeStyle='#ddd';c.beginPath();terrain.forEach((t,i)=>i?c.lineTo(t.x,t.y):c.moveTo(t.x,t.y));c.stroke();line(c,pad.x,pad.y,pad.x+pad.w,pad.y,'#6ff',4);c.save();c.translate(lander.x,lander.y);c.strokeStyle='#fff';c.beginPath();c.moveTo(0,-10);c.lineTo(-9,8);c.lineTo(9,8);c.closePath();c.stroke();if(!over&&fuel>0&&e.keys.has('ArrowUp')){line(c,-4,10,0,20,'#fa5');line(c,4,10,0,20,'#fa5')}c.restore();txt(c,'燃料 '+Math.floor(fuel),10,25,13,'#fff');txt(c,'横速度 '+lander.vx.toFixed(1)+'  縦速度 '+lander.vy.toFixed(1),630,25,13,'#fff','right');if(api.mode==='modern'){line(c,lander.x,lander.y,lander.x+lander.vx*1.2,lander.y+lander.vy*1.2,'#5ff',1);txt(c,'着陸地点',pad.x+pad.w/2,pad.y+20,11,'#6ff','center')}}
 })
});

R.register({id:'balloon-fight',title:'Balloon Fight',year:1985,system:'FAMICOM',genre:'Action',color:'#79c9ff',description:'風船でふわふわ飛び、勢いのある空中移動で敵の風船を割る。',classic:'左右移動＋羽ばたき。慣性が強く、相手より高い位置から体当たりして風船を割る。',modern:'連続羽ばたき補助、危険予告、短いシールドを追加。',controls:'←→ / Z 羽ばたき / X 連続羽ばたき',auto:'敵より少し高い位置を取り、速度を見ながら体当たり'},(host,api)=>{
 let p,enemies,stage,lives,shield,over,flapCd;
 function enemy(i){return{x:120+i*150,y:120+R.rand(0,120),vx:R.rand(-45,45),vy:R.rand(-10,10),balloons:2,phase:R.rand(0,6.28)}}
 function reset(){p={x:320,y:310,vx:0,vy:0,balloons:2};enemies=[enemy(0),enemy(1),enemy(2)];stage=1;lives=3;shield=0;over=false;flapCd=0;api.setStatus('敵の風船を割れ')};reset();
 function flap(){if(p.balloons<=0)return;p.vy-=105;api.beep(420,.02)}
 return api.canvas({
  reset,
  auto(e,dt,cfg){const t=[...enemies].filter(x=>x.balloons>0).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0];if(!t)return;const targetX=t.x,targetY=t.y-35;if(p.x<targetX-12)press(e,'ArrowRight');if(p.x>targetX+12)press(e,'ArrowLeft');if(p.y>targetY||p.vy>60)press(e,'KeyX')},
  keyDown(e,k){if(k==='KeyZ'&&flapCd<=0){flap();flapCd=.09}},
  update(e,dt){if(over)return;flapCd=Math.max(0,flapCd-dt);shield=Math.max(0,shield-dt);const accel=90;if(e.keys.has('ArrowLeft'))p.vx-=accel*dt;if(e.keys.has('ArrowRight'))p.vx+=accel*dt;if(e.keys.has('KeyX')&&flapCd<=0){flap();flapCd=.12}p.vy+=48*dt;p.vx*=Math.pow(.992,dt*60);p.vy*=Math.pow(.997,dt*60);p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.x<10){p.x=10;p.vx=Math.abs(p.vx)*.6}if(p.x>630){p.x=630;p.vx=-Math.abs(p.vx)*.6}if(p.y<25){p.y=25;p.vy=Math.abs(p.vy)*.25}if(p.y>435){p.y=435;p.vy=-80}for(const en of enemies){if(en.balloons<=0)continue;en.phase+=dt;en.vx+=Math.sin(en.phase*1.7)*18*dt;en.vy+=Math.cos(en.phase*1.4)*13*dt;en.vy+=32*dt;if(en.y>410)en.vy-=95;if(en.y<60)en.vy+=35;en.vx*=.995;en.vy*=.993;en.x+=en.vx*dt;en.y+=en.vy*dt;if(en.x<20||en.x>620)en.vx*=-1;if(Math.hypot(en.x-p.x,en.y-p.y)<28){if(p.y<en.y-5){en.balloons--;en.vy+=85;api.addScore(100);api.beep(760,.05);if(api.mode==='modern'&&Math.random()<.12)shield=4}else if(shield<=0){p.balloons--;p.vy+=90;api.beep(100,.1);if(p.balloons<=0){lives--;if(lives<=0){over=true;api.finish('水没')}else{p={x:320,y:310,vx:0,vy:0,balloons:2}}}}}}if(enemies.every(x=>x.balloons<=0)){stage++;api.addScore(500);enemies=[enemy(0),enemy(1),enemy(2),...(stage>2?[enemy(3)]:[])];p={...p,x:320,y:310,vx:0,vy:0,balloons:2}}},
  draw(e){const c=e.ctx;rect(c,0,0,640,480,'#6ebbe8');rect(c,0,440,640,40,'#164f76');for(let x=0;x<640;x+=80){c.fillStyle='#fff9';c.beginPath();c.arc(x+30,70+(x%160),20,0,6.28);c.fill()}drawFighter(c,p,'#fff','#ff5',shield>0);for(const en of enemies)if(en.balloons>0)drawFighter(c,en,'#f56','#e44',false);txt(c,'残機 '+lives,10,470,12,'#fff');txt(c,'ステージ '+stage,630,470,12,'#fff','right')}
 })
 function drawFighter(c,o,body,balloon,shield){rect(c,o.x-8,o.y,16,18,body);for(let i=0;i<o.balloons;i++){c.fillStyle=balloon;c.beginPath();c.arc(o.x+(i?10:-10),o.y-22,9,0,6.28);c.fill();line(c,o.x+(i?10:-10),o.y-13,o.x,o.y,'#333',1)}if(shield){c.strokeStyle='#6ff';c.beginPath();c.arc(o.x,o.y-5,28,0,6.28);c.stroke()}}
});
})();