'use strict';
(() => {
const R=window.RetroArcade;
const txt=(c,t,x,y,s=18,col='#fff',a='left')=>{c.fillStyle=col;c.font=s+'px monospace';c.textAlign=a;c.fillText(t,x,y)};
const rect=(c,x,y,w,h,col)=>{c.fillStyle=col;c.fillRect(x,y,w,h)};
const line=(c,x1,y1,x2,y2,col='#fff',w=2)=>{c.strokeStyle=col;c.lineWidth=w;c.beginPath();c.moveTo(x1,y1);c.lineTo(x2,y2);c.stroke()};
const press=(e,k,interval=.10)=>{if(e.autoTap&&['Space','KeyX','KeyZ'].includes(k))e.autoTap(k,interval);else e.autoKeys.add(k)};
const humanError=(cfg,scale=1)=>R.rand(-1,1)*(cfg.humanize||0)*scale*(1-(cfg.skill||.75)*.5);

R.register({id:'pac-maze',title:'PAC-MAN',year:1980,system:'ARCADE',genre:'Maze',color:'#ffe347',description:'迷路のドットを食べながら追跡者を避けるドットイート迷路ゲーム。',classic:'迷路内のドットを全回収。パワー状態では追跡者へ反撃できる。',modern:'方向予約を広めに受付し、連続回収ボーナスと視認性を補強。',controls:'矢印キー',auto:'近いドットへ向かいながら追跡者との距離を評価'},(host,api)=>{
 const map=['#################','#.......#.......#','#.###.#.#.#.###.#','#o#...#...#...#o#','#.#.###.#.###.#.#','#...............#','###.#.#####.#.###','#...#...#...#...#','#.#####.#.#####.#','#...............#','#.###.#####.###.#','#o..#...#...#..o#','###.###.#.###.###','#...............#','#################'];
 const W=17,H=15,C=28,ox=82,oy=28;let grid,pl,ghosts,power,lives,combo,over,dir,next;
 function reset(){grid=map.map(r=>r.split(''));pl={x:1,y:1};ghosts=[{x:8,y:7,dx:1,dy:0,col:'#f55'},{x:9,y:7,dx:-1,dy:0,col:'#5ff'},{x:8,y:8,dx:0,dy:-1,col:'#f9f'}];power=0;lives=3;combo=0;over=false;dir={x:1,y:0};next=dir;api.setStatus('ドットを全部取れ')};reset();
 const open=(x,y)=>grid[y]?.[x]&&grid[y][x]!=='#';const dirs=[{x:1,y:0,k:'ArrowRight'},{x:-1,y:0,k:'ArrowLeft'},{x:0,y:1,k:'ArrowDown'},{x:0,y:-1,k:'ArrowUp'}];let moveT=0;
 function chooseAuto(cfg){let best=null;for(const d of dirs){const nx=pl.x+d.x,ny=pl.y+d.y;if(!open(nx,ny))continue;let score=0;if(grid[ny][nx]==='.')score+=8;if(grid[ny][nx]==='o')score+=25;let nearest=99;for(const g of ghosts)nearest=Math.min(nearest,Math.abs(g.x-nx)+Math.abs(g.y-ny));score+=(power>0?12-nearest:nearest*3)+R.rand(-3,3)*(cfg.humanize||0);if(!best||score>best.s)best={d,s:score}}return best?.d}
 return api.canvas({
  reset,
  auto(e,dt,cfg){const d=chooseAuto(cfg);if(d)press(e,d.k)},
  update(e,dt){if(over)return;for(const d of dirs)if(e.keys.has(d.k))next=d;moveT+=dt;if(moveT<.115)return;moveT=0;if(open(pl.x+next.x,pl.y+next.y))dir=next;if(open(pl.x+dir.x,pl.y+dir.y)){pl.x+=dir.x;pl.y+=dir.y}const cell=grid[pl.y][pl.x];if(cell==='.'||cell==='o'){grid[pl.y][pl.x]=' ';api.addScore(cell==='o'?50:10);if(cell==='o'){power=6;combo=0;api.beep(700,.08)}}power=Math.max(0,power-.115);for(const g of ghosts){const options=dirs.filter(d=>open(g.x+d.x,g.y+d.y)&&!(d.x===-g.dx&&d.y===-g.dy));let best=options[0];if(options.length){best=options.sort((a,b)=>{const da=Math.abs(pl.x-(g.x+a.x))+Math.abs(pl.y-(g.y+a.y)),db=Math.abs(pl.x-(g.x+b.x))+Math.abs(pl.y-(g.y+b.y));return power>0?db-da:da-db})[0];if(Math.random()<.16)best=options[Math.floor(Math.random()*options.length)];g.dx=best.x;g.dy=best.y;g.x+=g.dx;g.y+=g.dy}if(g.x===pl.x&&g.y===pl.y){if(power>0){g.x=8;g.y=7;combo++;api.addScore(200*combo);api.beep(850,.08)}else{lives--;pl={x:1,y:1};if(lives<=0){over=true;api.finish('ゲームオーバー')}}}}if(!grid.some(r=>r.includes('.')||r.includes('o'))){api.addScore(1000);reset()}},
  draw(e){const c=e.ctx;rect(c,0,0,640,480,'#000');for(let y=0;y<H;y++)for(let x=0;x<W;x++){const v=grid[y][x],px=ox+x*C,py=oy+y*C;if(v==='#'){c.strokeStyle='#173cff';c.strokeRect(px,py,C,C)}else if(v==='.')rect(c,px+13,py+13,3,3,'#ffd9a0');else if(v==='o'){c.fillStyle='#fff';c.beginPath();c.arc(px+14,py+14,5,0,6.28);c.fill()}}c.fillStyle='#ffe347';c.beginPath();c.arc(ox+pl.x*C+14,oy+pl.y*C+14,11,.25,6.0);c.lineTo(ox+pl.x*C+14,oy+pl.y*C+14);c.fill();for(const g of ghosts){rect(c,ox+g.x*C+5,oy+g.y*C+5,18,18,power>0?'#2456ff':g.col);rect(c,ox+g.x*C+8,oy+g.y*C+9,3,4,'#fff');rect(c,ox+g.x*C+16,oy+g.y*C+9,3,4,'#fff')}txt(c,'残機 '+lives,10,472,12,'#ff6');if(power>0)txt(c,'パワー '+power.toFixed(1),630,472,12,'#6ff','right')}
 })
});

R.register({id:'frogger',title:'Frogger',year:1981,system:'ARCADE',genre:'Action',color:'#79db4b',description:'道路と川を横断し、危険な流れを読みながら上端を目指す。',classic:'車道を避け、川では流れる足場へ乗る。複数のゴールを埋める。',modern:'入力バッファ、危険予告、連続ゴールボーナスを追加。',controls:'矢印キー',auto:'次レーンの車・足場位置を見て安全な移動タイミングを選択'},(host,api)=>{
 let p,lanes,goals,lives,moveCd,over;
 function build(){lanes=[];for(let i=0;i<4;i++)lanes.push({y:360-i*38,type:'road',dir:i%2?1:-1,speed:80+i*18,objs:Array.from({length:4},(_,k)=>({x:k*170+R.rand(0,50),w:55}))});for(let i=0;i<4;i++)lanes.push({y:175-i*38,type:'river',dir:i%2?-1:1,speed:55+i*14,objs:Array.from({length:3},(_,k)=>({x:k*220+R.rand(0,40),w:105}))})}
 function reset(){p={x:320,y:430};goals=[false,false,false,false,false];lives=4;moveCd=0;over=false;build();api.setStatus('5つのゴールを目指せ')};reset();
 function laneAt(y){return lanes.find(l=>Math.abs(l.y-y)<8)}
 function safeStep(d){const nx=p.x+d.x*38,ny=p.y+d.y*38,l=laneAt(ny);if(nx<15||nx>625)return -999;if(!l)return 5;if(l.type==='road'){for(const o of l.objs)if(nx>o.x-20&&nx<o.x+o.w+20)return -50;return 15}else{for(const o of l.objs)if(nx>o.x&&nx<o.x+o.w)return 18;return -40}}
 return api.canvas({
  reset,
  auto(e,dt,cfg){if(moveCd>0)return;const opts=[{x:0,y:-1,k:'ArrowUp'},{x:-1,y:0,k:'ArrowLeft'},{x:1,y:0,k:'ArrowRight'},{x:0,y:1,k:'ArrowDown'}].map(d=>({d,s:safeStep(d)+(-d.y)*12+humanError(cfg,12)})).sort((a,b)=>b.s-a.s);if(opts[0].s>-100)press(e,opts[0].d.k)},
  keyDown(e,k){if(moveCd>0)return;const d=k==='ArrowUp'?[0,-1]:k==='ArrowDown'?[0,1]:k==='ArrowLeft'?[-1,0]:k==='ArrowRight'?[1,0]:null;if(d){p.x+=d[0]*38;p.y+=d[1]*38;moveCd=.12;api.beep(350,.02)}},
  update(e,dt){if(over)return;moveCd=Math.max(0,moveCd-dt);for(const l of lanes)for(const o of l.objs){o.x+=l.dir*l.speed*dt;if(o.x>680)o.x=-o.w-30;if(o.x<-o.w-30)o.x=680}const l=laneAt(p.y);if(l){if(l.type==='road'){for(const o of l.objs)if(p.x>o.x-12&&p.x<o.x+o.w+12){lives--;p={x:320,y:430};api.beep(90,.1);break}}else{const o=l.objs.find(o=>p.x>o.x&&p.x<o.x+o.w);if(!o){lives--;p={x:320,y:430};api.beep(90,.1)}else p.x+=l.dir*l.speed*dt}}if(p.x<0||p.x>640){lives--;p={x:320,y:430}}if(p.y<45){const gi=R.clamp(Math.floor((p.x-70)/110),0,4);if(!goals[gi]){goals[gi]=true;api.addScore(200+goals.filter(Boolean).length*50)}p={x:320,y:430};if(goals.every(Boolean)){api.addScore(1000);goals.fill(false)}}if(lives<=0){over=true;api.finish('水没 / 衝突')}},
  draw(e){const c=e.ctx;rect(c,0,0,640,480,'#050505');rect(c,0,210,640,175,'#333');rect(c,0,25,640,175,'#063b72');for(const l of lanes){for(const o of l.objs){if(l.type==='road'){rect(c,o.x,l.y-12,o.w,24,l.dir>0?'#f55':'#fc4')}else{rect(c,o.x,l.y-9,o.w,18,'#8b5a2b');rect(c,o.x+5,l.y-6,o.w-10,4,'#b97838')}}}for(let i=0;i<5;i++){rect(c,45+i*110,28,50,24,goals[i]?'#7f7':'#184');if(goals[i])txt(c,'✓',70+i*110,47,16,'#052','center')}rect(c,p.x-11,p.y-11,22,22,'#77e04d');rect(c,p.x-15,p.y-7,5,5,'#77e04d');rect(c,p.x+10,p.y-7,5,5,'#77e04d');txt(c,'残機 '+lives,10,472,12,'#9f7')}
 })
});

R.register({id:'centipede',title:'Centipede',year:1981,system:'ARCADE',genre:'Shooter',color:'#ff59d4',description:'きのこ地帯を蛇行する多節虫を下から撃ち崩すアーケードシューター。',classic:'節を撃つと分裂し、きのこが増える。下部エリアで自由移動して迎撃。',modern:'短時間スロー/サイドショット風ボーナスとコンボを追加。',controls:'矢印 / スペース',auto:'最も近い節へ追従し、接近時は横へ退避'},(host,api)=>{
 let p,segs,mush,shots,dir,cool,lives,combo,over,power;
 function reset(){p={x:320,y:430};segs=Array.from({length:12},(_,i)=>({x:80+i*28,y:60}));mush=Array.from({length:32},()=>({x:20+Math.floor(R.rand(0,20))*30,y:80+Math.floor(R.rand(0,10))*30,hp:2}));shots=[];dir=1;cool=0;lives=3;combo=0;over=false;power=0;api.setStatus('ムカデを撃て')};reset();
 return api.canvas({
  reset,
  auto(e,dt,cfg){const t=[...segs].sort((a,b)=>b.y-a.y||Math.abs(a.x-p.x)-Math.abs(b.x-p.x))[0];if(!t)return;if(t.y>360&&Math.abs(t.x-p.x)<70)press(e,t.x<p.x?'ArrowRight':'ArrowLeft');else if(p.x<t.x-8)press(e,'ArrowRight');else if(p.x>t.x+8)press(e,'ArrowLeft');press(e,'Space')},
  update(e,dt){if(over)return;const sp=320;if(e.keys.has('ArrowLeft'))p.x-=sp*dt;if(e.keys.has('ArrowRight'))p.x+=sp*dt;if(e.keys.has('ArrowUp'))p.y-=sp*dt;if(e.keys.has('ArrowDown'))p.y+=sp*dt;p.x=R.clamp(p.x,8,632);p.y=R.clamp(p.y,330,462);cool-=dt;power=Math.max(0,power-dt);if(e.keys.has('Space')&&cool<=0){shots.push({x:p.x,y:p.y-10});cool=power>0?.09:.17}for(const s of shots)s.y-=420*dt;shots=shots.filter(s=>s.y>-10);let edge=false;for(const s of segs){s.x+=dir*(75+(12-segs.length)*5)*dt;if(s.x<12||s.x>628)edge=true}if(edge){dir*=-1;for(const s of segs){s.y+=18;s.x=R.clamp(s.x,12,628)}}for(let i=shots.length-1;i>=0;i--){const sh=shots[i];let used=false;for(let j=segs.length-1;j>=0;j--){const s=segs[j];if(Math.hypot(s.x-sh.x,s.y-sh.y)<13){segs.splice(j,1);shots.splice(i,1);mush.push({x:s.x,y:s.y,hp:2});combo++;api.addScore(10+combo*2);if(api.mode==='modern'&&Math.random()<.08)power=5;used=true;break}}if(used)continue;for(let j=mush.length-1;j>=0;j--){const m=mush[j];if(Math.hypot(m.x-sh.x,m.y-sh.y)<12){m.hp--;shots.splice(i,1);if(m.hp<=0){mush.splice(j,1);api.addScore(1)}break}}}for(const s of segs)if(Math.hypot(s.x-p.x,s.y-p.y)<16){lives--;p={x:320,y:430};combo=0;if(lives<=0){over=true;api.finish('ゲームオーバー')}break}if(!segs.length){api.addScore(500);segs=Array.from({length:14},(_,i)=>({x:70+i*26,y:60}));dir=1}},
  draw(e){const c=e.ctx;rect(c,0,0,640,480,'#050016');for(const m of mush){c.fillStyle=m.hp===2?'#6df':'#367';c.beginPath();c.arc(m.x,m.y,8,Math.PI,0);c.fill();rect(c,m.x-2,m.y,4,9,'#6df')}for(const s of segs){c.fillStyle='#ff4bd0';c.beginPath();c.arc(s.x,s.y,9,0,6.28);c.fill()}rect(c,p.x-10,p.y-9,20,18,'#70ff83');for(const s of shots)rect(c,s.x-2,s.y-8,4,10,'#fff');txt(c,'残機 '+lives,10,472,12,'#8ff');if(api.mode==='modern')txt(c,'コンボ '+combo,630,472,12,'#f8d','right')}
 })
});

R.register({id:'galaga',title:'Galaga',year:1981,system:'ARCADE',genre:'Shooter',color:'#60a5ff',description:'編隊から急降下してくる敵を撃つ固定画面シューティング。',classic:'敵は編隊待機と急降下を繰り返し、プレイヤーは左右移動と射撃。',modern:'コンボ、危険予告、短時間ダブルショットを追加。',controls:'←→ / スペース',auto:'敵弾と急降下軌道を避けつつ、列へ合わせて射撃'},(host,api)=>{
 let px,enemies,shots,enemyShots,cool,lives,combo,power,over;
 function reset(){px=305;enemies=[];for(let r=0;r<5;r++)for(let x=0;x<10;x++)enemies.push({homeX:95+x*48,homeY:55+r*32,x:95+x*48,y:55+r*32,alive:true,phase:R.rand(0,6.28),dive:false,t:0});shots=[];enemyShots=[];cool=0;lives=3;combo=0;power=0;over=false;api.setStatus('編隊を撃破せよ')};reset();
 return api.canvas({
  reset,
  auto(e,dt,cfg){const danger=enemyShots.filter(b=>b.y>320&&Math.abs(b.x-px)<55).sort((a,b)=>b.y-a.y)[0];if(danger)press(e,danger.x<px?'ArrowRight':'ArrowLeft');else{const t=enemies.filter(x=>x.alive).sort((a,b)=>Math.abs(a.x-px)-Math.abs(b.x-px))[0];if(t){if(px<t.x-12)press(e,'ArrowRight');else if(px>t.x+12)press(e,'ArrowLeft')}}press(e,'Space')},
  update(e,dt){if(over)return;const sp=330;if(e.keys.has('ArrowLeft'))px-=sp*dt;if(e.keys.has('ArrowRight'))px+=sp*dt;px=R.clamp(px,8,602);cool-=dt;power=Math.max(0,power-dt);if(e.keys.has('Space')&&cool<=0){shots.push({x:px+15,y:420});if(power>0)shots.push({x:px+5,y:420});cool=power>0?.11:.2;api.beep(540,.02)}for(const s of shots)s.y-=450*dt;shots=shots.filter(s=>s.y>-10);for(const b of enemyShots)b.y+=190*dt;enemyShots=enemyShots.filter(b=>b.y<490);for(const en of enemies)if(en.alive){en.phase+=dt;en.t+=dt;if(!en.dive&&Math.random()<dt*.08){en.dive=true;en.t=0}if(en.dive){en.y+=115*dt;en.x+=Math.sin(en.t*3+en.phase)*85*dt;if(en.y>390){en.dive=false;en.x=en.homeX;en.y=en.homeY}}else{en.x=en.homeX+Math.sin(en.phase*1.6)*8;en.y=en.homeY+Math.cos(en.phase*1.3)*3}if(Math.random()<dt*.08)enemyShots.push({x:en.x,y:en.y+12})}for(let i=shots.length-1;i>=0;i--){for(const en of enemies)if(en.alive&&Math.abs(en.x-shots[i].x)<14&&Math.abs(en.y-shots[i].y)<12){en.alive=false;shots.splice(i,1);combo++;api.addScore(en.dive?80+combo*3:30+combo);if(api.mode==='modern'&&Math.random()<.07)power=5;api.beep(720,.035);break}}for(const b of enemyShots)if(Math.abs(b.x-(px+15))<14&&Math.abs(b.y-430)<12){b.y=999;lives--;combo=0;if(lives<=0){over=true;api.finish('機体破壊')}}if(enemies.every(x=>!x.alive)){api.addScore(800);reset()}},
  draw(e){const c=e.ctx;rect(c,0,0,640,480,'#000015');for(const en of enemies)if(en.alive){rect(c,en.x-10,en.y-7,20,14,en.dive?'#ffcf4c':'#66a8ff');rect(c,en.x-15,en.y-3,30,5,'#d65cff')}rect(c,px,427,30,14,'#77eaff');rect(c,px+12,417,6,10,'#fff');for(const s of shots)rect(c,s.x-2,s.y-7,4,10,'#fff');for(const b of enemyShots)rect(c,b.x-2,b.y,4,9,'#f66');txt(c,'残機 '+lives,10,472,12,'#8cf');if(api.mode==='modern')txt(c,'コンボ '+combo,630,472,12,'#fc7','right')}
 })
});

R.register({id:'donkey-kong',title:'Donkey Kong',year:1981,system:'ARCADE',genre:'Platform',color:'#ff624f',description:'傾斜した足場と梯子を登り、転がる障害を跳び越えて上を目指す。',classic:'左右移動、梯子の昇降、ジャンプで樽を回避しながら最上段へ。',modern:'ジャンプ猶予、危険予告、チェックポイント的な復帰補助を追加。',controls:'←→ / ↑↓ 梯子 / スペース ジャンプ',auto:'上方向の梯子を探し、近い樽を自動ジャンプ'},(host,api)=>{
 let p,barrels,spawn,lives,vy,onGround,over,stage;
 const plats=[{y:430,x1:40,x2:600,tilt:-.04},{y:350,x1:40,x2:600,tilt:.04},{y:270,x1:40,x2:600,tilt:-.04},{y:190,x1:40,x2:600,tilt:.04},{y:110,x1:110,x2:530,tilt:0}];
 const ladders=[{x:530,y1:350,y2:430},{x:115,y1:270,y2:350},{x:520,y1:190,y2:270},{x:150,y1:110,y2:190}];
 function reset(){p={x:80,y:410,level:0};barrels=[];spawn=1;lives=3;vy=0;onGround=true;over=false;stage=1;api.setStatus('最上段を目指せ')};reset();
 function nearLadder(){return ladders.find(l=>Math.abs(l.x-p.x)<18&&p.y>=l.y2-25&&p.y<=l.y1+25)}
 return api.canvas({
  reset,
  auto(e,dt,cfg){const danger=[...barrels].sort((a,b)=>Math.abs(a.x-p.x)-Math.abs(b.x-p.x))[0];if(danger&&Math.abs(danger.x-p.x)<70&&Math.abs(danger.y-p.y)<28)press(e,'Space');const target=ladders[p.level];if(target){if(Math.abs(p.x-target.x)>12)press(e,p.x<target.x?'ArrowRight':'ArrowLeft');else press(e,'ArrowUp')}},
  keyDown(e,k){if(k==='Space'&&onGround){vy=-250;onGround=false;api.beep(420,.025)}},
  update(e,dt){if(over)return;const sp=170;if(e.keys.has('ArrowLeft'))p.x-=sp*dt;if(e.keys.has('ArrowRight'))p.x+=sp*dt;p.x=R.clamp(p.x,42,598);const lad=nearLadder();if(lad&&(e.keys.has('ArrowUp')||e.keys.has('ArrowDown'))){p.y+=(e.keys.has('ArrowUp')?-150:150)*dt;vy=0;onGround=false;if(p.y<lad.y1+8){p.level=Math.min(4,p.level+1);p.y=plats[p.level].y-20;onGround=true;api.addScore(100)}else if(p.y>lad.y2-8){p.level=Math.max(0,p.level-1);p.y=plats[p.level].y-20;onGround=true}}else{vy+=620*dt;p.y+=vy*dt;const fy=plats[p.level].y+(p.x-320)*plats[p.level].tilt-20;if(p.y>=fy){p.y=fy;vy=0;onGround=true}}spawn-=dt;if(spawn<=0&&p.level<4){barrels.push({x:510,y:plats[3].y-9,level:3,dir:-1});spawn=R.rand(1.1,2.1)}for(const b of barrels){b.x+=b.dir*(95+stage*7)*dt;b.y=plats[b.level].y+(b.x-320)*plats[b.level].tilt-9;if((b.dir<0&&b.x<45)||(b.dir>0&&b.x>595)){if(b.level>0){b.level--;b.dir*=-1;b.x=R.clamp(b.x,45,595)}else b.dead=true}if(Math.abs(b.x-p.x)<18&&Math.abs(b.y-p.y)<18){lives--;p={x:80,y:410,level:0};vy=0;onGround=true;b.dead=true;api.beep(90,.12);if(lives<=0){over=true;api.finish('ゲームオーバー')}}}barrels=barrels.filter(b=>!b.dead);if(p.level>=4&&p.x>270&&p.x<370){stage++;api.addScore(1000);p={x:80,y:410,level:0};barrels=[];spawn=1}},
  draw(e){const c=e.ctx;rect(c,0,0,640,480,'#080016');for(const pl of plats){c.strokeStyle='#e54a61';c.lineWidth=8;c.beginPath();c.moveTo(pl.x1,pl.y+(pl.x1-320)*pl.tilt);c.lineTo(pl.x2,pl.y+(pl.x2-320)*pl.tilt);c.stroke()}for(const l of ladders){line(c,l.x-9,l.y1,l.x-9,l.y2,'#6dd',4);line(c,l.x+9,l.y1,l.x+9,l.y2,'#6dd',4);for(let y=l.y1;y<l.y2;y+=12)line(c,l.x-9,y,l.x+9,y,'#6dd',2)}rect(c,490,75,48,35,'#b44');txt(c,'ボス',514,98,11,'#fff','center');rect(c,p.x-9,p.y-17,18,17,'#6af');rect(c,p.x-7,p.y-26,14,10,'#ffd3a6');for(const b of barrels){c.strokeStyle='#e78a3c';c.lineWidth=4;c.beginPath();c.arc(b.x,b.y,11,0,6.28);c.stroke()}txt(c,'残機 '+lives,10,472,12,'#fff');txt(c,'ステージ '+stage,630,472,12,'#fff','right')}
 })
});
})();