'use strict';
(() => {
const Q={};
const set=(ids,kind,cfg={})=>{for(const id of ids)Q[id]={...(Q[id]||{}),kind,cfg:{...(Q[id]?.cfg||{}),...cfg}}};
set(['sea-wolf','duck-hunt','operation-wolf'],'galleryShooter',{time:55,shots:45});
set(['space-harrier','after-burner','star-fox','panzer-dragoon','star-fox-64'],'railShooter',{enemySpeed:.32,tough:true});
set(['contra','mega-man','mega-man-2','mega-man-3','shinobi','bionic-commando','metal-slug'],'runGun',{levelW:3100,fireDelay:.14});
set(['double-dragon','golden-axe','final-fight','streets-rage','kung-fu-master'],'beatEmUp',{tough:true,enemySpeed:82});
set(['mario-bros','burgertime','bubble-bobble','bomb-jack'],'fixedPlatform',{enemies:7,items:9});
set(['track-field'],'trackField',{time:40});
set(['tapper'],'serviceGame',{time:65});
set(['robotron-2084','commando','ikari-warriors'],'arena',{enemySpeed:92,enemyScore:35});
set(['galaxian'],'fixedShooter',{dive:true,fireRate:.06,enemyScore:40});
set(['tempest'],'fixedShooter',{cols:12,rows:3,fireRate:.08,enemyScore:50});
set(['defender','scramble','gradius','fantasy-zone','r-type','darius'],'scrollShooter',{enemySpeed:130,fireRate:.1});
set(['xevious','1942','1943','raiden'],'scrollShooter',{vertical:true,enemySpeed:138,fireRate:.1});
set(['wing-commander'],'scrollShooter',{enemySpeed:150,fireRate:.12,tough:true});
set(['joust'],'fixedPlatform',{enemies:6,items:6,jump:360,enemySpeed:65});
set(['donkey-kong-jr','ice-climber'],'fixedPlatform',{enemies:6,items:8,jump:350});
set(['ghosts-goblins','castlevania','castlevania-3','prince-persia','another-world','tomb-raider'],'platform',{jump:320,gravity:800,enemies:13});
set(['super-mario-bros','super-mario-world','sonic','donkey-kong-country','rayman','yoshis-island','crash-bandicoot','super-mario-64'],'platform',{jump:365,gravity:760,enemies:12});
set(['metroid','super-metroid','castlevania-sotn'],'runGun',{levelW:3300,fireDelay:.17,tough:true});
set(['metal-gear','metal-gear-solid','thief-dark-project'],'stealth',{guards:7});
set(['wolfenstein-3d','doom','doom-2','system-shock','descent','quake','duke-nukem-3d','goldeneye-007','half-life','counter-strike'],'raycast',{tough:true});
set(['street-fighter-2','mortal-kombat','virtua-fighter','tekken','killer-instinct','tekken-2','tekken-3','super-smash-bros'],'fighter',{aiAggro:2.8,speed:185});
set(['karate-champ','yie-ar-kung-fu','punch-out','karateka'],'fighter',{aiAggro:2.25,speed:165});
set(['dragons-lair','dance-dance-revolution'],'rhythm',{speed:235});
set(['canyon-bomber','worms'],'physics',{shots:11});
set(['dr-mario'],'puzzle',{cols:8,rows:16});
set(['simcity','civilization','civilization-2'],'strategy',{pressure:.55,goal:90});
set(['dune-2','warcraft','warcraft-2','command-conquer','age-of-empires','starcraft'],'strategy',{pressure:1.05,goal:95});
set(['xcom-ufo','heroes-might-magic'],'strategy',{pressure:.85,goal:88});
set(['theme-park','rollercoaster-tycoon'],'management',{days:38});
set(['zelda-1986','secret-mana','ocarina-time'],'adventure',{items:8,enemies:8,tough:true});
set(['dragon-quest','dragon-quest-3','final-fantasy','phantasy-star-2','ultima-6','earthbound','chrono-trigger','pokemon-red-green','diablo','final-fantasy-7','fallout'],'adventure',{items:8,enemies:9,tough:true});
set(['myst','day-tentacle','kings-quest'],'adventure',{items:9,enemies:1});
set(['resident-evil','alone-dark'],'adventure',{items:7,enemies:6,tough:true});
set(['ms-pac-man','mappy','berzerk'],'maze',{smart:.8,items:42});
set(['qbert','dig-dug'],'maze',{smart:.68,items:34});
set(['combat','battlezone'],'tank',{tough:true});
set(['sensible-soccer','fifa-international'],'sports',{time:75,ballSpeed:350,aiSpeed:145});
set(['atari-football','tecmo-bowl'],'sports',{time:70,ballSpeed:325,aiSpeed:135});
set(['atari-basketball'],'sports',{time:60,ballSpeed:335,aiSpeed:130});
set(['night-driver','monaco-gp','pole-position','out-run','f-zero','ridge-racer','gran-turismo'],'racer',{lanes:5,maxSpeed:315,lapLength:6200});
set(['sprint-2','rc-pro-am','micro-machines'],'racer',{lanes:4,maxSpeed:250,lapLength:3900});
set(['super-mario-kart','mario-kart-64'],'racer',{lanes:5,maxSpeed:295,lapLength:5600});
set(['spy-hunter','road-fighter','crazy-taxi'],'racer',{lanes:5,maxSpeed:300,lapLength:5600});
set(['hang-on'],'racer',{lanes:4,maxSpeed:300,lapLength:5800});
set(['paperboy'],'racer',{lanes:4,maxSpeed:220,lapLength:4300});
set(['twisted-metal'],'racer',{lanes:5,maxSpeed:280,lapLength:5200});
set(['marble-madness','tony-hawk-pro-skater'],'racer',{lanes:5,maxSpeed:235,lapLength:4300});
set(['pilotwings'],'racer',{lanes:5,maxSpeed:220,lapLength:4200});

set(['atari-basketball'],'basketball',{});
set(['atari-football','tecmo-bowl'],'gridiron',{});
set(['sprint-2','rc-pro-am','micro-machines'],'topRace',{});
set(['marble-madness'],'rolling',{});
set(['tony-hawk-pro-skater'],'skate',{});
set(['dragons-lair'],'qte',{});
set(['myst','day-tentacle','kings-quest'],'pointClick',{});
set(['dragon-quest','dragon-quest-3','final-fantasy','phantasy-star-2','ultima-6','earthbound','chrono-trigger','pokemon-red-green','diablo','final-fantasy-7','fallout'],'dungeonRPG',{items:7,enemies:8});
set(['lemmings'],'lemmings',{});
set(['pilotwings'],'flightChallenge',{});


set(['simcity'],'cityBuilder',{});
set(['dune-2','warcraft','warcraft-2','command-conquer','age-of-empires','starcraft'],'rts',{});
set(['xcom-ufo','heroes-might-magic'],'tactics',{});
set(['theme-park','rollercoaster-tycoon'],'park',{});
set(['twisted-metal'],'vehicleCombat',{});
set(['crazy-taxi'],'taxi',{});
set(['qbert'],'qbert',{});
set(['dig-dug'],'digger',{});

window.RetroQuality=Q;
})();