// ---------- data + chart ----------
function parseData(text){
  const labeled=parseLabeledData(text);if(labeled)return labeled;
  const nums=numbersFrom(text);return nums.map((v,i)=>({label:String(i+1),value:v}));
}
function quantile(sorted,q){if(!sorted.length)return NaN;const pos=(sorted.length-1)*q,base=Math.floor(pos),rest=pos-base;return sorted[base+1]!==undefined?sorted[base]+rest*(sorted[base+1]-sorted[base]):sorted[base]}
function dataStats(rows){const a=rows.map(x=>x.value),s=[...a].sort((x,y)=>x-y),sum=a.reduce((x,y)=>x+y,0),mean=sum/a.length,variance=a.reduce((z,x)=>z+(x-mean)**2,0)/a.length;const counts=new Map;for(const x of a)counts.set(x,(counts.get(x)||0)+1);const mc=Math.max(...counts.values()),modes=mc>1?[...counts].filter(x=>x[1]===mc).map(x=>x[0]):[];return {count:a.length,sum,mean,median:quantile(s,.5),min:s[0],max:s.at(-1),range:s.at(-1)-s[0],q1:quantile(s,.25),q3:quantile(s,.75),variance,std:Math.sqrt(variance),modes}}
function runData(){const box=$('#dataResult'),statsBox=$('#stats');try{let rows=parseData($('#dataInput').value);if(!rows.length)throw Error('数値を入力してください。');if(rows.length>200)throw Error('グラフの見やすさのため、1回200件までにしてください。');const sort=$('#sortData').value;if(sort==='asc')rows.sort((a,b)=>a.value-b.value);if(sort==='desc')rows.sort((a,b)=>b.value-a.value);const st=dataStats(rows);statsBox.innerHTML=[['件数',st.count],['合計',fmt(st.sum)],['平均',fmt(st.mean)],['中央値',fmt(st.median)],['最小',fmt(st.min)],['最大',fmt(st.max)],['範囲',fmt(st.range)],['標準偏差',fmt(st.std)]].map(([l,v])=>`<div class="stat"><span>${l}</span><strong>${v}</strong></div>`).join('');box.className='result success';box.innerHTML=`第1四分位数：${fmt(st.q1)}　/　第3四分位数：${fmt(st.q3)}　/　分散：${fmt(st.variance)}${st.modes.length?`<br>最頻値：${st.modes.map(fmt).join('、')}`:''}`;drawChart(rows,$('#chartType').value);addHistory('データ分析',`${rows.length}件`,`平均 ${fmt(st.mean)}`)}catch(e){statsBox.innerHTML='';box.className='result error';box.textContent=e.message;clearCanvas()}}
$('#dataRun').addEventListener('click',runData);$('#chartType').addEventListener('change',()=>{if($('#dataInput').value.trim())runData()});$('#sortData').addEventListener('change',()=>{if($('#dataInput').value.trim())runData()});
function clearCanvas(){const c=$('#chart'),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height)}
function drawChart(rows,type){const c=$('#chart'),ctx=c.getContext('2d'),W=c.width,H=c.height;ctx.clearRect(0,0,W,H);ctx.fillStyle='#fff';ctx.fillRect(0,0,W,H);if(type==='pie'){drawPie(ctx,rows,W,H);return}drawAxesChart(ctx,rows,W,H,type)}
function drawAxesChart(ctx,rows,W,H,type){const pad={l:70,r:25,t:30,b:80},pw=W-pad.l-pad.r,ph=H-pad.t-pad.b,vals=rows.map(x=>x.value),min=Math.min(0,...vals),max=Math.max(0,...vals),span=max-min||1;ctx.strokeStyle='#dce4f0';ctx.lineWidth=1;ctx.fillStyle='#62708a';ctx.font='14px sans-serif';for(let i=0;i<=5;i++){const y=pad.t+ph*i/5,val=max-span*i/5;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(W-pad.r,y);ctx.stroke();ctx.fillText(fmt(val,4),5,y+4)}const xStep=pw/Math.max(rows.length,1),yOf=v=>pad.t+(max-v)/span*ph;ctx.strokeStyle='#3567d6';ctx.fillStyle='#5c84df';ctx.lineWidth=3;if(type==='line'){ctx.beginPath();rows.forEach((r,i)=>{const x=pad.l+xStep*(i+.5),y=yOf(r.value);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();rows.forEach((r,i)=>{const x=pad.l+xStep*(i+.5),y=yOf(r.value);ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fill()})}else{const bw=Math.max(3,xStep*.68),zero=yOf(0);rows.forEach((r,i)=>{const x=pad.l+xStep*(i+.5)-bw/2,y=yOf(r.value);ctx.fillRect(x,Math.min(y,zero),bw,Math.abs(zero-y)||1)})}ctx.fillStyle='#475569';ctx.font='12px sans-serif';const every=Math.max(1,Math.ceil(rows.length/14));rows.forEach((r,i)=>{if(i%every)return;const x=pad.l+xStep*(i+.5);ctx.save();ctx.translate(x,H-pad.b+15);ctx.rotate(-.45);ctx.fillText(String(r.label).slice(0,16),0,0);ctx.restore()})}
function drawPie(ctx,rows,W,H){const positives=rows.filter(r=>r.value>0),sum=positives.reduce((s,r)=>s+r.value,0);if(!sum){ctx.fillStyle='#62708a';ctx.font='18px sans-serif';ctx.fillText('円グラフは正の値が必要です。',30,50);return}const cx=W*.38,cy=H*.48,rad=Math.min(H*.36,W*.24);let start=-Math.PI/2;const hues=[215,165,35,285,5,195,115,255,55,325];positives.forEach((r,i)=>{const ang=r.value/sum*Math.PI*2;ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,rad,start,start+ang);ctx.closePath();ctx.fillStyle=`hsl(${hues[i%hues.length]} 65% 62%)`;ctx.fill();start+=ang});ctx.font='13px sans-serif';positives.slice(0,12).forEach((r,i)=>{const y=45+i*27;ctx.fillStyle=`hsl(${hues[i%hues.length]} 65% 55%)`;ctx.fillRect(W*.68,y-11,13,13);ctx.fillStyle='#334155';ctx.fillText(`${String(r.label).slice(0,15)}  ${fmt(r.value/sum*100,2)}%`,W*.68+20,y)})}

$('#clearHistory').addEventListener('click',()=>{localStorage.removeItem(HISTORY_KEY);renderHistory()});
renderHistory();
