// ---------- geometry ----------
const SHAPES={
  rectangle:{name:'長方形',svg:'<svg viewBox="0 0 240 120"><rect x="35" y="20" width="170" height="80" rx="2" fill="#edf3ff" stroke="#3567d6" stroke-width="3"/></svg>',targets:{area:{name:'面積',fields:[['width','横'],['height','縦']],calc:v=>v.width*v.height,formula:v=>`${v.width} × ${v.height}`},perimeter:{name:'周の長さ',fields:[['width','横'],['height','縦']],calc:v=>2*(v.width+v.height),formula:v=>`2 × (${v.width} + ${v.height})`},width:{name:'横（面積から逆算）',fields:[['area','面積'],['height','縦']],calc:v=>v.area/v.height,formula:v=>`${v.area} ÷ ${v.height}`},height:{name:'縦（面積から逆算）',fields:[['area','面積'],['width','横']],calc:v=>v.area/v.width,formula:v=>`${v.area} ÷ ${v.width}`}}},
  square:{name:'正方形',svg:'<svg viewBox="0 0 240 120"><rect x="70" y="15" width="90" height="90" fill="#edf3ff" stroke="#3567d6" stroke-width="3"/></svg>',targets:{area:{name:'面積',fields:[['side','一辺']],calc:v=>v.side**2,formula:v=>`${v.side}²`},perimeter:{name:'周の長さ',fields:[['side','一辺']],calc:v=>4*v.side,formula:v=>`4 × ${v.side}`},sideArea:{name:'一辺（面積から）',fields:[['area','面積']],calc:v=>Math.sqrt(v.area),formula:v=>`√${v.area}`}}},
  triangle:{name:'三角形',svg:'<svg viewBox="0 0 240 120"><polygon points="120,12 35,105 205,105" fill="#edf3ff" stroke="#3567d6" stroke-width="3"/></svg>',targets:{area:{name:'面積',fields:[['base','底辺'],['height','高さ']],calc:v=>v.base*v.height/2,formula:v=>`${v.base} × ${v.height} ÷ 2`},base:{name:'底辺（面積から）',fields:[['area','面積'],['height','高さ']],calc:v=>2*v.area/v.height,formula:v=>`${v.area} × 2 ÷ ${v.height}`},height:{name:'高さ（面積から）',fields:[['area','面積'],['base','底辺']],calc:v=>2*v.area/v.base,formula:v=>`${v.area} × 2 ÷ ${v.base}`}}},
  circle:{name:'円',svg:'<svg viewBox="0 0 240 120"><circle cx="120" cy="60" r="48" fill="#edf3ff" stroke="#3567d6" stroke-width="3"/><line x1="120" y1="60" x2="168" y2="60" stroke="#3567d6" stroke-width="2"/></svg>',targets:{area:{name:'面積',fields:[['radius','半径']],calc:v=>Math.PI*v.radius**2,formula:v=>`π × ${v.radius}²`},circ:{name:'円周',fields:[['radius','半径']],calc:v=>2*Math.PI*v.radius,formula:v=>`2 × π × ${v.radius}`},diam:{name:'直径',fields:[['radius','半径']],calc:v=>2*v.radius,formula:v=>`2 × ${v.radius}`},radiusArea:{name:'半径（面積から）',fields:[['area','面積']],calc:v=>Math.sqrt(v.area/Math.PI),formula:v=>`√(${v.area} ÷ π)`},radiusCirc:{name:'半径（円周から）',fields:[['circ','円周']],calc:v=>v.circ/(2*Math.PI),formula:v=>`${v.circ} ÷ (2π)`}}},
  parallelogram:{name:'平行四辺形',svg:'<svg viewBox="0 0 240 120"><polygon points="70,20 205,20 170,100 35,100" fill="#edf3ff" stroke="#3567d6" stroke-width="3"/></svg>',targets:{area:{name:'面積',fields:[['base','底辺'],['height','高さ']],calc:v=>v.base*v.height,formula:v=>`${v.base} × ${v.height}`},base:{name:'底辺（面積から）',fields:[['area','面積'],['height','高さ']],calc:v=>v.area/v.height,formula:v=>`${v.area} ÷ ${v.height}`},height:{name:'高さ（面積から）',fields:[['area','面積'],['base','底辺']],calc:v=>v.area/v.base,formula:v=>`${v.area} ÷ ${v.base}`}}},
  trapezoid:{name:'台形',svg:'<svg viewBox="0 0 240 120"><polygon points="80,20 160,20 205,100 35,100" fill="#edf3ff" stroke="#3567d6" stroke-width="3"/></svg>',targets:{area:{name:'面積',fields:[['top','上底'],['bottom','下底'],['height','高さ']],calc:v=>(v.top+v.bottom)*v.height/2,formula:v=>`(${v.top} + ${v.bottom}) × ${v.height} ÷ 2`},height:{name:'高さ（面積から）',fields:[['area','面積'],['top','上底'],['bottom','下底']],calc:v=>2*v.area/(v.top+v.bottom),formula:v=>`${v.area} × 2 ÷ (${v.top} + ${v.bottom})`}}},
  cube:{name:'立方体',svg:'<svg viewBox="0 0 240 120"><path d="M70 35l35-20 70 0 0 65-35 20-70 0z M70 35h70v65 M140 35l35-20" fill="#edf3ff" stroke="#3567d6" stroke-width="3"/></svg>',targets:{volume:{name:'体積',fields:[['side','一辺']],calc:v=>v.side**3,formula:v=>`${v.side}³`},surface:{name:'表面積',fields:[['side','一辺']],calc:v=>6*v.side**2,formula:v=>`6 × ${v.side}²`},side:{name:'一辺（体積から）',fields:[['volume','体積']],calc:v=>Math.cbrt(v.volume),formula:v=>`∛${v.volume}`}}},
  cuboid:{name:'直方体',svg:'<svg viewBox="0 0 240 120"><path d="M55 40l35-20h95v65l-35 20H55z M55 40h95v65 M150 40l35-20" fill="#edf3ff" stroke="#3567d6" stroke-width="3"/></svg>',targets:{volume:{name:'体積',fields:[['width','横'],['depth','奥行'],['height','高さ']],calc:v=>v.width*v.depth*v.height,formula:v=>`${v.width} × ${v.depth} × ${v.height}`},surface:{name:'表面積',fields:[['width','横'],['depth','奥行'],['height','高さ']],calc:v=>2*(v.width*v.depth+v.depth*v.height+v.height*v.width),formula:v=>`2 × (横×奥行 + 奥行×高さ + 高さ×横)`}}},
  cylinder:{name:'円柱',svg:'<svg viewBox="0 0 240 120"><ellipse cx="120" cy="25" rx="55" ry="15" fill="#edf3ff" stroke="#3567d6" stroke-width="3"/><path d="M65 25v65c0 20 110 20 110 0V25" fill="#edf3ff" stroke="#3567d6" stroke-width="3"/><ellipse cx="120" cy="90" rx="55" ry="15" fill="none" stroke="#3567d6" stroke-width="3"/></svg>',targets:{volume:{name:'体積',fields:[['radius','半径'],['height','高さ']],calc:v=>Math.PI*v.radius**2*v.height,formula:v=>`π × ${v.radius}² × ${v.height}`},surface:{name:'表面積',fields:[['radius','半径'],['height','高さ']],calc:v=>2*Math.PI*v.radius*(v.radius+v.height),formula:v=>`2π × ${v.radius} × (${v.radius} + ${v.height})`},height:{name:'高さ（体積から）',fields:[['volume','体積'],['radius','半径']],calc:v=>v.volume/(Math.PI*v.radius**2),formula:v=>`${v.volume} ÷ (π × ${v.radius}²)`}}},
  sphere:{name:'球',svg:'<svg viewBox="0 0 240 120"><circle cx="120" cy="60" r="48" fill="#edf3ff" stroke="#3567d6" stroke-width="3"/><ellipse cx="120" cy="60" rx="48" ry="15" fill="none" stroke="#9bb3e8" stroke-width="2"/></svg>',targets:{volume:{name:'体積',fields:[['radius','半径']],calc:v=>4*Math.PI*v.radius**3/3,formula:v=>`4 ÷ 3 × π × ${v.radius}³`},surface:{name:'表面積',fields:[['radius','半径']],calc:v=>4*Math.PI*v.radius**2,formula:v=>`4 × π × ${v.radius}²`}}}
};
function initGeometry(){const s=$('#shape');s.innerHTML=Object.entries(SHAPES).map(([k,v])=>`<option value="${k}">${v.name}</option>`).join('');renderGeoTargets()}
function renderGeoTargets(){const sh=SHAPES[$('#shape').value],t=$('#geoTarget');t.innerHTML=Object.entries(sh.targets).map(([k,v])=>`<option value="${k}">${v.name}</option>`).join('');$('#shapePreview').innerHTML=sh.svg;renderGeoFields()}
function renderGeoFields(){const sh=SHAPES[$('#shape').value],tg=sh.targets[$('#geoTarget').value];$('#geoFields').innerHTML=tg.fields.map(([id,name])=>`<div class="field"><label>${name}</label><input id="geo_${id}" class="input" type="number" step="any" min="0" placeholder="数値"></div>`).join('')}
$('#shape').addEventListener('change',renderGeoTargets);$('#geoTarget').addEventListener('change',renderGeoFields);
function runGeo(){const box=$('#geoResult');try{const sh=SHAPES[$('#shape').value],tg=sh.targets[$('#geoTarget').value],v={};for(const [id,name] of tg.fields){v[id]=Number($('#geo_'+id).value);if(!Number.isFinite(v[id])||v[id]<0)throw Error(`${name}を0以上の数値で入力してください。`)}const ans=tg.calc(v);if(!Number.isFinite(ans))throw Error('この値では計算できません。');box.className='result success';box.innerHTML=`<div class="big-answer">${tg.name}：${fmt(ans)}</div><div class="steps">${esc(tg.formula(v))} = ${fmt(ans)}<br><span class="muted">単位を付ける場合、面積は²、体積は³になります。</span></div>`;addHistory('図形',`${sh.name}/${tg.name}`,fmt(ans))}catch(e){box.className='result error';box.textContent=e.message}}
$('#geoRun').addEventListener('click',runGeo);initGeometry();
