// ---------- guided text calculations ----------
const guideTemplates={
  compare:()=>fields2('1つ目の数','a','2つ目の数','b'),difference:()=>fields2('1つ目の数','a','2つ目の数','b'),times:()=>fields2('比べる数','a','基準の数','b'),
  percent:()=>`<div class="row"><div class="field"><label>部分</label><input class="input" id="g_part" type="number" step="any"></div><div class="field"><label>全体</label><input class="input" id="g_total" type="number" step="any"></div></div><div class="field"><label>求めるもの</label><select class="select" id="g_percentType"><option value="pct">百分率（%）</option><option value="decimal">割合（小数）</option><option value="part">全体と割合から部分</option></select></div>`,
  speed:()=>`<div class="row3"><div class="field"><label>距離</label><input class="input" id="g_distance" type="number" step="any"></div><div class="field"><label>時間</label><input class="input" id="g_time" type="number" step="any"></div><div class="field"><label>速さ</label><input class="input" id="g_speed" type="number" step="any"></div></div><div class="field"><label>求めるもの</label><select class="select" id="g_speedType"><option value="speed">速さ = 距離 ÷ 時間</option><option value="distance">距離 = 速さ × 時間</option><option value="time">時間 = 距離 ÷ 速さ</option></select></div>`,
  average:()=>`<div class="field"><label>数値（カンマ・空白・改行区切り）</label><textarea class="textarea" id="g_numbers" placeholder="70, 92, 84, 75, 88"></textarea></div>`,
  sentence:()=>`<div class="field"><label>比較文</label><input class="input" id="g_sentence" placeholder="例：20より15のほうが大きい"></div>`
};
function fields2(l1,id1,l2,id2){return `<div class="row"><div class="field"><label>${l1}</label><input class="input" id="g_${id1}" type="number" step="any"></div><div class="field"><label>${l2}</label><input class="input" id="g_${id2}" type="number" step="any"></div></div>`}
function renderGuide(){const t=$('#guideType').value;$('#guideFields').innerHTML=guideTemplates[t]();}
$('#guideType').addEventListener('change',renderGuide);renderGuide();
function val(id){const e=$(id);return e&&e.value!==''?Number(e.value):NaN}
function runGuide(){
  const t=$('#guideType').value,r=$('#guideResult');try{
    if(t==='compare'){const a=val('#g_a'),b=val('#g_b');need(a,b);const rel=nearly(a,b)?['等しい','=']:a>b?['大きい','>']:['小さい','<'];r.innerHTML=`<div class="big-answer">${fmt(a)} は ${fmt(b)} より${rel[0]}。</div><div class="steps">${fmt(a)} ${rel[1]} ${fmt(b)}</div>`;addHistory('文字比較',`${a},${b}`,`${a}${rel[1]}${b}`)}
    else if(t==='difference'){const a=val('#g_a'),b=val('#g_b');need(a,b);const d=Math.abs(a-b);r.innerHTML=`<div class="big-answer">差：${fmt(d)}</div><div class="steps">|${fmt(a)} − ${fmt(b)}| = ${fmt(d)}</div>`;addHistory('差',`${a},${b}`,fmt(d))}
    else if(t==='times'){const a=val('#g_a'),b=val('#g_b');need(a,b);if(nearly(b,0))throw Error('基準の数を0にはできません。');const q=a/b;r.innerHTML=`<div class="big-answer">${fmt(q)}倍</div><div class="steps">${fmt(a)} ÷ ${fmt(b)} = ${fmt(q)}</div>`;addHistory('倍率',`${a}/${b}`,`${fmt(q)}倍`)}
    else if(t==='percent'){const part=val('#g_part'),total=val('#g_total'),mode=$('#g_percentType').value;if(mode==='part'){need(total,part);const ans=total*part;r.innerHTML=`<div class="big-answer">部分：${fmt(ans)}</div><div class="steps">全体 ${fmt(total)} × 割合 ${fmt(part)}</div>`}else{need(part,total);if(nearly(total,0))throw Error('全体は0にできません。');const q=part/total;r.innerHTML=`<div class="big-answer">${mode==='pct'?fmt(q*100)+'%':fmt(q)}</div><div class="steps">${fmt(part)} ÷ ${fmt(total)}${mode==='pct'?' × 100':''}</div>`}}
    else if(t==='speed'){const mode=$('#g_speedType').value,d=val('#g_distance'),tm=val('#g_time'),sp=val('#g_speed');let ans,formula;if(mode==='speed'){need(d,tm);if(nearly(tm,0))throw Error('時間は0にできません。');ans=d/tm;formula=`${fmt(d)} ÷ ${fmt(tm)}`}if(mode==='distance'){need(sp,tm);ans=sp*tm;formula=`${fmt(sp)} × ${fmt(tm)}`}if(mode==='time'){need(d,sp);if(nearly(sp,0))throw Error('速さは0にできません。');ans=d/sp;formula=`${fmt(d)} ÷ ${fmt(sp)}`}r.innerHTML=`<div class="big-answer">${mode==='speed'?'速さ':mode==='distance'?'距離':'時間'}：${fmt(ans)}</div><div class="steps">${formula} = ${fmt(ans)}</div>`}
    else if(t==='average'){const a=numbersFrom($('#g_numbers').value);if(!a.length)throw Error('数値を1つ以上入力してください。');const sum=a.reduce((x,y)=>x+y,0),m=sum/a.length;r.innerHTML=`<div class="big-answer">平均：${fmt(m)}</div><div class="steps">合計 ${fmt(sum)} ÷ ${a.length}</div>`}
    else if(t==='sentence'){const text=normalizeText($('#g_sentence').value);const m=text.match(/(-?\d+(?:\.\d+)?)\s*より\s*(-?\d+(?:\.\d+)?)\s*のほうが\s*(大きい|小さい|等しい)/);if(!m)throw Error('「20より15のほうが大きい」のように入力してください。');const base=+m[1],subject=+m[2],word=m[3];const truth=word==='大きい'?subject>base:word==='小さい'?subject<base:nearly(subject,base);const correct=nearly(subject,base)?`${fmt(base)}と${fmt(subject)}は等しい`:subject>base?`${fmt(base)}より${fmt(subject)}のほうが大きい`:`${fmt(base)}より${fmt(subject)}のほうが小さい`;r.innerHTML=truth?`<div class="big-answer">✓ 正しい</div><div class="steps">${esc(text)}</div>`:`<div class="big-answer">✗ 違います</div><div class="steps">正しくは「${esc(correct)}」です。</div>`}
    r.className='result success';
  }catch(e){r.className='result error';r.textContent=e.message}
}
function need(...a){if(a.some(x=>!Number.isFinite(x)))throw Error('必要な数値を入力してください。')}
$('#guideRun').addEventListener('click',runGuide);$('#guideUnknown').addEventListener('click',()=>{const t=$('#guideType').value;const msg={compare:'比べたい2つの数だけ入れればOKです。',difference:'2つの数を入れると、大きい方から小さい方を引いた差を出します。',times:'「比べる数 ÷ 基準の数」で何倍かを出します。',percent:'「部分」と「全体」が分かれば、部分 ÷ 全体で割合を出せます。',speed:'3つ全部は不要です。求めたいもの以外の2つを入力してください。',average:'平均したい数をまとめて貼り付けてください。',sentence:'「AよりBのほうが大きい」の形で書くと判定できます。'}[t];$('#guideResult').className='result';$('#guideResult').textContent=msg});

function coeffsFromEquation(eq){
  eq=normalizeText(eq);const parts=eq.split('=');if(parts.length!==2)throw Error('「左辺 = 右辺」の形で入力してください。');
  const f=x=>evalExpression(parts[0],{x})-evalExpression(parts[1],{x});
  const y0=f(0),y1=f(1),y2=f(2);const a=(y2-2*y1+y0)/2,b=y1-y0-a,c=y0;
  for(const x of [-2,-1,3,4]){if(!nearly(f(x),a*x*x+b*x+c))throw Error('現在はxについての一次・二次方程式に対応しています。関数や分母にxがある式は対象外です。');}
  return {a:Math.abs(a)<EPS?0:a,b:Math.abs(b)<EPS?0:b,c:Math.abs(c)<EPS?0:c};
}
function runEquation(){const box=$('#equationResult'),eq=$('#equationInput').value;try{const {a,b,c}=coeffsFromEquation(eq);let html='';if(nearly(a,0)&&nearly(b,0)){html=nearly(c,0)?'<div class="big-answer">すべてのxが解です。</div>':'<div class="big-answer">解はありません。</div>'}else if(nearly(a,0)){const x=-c/b;html=`<div class="big-answer">x = ${fmt(x)}</div><div class="steps">整理すると ${fmt(b)}x ${c>=0?'+':'−'} ${fmt(Math.abs(c))} = 0<br>${fmt(b)}x = ${fmt(-c)}<br>x = ${fmt(x)}</div>`}else{const D=b*b-4*a*c;if(D<-EPS){html=`<div class="big-answer">実数解はありません。</div><div class="steps">判別式 D = b² − 4ac = ${fmt(D)} &lt; 0</div>`}else if(nearly(D,0)){const x=-b/(2*a);html=`<div class="big-answer">x = ${fmt(x)}（重解）</div><div class="steps">${fmt(a)}x² ${b>=0?'+':'−'} ${fmt(Math.abs(b))}x ${c>=0?'+':'−'} ${fmt(Math.abs(c))} = 0<br>D = ${fmt(D)}</div>`}else{const s=Math.sqrt(D),x1=(-b+s)/(2*a),x2=(-b-s)/(2*a);html=`<div class="big-answer">x = ${fmt(x1)} , ${fmt(x2)}</div><div class="steps">a=${fmt(a)}, b=${fmt(b)}, c=${fmt(c)}<br>D = b² − 4ac = ${fmt(D)}<br>x = (−b ± √D) ÷ 2a</div>`}}box.className='result success';box.innerHTML=html;addHistory('方程式',eq,box.querySelector('.big-answer')?.textContent||'解を表示')}catch(e){box.className='result error';box.textContent=e.message}}
$('#equationRun').addEventListener('click',runEquation);$('#equationInput').addEventListener('keydown',e=>{if(e.key==='Enter')runEquation()});
