'use strict';
(function installBootV3(){
  const bootHost=$('#boot-screen');
  if(!bootHost)return;
  bootHost.innerHTML=`<div class="boot-card">
    <section class="boot-visual">
      <div class="boot-brand"><div class="boot-orb"><div class="logo">◈</div></div><h1>DEV OS</h1><div class="boot-build">LAB FIRMWARE 3.0 · BUILD 26100.sim</div></div>
      <div class="boot-side-health" id="boot-health"></div>
    </section>
    <section class="boot-main">
      <div class="boot-heading"><div><h2 id="boot-title">Power-on self test</h2><div class="boot-sub" id="boot-status">Preparing firmware environment…</div></div><div class="boot-percent" id="boot-percent">00%</div></div>
      <div class="boot-stage-list" id="boot-stages"></div>
      <div class="boot-log" id="boot-log"></div>
      <div class="progress"><span id="boot-progress"></span></div>
      <div class="boot-actions"><button id="enter-bios" class="ghost">F2 · UEFI Setup</button><button id="skip-boot" class="ghost">Fast boot</button><span class="boot-integrity" id="boot-integrity"></span></div>
    </section>
  </div>`;
  let bootRun=0;
  $('#enter-bios').addEventListener('click',()=>bootRun++);$('#skip-boot').addEventListener('click',()=>bootRun++);document.addEventListener('keydown',e=>{if(e.key==='F2'&&!bootHost.classList.contains('hidden'))bootRun++},true);
  const activeThreat=()=>!!(state.malware?.active&&Object.keys(state.malware.active).length);
  const bootSteps=()=>[
    ['POST','Firmware power-on self test','CPU, memory and virtual chipset checks'],['UEFI','Validating firmware configuration',`Secure Boot ${state.bios.secureBoot?'enabled':'disabled'} · TPM ${state.bios.tpm?'ready':'disabled'}`],['DEV','Enumerating virtual devices',`${Object.keys(state.devices||{}).length} devices discovered`],['BOOT','Loading Dev Boot Manager',`${state.bios.bootMode} · ${state.bios.bootOrder?.[0]||'DevSSD'}`],['KRN','Loading Dev Kernel','kernel.dev · HAL · memory manager'],['DRV','Starting virtual drivers','Display, storage, network, audio and security filters'],['SVC','Starting system services',`${Object.values(state.services||{}).filter(x=>x.startup==='Automatic').length} automatic services`],['SEC','Checking startup integrity',activeThreat()?'Modified startup entries detected':'Startup chain verified'],['USR','Preparing user session',state.safeMode?'Safe Mode profile':'Student profile'],['SHELL','Starting desktop shell','Explorer, taskbar and package runtime']];
  function paintHealth(){const host=$('#boot-health');if(!host)return;const malware=activeThreat();host.innerHTML=`<div class="boot-health-row"><span>CPU</span><strong>DevCore 8C</strong></div><div class="boot-health-row"><span>Memory</span><strong>16 GB</strong></div><div class="boot-health-row"><span>Boot</span><strong>${esc(state.bios.bootMode)}</strong></div><div class="boot-health-row"><span>Secure Boot</span><strong>${state.bios.secureBoot?'ON':'OFF'}</strong></div><div class="boot-health-row"><span>TPM</span><strong>${state.bios.tpm?'READY':'OFF'}</strong></div><div class="boot-health-row"><span>Startup</span><strong style="color:${malware?'#f3bf5c':'#4fd39c'}">${malware?'MODIFIED':'VERIFIED'}</strong></div>`}
  function appendLog(text){const l=$('#boot-log');if(!l)return;const d=document.createElement('div');d.textContent=`[${new Date().toLocaleTimeString('en-GB',{hour12:false})}] ${text}`;l.append(d);while(l.children.length>6)l.firstElementChild.remove()}
  function drawStages(steps,current){const host=$('#boot-stages');if(!host)return;host.innerHTML=steps.map((s,i)=>`<div class="boot-stage ${i<current?'done':i===current?'active':''}"><span>${i<current?'✓':i===current?'●':'○'}</span><div><strong>${esc(s[1])}</strong><div style="font-size:.74rem;margin-top:2px">${esc(s[2])}</div></div><span class="state">${i<current?'DONE':i===current?'RUN':'WAIT'}</span></div>`).join('')}
  boot=function(forceRecovery=false){const runId=++bootRun;$('#desktop').classList.add('hidden');$('#lock').classList.add('hidden');$('#bios').classList.add('hidden');$('#bsod').classList.add('hidden');$('#recovery').classList.add('hidden');bootHost.classList.remove('hidden');paintHealth();const steps=bootSteps();let i=0;$('#boot-log').innerHTML='';$('#boot-progress').style.width='0%';$('#boot-percent').textContent='00%';drawStages(steps,0);const integrity=$('#boot-integrity'),threat=activeThreat();integrity.textContent=threat?'⚠ startup integrity changed':'✓ startup integrity verified';integrity.classList.toggle('warn',threat);const advance=()=>{if(runId!==bootRun)return;if(i>=steps.length){$('#boot-percent').textContent='100%';$('#boot-progress').style.width='100%';drawStages(steps,steps.length);appendLog('Boot handoff completed.');state.bootCount++;state.lastBoot=now();state.uptimeStart=now();save();setTimeout(()=>{if(runId!==bootRun)return;bootHost.classList.add('hidden');if(forceRecovery||!state.cleanShutdown)showRecovery();else showLock()},state.bios.fastBoot?120:360);return}const[code,title,sub]=steps[i];$('#boot-title').textContent=title;$('#boot-status').textContent=sub;drawStages(steps,i);appendLog(`${code}: ${title}`);const pct=Math.round((i+1)/steps.length*100);$('#boot-progress').style.width=pct+'%';$('#boot-percent').textContent=String(pct).padStart(2,'0')+'%';if(code==='UEFI'&&!state.bios.tpm)logEvent('Warning','TPM-WMI',1796,'TPM simulator is disabled in firmware.','System');i++;setTimeout(advance,state.bios.fastBoot?95:260+rnd(0,130))};advance()};
})();