'use strict';
let desktopSelection=new Set(),selectRect=null,selectStart=null,longPressTimer=null;
function ensureSettings(){state.settings??={language:'ja',theme:'dark',wallpaper:'aurora',iconSize:'medium',accent:'#6aa8ff'};state.desktop??={positions:{},sort:'name'};}
function applyAppearance(){ensureSettings();document.documentElement.dataset.theme=state.settings.theme;document.documentElement.style.setProperty('--accent',state.settings.accent||'#6aa8ff');const d=$('#desktop');if(d){d.dataset.wallpaper=state.settings.wallpaper||'aurora';d.dataset.icons=state.settings.iconSize||'medium';}document.documentElement.lang=locale();}
function refreshShellLanguage(){document.title=`${t('osName')} | PC Local Tool`;$('#unlock').textContent=t('unlock');$('#tray-status').textContent=securityScore()<70?t('attention'):t('protected');renderDesktop();}
function contextMenu(items,x,y){closeContextMenu();const m=document.createElement('div');m.id='context-menu';m.className='context-menu';m.style.left=Math.min(x,innerWidth-245)+'px';m.style.top=Math.min(y,innerHeight-330)+'px';for(const it of items){if(it==='sep'){m.append(Object.assign(document.createElement('div'),{className:'ctx-sep'}));continue}const b=document.createElement('button');b.disabled=!!it.disabled;b.innerHTML=`<span>${it.icon||''}</span><span>${esc(it.label)}</span>${it.hint?`<kbd>${esc(it.hint)}</kbd>`:''}`;b.onclick=()=>{closeContextMenu();it.run?.()};m.append(b)}document.body.append(m)}
function closeContextMenu(){document.querySelector('#context-menu')?.remove()}
function desktopContextItems(target){const icon=target?.closest?.('.desktop-icon');if(icon){const id=icon.dataset.open;return [{label:t('open'),icon:'↗',run:()=>openApp(id)},{label:t('rename'),icon:'✎',disabled:true},{label:t('delete'),icon:'🗑',disabled:id==='appdownloader'||id==='security'},{label:t('properties'),icon:'ⓘ',run:()=>toast(t('properties'),`${apps[id]?.title||id} · Dev OS shortcut`)}]}
 return [{label:t('refresh'),icon:'⟳',run:()=>renderDesktop()},{label:t('newFolder'),icon:'📁',run:createDesktopFolder},{label:t('terminalHere'),icon:'>_',run:()=>openApp('terminal')},'sep',{label:t('selectAll'),icon:'☑',run:selectAllDesktop},{label:t('personalize'),icon:'🎨',run:()=>openApp('settings')},{label:t('displaySettings'),icon:'▣',run:()=>openApp('settings')}];}
function installDesktopInteractions(){const d=$('#desktop');if(!d||d.dataset.interactions)return;d.dataset.interactions='1';d.addEventListener('contextmenu',e=>{if(e.target.closest('.window,.taskbar,.start-menu,.quick-panel'))return;e.preventDefault();contextMenu(desktopContextItems(e.target),e.clientX,e.clientY)});document.addEventListener('pointerdown',e=>{if(!e.target.closest('#context-menu'))closeContextMenu()});
 d.addEventListener('pointerdown',e=>{if(e.button!==0||e.target.closest('.window,.taskbar,.start-menu,.quick-panel'))return;const icon=e.target.closest('.desktop-icon');if(icon){if(e.ctrlKey)toggleDesktopIcon(icon);else selectDesktopIcon(icon);longPressTimer=setTimeout(()=>contextMenu(desktopContextItems(icon),e.clientX,e.clientY),650);return;}clearDesktopSelection();selectStart={x:e.clientX,y:e.clientY};selectRect=document.createElement('div');selectRect.className='selection-rect';d.append(selectRect);d.setPointerCapture?.(e.pointerId);longPressTimer=setTimeout(()=>{selectStart=null;selectRect?.remove();selectRect=null;contextMenu(desktopContextItems(null),e.clientX,e.clientY)},650)});
 d.addEventListener('pointermove',e=>{if(!selectStart||!selectRect)return;clearTimeout(longPressTimer);const x=Math.min(selectStart.x,e.clientX),y=Math.min(selectStart.y,e.clientY),w=Math.abs(e.clientX-selectStart.x),h=Math.abs(e.clientY-selectStart.y);Object.assign(selectRect.style,{left:x+'px',top:y+'px',width:w+'px',height:h+'px'});const r={left:x,top:y,right:x+w,bottom:y+h};$$('.desktop-icon',d).forEach(el=>{const b=el.getBoundingClientRect();const hit=!(b.right<r.left||b.left>r.right||b.bottom<r.top||b.top>r.bottom);el.classList.toggle('selected',hit);if(hit)desktopSelection.add(el.dataset.open);else desktopSelection.delete(el.dataset.open)})});
 const finish=()=>{clearTimeout(longPressTimer);selectStart=null;selectRect?.remove();selectRect=null};d.addEventListener('pointerup',finish);d.addEventListener('pointercancel',finish);
}
function selectDesktopIcon(el){clearDesktopSelection();el.classList.add('selected');desktopSelection.add(el.dataset.open)}function toggleDesktopIcon(el){const on=!el.classList.contains('selected');el.classList.toggle('selected',on);on?desktopSelection.add(el.dataset.open):desktopSelection.delete(el.dataset.open)}function clearDesktopSelection(){$$('.desktop-icon').forEach(x=>x.classList.remove('selected'));desktopSelection.clear()}function selectAllDesktop(){$$('.desktop-icon').forEach(x=>{x.classList.add('selected');desktopSelection.add(x.dataset.open)})}
function createDesktopFolder(){let base=locale()==='ja'?'新しいフォルダー':'New Folder',name=base,i=2;while(state.fs.files[`C:/Users/Student/Desktop/${name}`])name=`${base} (${i++})`;state.fs.files[`C:/Users/Student/Desktop/${name}`]={type:'dir'};logEvent('Information','Explorer',100,`Created desktop folder ${name}.`,'Application');save();toast(t('desktop'),name);}
