function renderEventViewer(root){
  let channel='All',level='All',search='';const render=()=>{let logs=state.logs.filter(x=>(channel==='All'||x.channel===channel)&&(level==='All'||x.level===level)&&(!search||(`${x.source} ${x.id} ${x.message}`.toLowerCase().includes(search.toLowerCase()))));root.innerHTML=`<div class="app-shell"><aside class="sidebar"><h3>Event Viewer</h3>${['All','System','Application','Security','Setup'].map(c=>`<button data-channel="${c}" class="${c===channel?'active':''}">${c}</button>`).join('')}</aside><main class="content"><div class="hero-row"><div><h2>${channel} Events</h2><p class="muted">${logs.length} events</p></div><button class="btn" data-clearlog>Clear simulation log</button></div><div class="toolbar"><select data-level>${['All','Critical','Error','Warning','Information'].map(x=>`<option ${x===level?'selected':''}>${x}</option>`).join('')}</select><input data-search placeholder="Source, Event ID, message" value="${esc(search)}"></div><table class="table"><thead><tr><th>Level</th><th>Date and Time</th><th>Source</th><th>Event ID</th><th>Message</th></tr></thead><tbody>${logs.map((x,i)=>`<tr data-log="${i}"><td class="${x.level==='Critical'||x.level==='Error'?'bad':x.level==='Warning'?'warn':'good'}">${esc(x.level)}</td><td>${new Date(x.time).toLocaleString('ja-JP')}</td><td>${esc(x.source)}</td><td>${x.id}</td><td>${esc(x.message)}</td></tr>`).join('')}</tbody></table></main></div>`;
    root.querySelector('.sidebar').onclick=e=>{const b=e.target.closest('[data-channel]');if(b){channel=b.dataset.channel;render()}};root.querySelector('[data-level]').onchange=e=>{level=e.target.value;render()};root.querySelector('[data-search]').oninput=e=>{search=e.target.value;render()};root.querySelector('[data-clearlog]').onclick=()=>{if(confirm('Clear virtual event log?')){state.logs=[];logEvent('Information','EventLog',104,'The virtual log was cleared.','System');render()}};
  };render();
}
function servicesTable(compact=false){return `<h2>${compact?'Services':'Services Console'}</h2><table class="table"><thead><tr><th>Name</th><th>Status</th><th>Startup</th><th>Description</th><th></th></tr></thead><tbody>${Object.entries(state.services).map(([n,s])=>`<tr><td>${esc(n)}</td><td class="${s.status==='Running'?'good':'muted'}">${s.status}</td><td>${s.startup}</td><td>${esc(s.desc)}</td><td><button class="btn" data-service="${esc(n)}">${s.status==='Running'?'Stop':'Start'}</button></td></tr>`).join('')}</tbody></table>`}
function bindServiceButtons(root,rerender){root.querySelectorAll('[data-service]').forEach(b=>b.onclick=()=>{const n=b.dataset.service,s=state.services[n];if(s.startup==='Disabled'&&s.status!=='Running'){toast('Services',`${n} is disabled.`);return}s.status=s.status==='Running'?'Stopped':'Running';logEvent('Information','Service Control Manager',7036,`The ${n} service entered the ${s.status.toLowerCase()} state.`,'System');save();rerender()})}
function renderServices(root){const render=()=>{root.innerHTML=`<div class="content">${servicesTable(false)}</div>`;bindServiceButtons(root,render)};render()}
function renderDevices(root){const render=()=>{root.innerHTML=`<div class="content"><h2>Device Manager</h2><p class="muted">All devices are simulated.</p><table class="table"><thead><tr><th>Device</th><th>Status</th><th>Driver</th><th></th></tr></thead><tbody>${Object.entries(state.devices).map(([n,d])=>`<tr><td>${d.status==='OK'?'🟢':'⚠️'} ${esc(n)}</td><td>${esc(d.status)}</td><td>${esc(d.driver)}</td><td><button class="btn" data-device="${esc(n)}">${d.status==='OK'?'Disable':'Enable'}</button></td></tr>`).join('')}</tbody></table><button class="btn danger" data-driverfault>Simulate faulty display driver</button></div>`;root.querySelectorAll('[data-device]').forEach(b=>b.onclick=()=>{const d=state.devices[b.dataset.device];d.status=d.status==='OK'?'Disabled':'OK';logEvent(d.status==='OK'?'Information':'Warning','Kernel-PnP',411,`${b.dataset.device} status changed to ${d.status}.`,'System');save();render()});root.querySelector('[data-driverfault]').onclick=()=>crash('VIDEO_TDR_FAILURE','devrender.sys')};render()}
