'use strict';
(function installDevOSUpdater311(){
  const RELEASE={version:'3.1.1',build:30101,channel:'stable',released:'2026-09-11'};
  const RAW_BASE='https://raw.githubusercontent.com/fuugafuu/pclocaltool/main/tools/dev-os/';
  const RAW_MANIFEST=RAW_BASE+'updates/latest.json';
  const CANONICAL_ORIGIN='https://pclocaltool.vercel.app';
  const CANONICAL_BASE=CANONICAL_ORIGIN+'/tools/dev-os/';
  const MODE=location.protocol==='file:'?'local':/\.vercel\.app$/i.test(location.hostname)?'vercel':'web';
  const SAME_ORIGIN_BASE=MODE==='vercel'?new URL('./',location.href).href:null;
  const SAME_ORIGIN_MANIFEST=MODE==='vercel'?new URL('updates/latest.json',SAME_ORIGIN_BASE).href:null;
  window.DEVOS_RELEASE=RELEASE;
  state.update??={lastCheck:0,channel:'stable',history:[],available:null,status:'idle',source:MODE,auto:true};
  state.update.history??=[];state.update.auto??=true;state.update.source=MODE;
  let lastResult=null,checking=false;
  const parts=v=>String(v||'0').split(/[.-]/).map(x=>parseInt(x,10)||0);
  function cmp(a,b){const x=parts(a),y=parts(b),n=Math.max(x.length,y.length);for(let i=0;i<n;i++){const d=(x[i]||0)-(y[i]||0);if(d)return d>0?1:-1}return 0}
  function trustedURL(value){try{const u=new URL(value);if(u.href.startsWith(RAW_BASE)||u.href.startsWith(CANONICAL_BASE))return true;if(MODE==='vercel'&&u.origin===location.origin&&u.pathname.startsWith('/tools/dev-os/'))return true;return false}catch{return false}}
  async function fetchJSON(url,timeout=7000){if(!trustedURL(url))throw Error('Untrusted update source.');const c=new AbortController(),tm=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url+(url.includes('?')?'&':'?')+'_='+Date.now(),{cache:'no-store',signal:c.signal,headers:{Accept:'application/json'}});if(!r.ok)throw Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(tm)}}
  function validate(m){if(!m||m.type!=='devos-update'||m.schema!==1||!m.version||!Number.isFinite(Number(m.build))||!Array.isArray(m.files))throw Error('Invalid Dev OS update manifest.');if(m.rawBase&&!trustedURL(m.rawBase))throw Error('Untrusted rawBase.');for(const f of m.files){if(!f.path||f.path.includes('..')||f.path.startsWith('/')||!/^[A-Za-z0-9_./-]+$/.test(f.path))throw Error('Unsafe path: '+String(f.path));if(f.url&&!trustedURL(f.url))throw Error('Untrusted file URL.')}return m}
  function text(r){if(!r)return'Not checked';return{current:'Up to date',available:`Version ${r.remote?.version||''} is ready`,waiting:`Version ${r.remote?.version||''} found · waiting for this Vercel deployment`, 'local-available':`Version ${r.remote?.version||''} available for local update`,error:r.message||'Update check failed',checking:'Checking…'}[r.status]||r.status}
  async function checkUpdates({silent=false,manifest=null}={}){if(checking)return lastResult;checking=true;state.update.status='checking';if(!silent)toast('Dev OS Update','Checking GitHub and deployment…');try{const remote=validate(manifest||await fetchJSON(RAW_MANIFEST));let status='current',deployed=null;if(cmp(remote.version,RELEASE.version)>0||Number(remote.build)>RELEASE.build){if(MODE==='vercel'){try{deployed=validate(await fetchJSON(SAME_ORIGIN_MANIFEST));status=(cmp(deployed.version,remote.version)>=0&&Number(deployed.build)>=Number(remote.build))?'available':'waiting'}catch{status='waiting'}}else status='local-available'}const r={status,remote,deployed,mode:MODE,checked:Date.now()};lastResult=r;state.update.lastCheck=r.checked;state.update.available=status==='current'?null:{version:remote.version,build:remote.build};state.update.status=status;save();logEvent('Information','DevOS-Update',19,`Update check: ${status}; running ${RELEASE.version}/${RELEASE.build}; GitHub ${remote.version}/${remote.build}.`,'System');if(!silent)toast('Dev OS Update',text(r));return r}catch(e){const r={status:'error',message:e.name==='AbortError'?'Update check timed out.':String(e.message||e),checked:Date.now(),mode:MODE};lastResult=r;state.update.lastCheck=r.checked;state.update.status='error';save();if(!silent)toast('Dev OS Update',r.message);return r}finally{checking=false}}
  async function installVercel(r=lastResult){if(!r||r.status!=='available'){r=await checkUpdates();if(r.status!=='available')return}state.update.history.unshift({from:RELEASE.version,to:r.remote.version,time:Date.now(),mode:'vercel-reload',status:'started'});state.update.history=state.update.history.slice(0,30);state.update.pending=r.remote.version;state.update.status='restart-required';logEvent('Information','DevOS-Update',43,`Restart scheduled into ${r.remote.version}.`,'System');save();const u=new URL(location.href);u.searchParams.set('devosUpdate',r.remote.version);u.searchParams.set('build',String(r.remote.build));u.searchParams.set('_',String(Date.now()));location.replace(u.href)}
  async function readManifestFile(file){let m=JSON.parse(await file.text());if(m.type==='devos-update-pointer'){if(!m.manifestUrl||!trustedURL(m.manifestUrl))throw Error('Untrusted update pointer.');m=await fetchJSON(m.manifestUrl)}return validate(m)}
  function pickManifest(){return new Promise(resolve=>{const i=document.createElement('input');i.type='file';i.accept='.json,.devupdate.json,application/json';i.onchange=async()=>{try{resolve(i.files?.[0]?await readManifestFile(i.files[0]):null)}catch(e){toast('Dev OS Update',e.message);resolve(null)}};i.click()})}
  async function readDirFile(root,path){try{let d=root;const p=path.split('/');for(let x=0;x<p.length-1;x++)d=await d.getDirectoryHandle(p[x]);return await(await d.getFileHandle(p.at(-1))).getFile().then(f=>f.text())}catch{return null}}
  async function ensureDir(root,arr){let d=root;for(const n of arr)d=await d.getDirectoryHandle(n,{create:true});return d}
  async function writeDirFile(root,path,content){const p=path.split('/'),name=p.pop(),d=await ensureDir(root,p),h=await d.getFileHandle(name,{create:true}),w=await h.createWritable();await w.write(content);await w.close()}
  async function validFolder(dir){const h=await readDirFile(dir,'index.html');return !!h&&/Dev OS Lab|DEV OS/i.test(h)&&/core\.js/.test(h)}
  async function applyLocal(manifest){manifest=validate(manifest||lastResult?.remote);if(cmp(manifest.version,RELEASE.version)<=0&&Number(manifest.build)<=RELEASE.build){toast('Dev OS Update','This package is not newer than the running version.');return}if(!('showDirectoryPicker'in window)){toast('Dev OS Update','Folder writing requires a supported Chromium browser.');return}let dir;try{dir=await showDirectoryPicker({mode:'readwrite'})}catch{return}if(!(await validFolder(dir))){toast('Dev OS Update','Select the folder that contains the Dev OS index.html.');return}const stamp=new Date().toISOString().replace(/[:.]/g,'-'),backup=await dir.getDirectoryHandle('.devos-backup',{create:true}),bak=await backup.getDirectoryHandle(`${RELEASE.version}-${stamp}`,{create:true});let done=0;try{for(const f of manifest.files){const old=await readDirFile(dir,f.path);if(old!==null)await writeDirFile(bak,f.path,old);const url=f.url||`${manifest.rawBase||RAW_BASE}${f.path}`;if(!trustedURL(url))throw Error('Untrusted source: '+url);const r=await fetch(url+(url.includes('?')?'&':'?')+'_='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(`${f.path}: HTTP ${r.status}`);await writeDirFile(dir,f.path,await r.text());done++;state.update.status='installing';state.update.progress={done,total:manifest.files.length,file:f.path};save();rerender()}state.update.history.unshift({from:RELEASE.version,to:manifest.version,time:Date.now(),mode:'local-files',status:'installed',files:done});state.update.pending=manifest.version;state.update.status='restart-required';delete state.update.progress;save();logEvent('Information','DevOS-Update',44,`Local update ${manifest.version} wrote ${done} files. Backup stored in .devos-backup.`,'System');toast('Dev OS Update',`Updated ${done} files. Reopen index.html.`);rerender()}catch(e){state.update.status='error';state.update.error=e.message;delete state.update.progress;save();toast('Dev OS Update',`Stopped after ${done} files: ${e.message}`);rerender()}}
  function environment(){const n=MODE==='vercel'?'Vercel deployment':MODE==='local'?'Local file':'Web host',sub=MODE==='vercel'?location.hostname:MODE==='local'?'User-selected folder updates supported where browser allows':location.hostname;return `<div class="status-card"><div class="status-icon">${MODE==='vercel'?'▲':MODE==='local'?'💾':'🌐'}</div><div style="flex:1"><strong>${n}</strong><div class="muted">${esc(sub)}</div></div><span class="badge">${RELEASE.version}</span></div>`}
  function render(root){const r=lastResult,remote=r?.remote,p=state.update.progress;root.innerHTML=`<div class="content update-page"><div class="hero-row"><div><h2>Dev OS Update</h2><p class="muted">GitHub release + current deployment verification.</p></div><span class="badge">Build ${RELEASE.build}</span></div>${environment()}<div class="update-hero"><div><span class="update-label">RUNNING</span><h2>${RELEASE.version}</h2><p>${remote?`GitHub: ${esc(remote.version)} / build ${esc(remote.build)}`:'Check for a newer release.'}</p></div><div class="update-state ${r?.status||state.update.status}">${esc(text(r)||state.update.status)}</div></div>${p?`<div class="status-card"><div style="flex:1"><strong>${p.done}/${p.total}</strong><div class="muted">${esc(p.file)}</div><div class="bar"><span style="width:${Math.round(p.done/p.total*100)}%"></span></div></div></div>`:''}<div class="toolbar"><button class="btn" data-check>Check GitHub</button>${MODE==='vercel'?`<button class="btn" data-deploy ${r?.status==='available'?'':'disabled'}>Update and restart</button>`:`<button class="btn" data-load>Load .devupdate.json</button><button class="btn" data-local ${remote&&cmp(remote.version,RELEASE.version)>0?'':'disabled'}>Update local folder</button>`}</div>${remote?`<section class="update-notes"><h3>${esc(remote.version)}</h3><ul>${(remote.notes||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`:''}<h3>History</h3>${(state.update.history||[]).slice(0,8).map(h=>`<div class="log"><span>↻</span><span>${new Date(h.time).toLocaleString()}</span><div>${esc(h.from)} → ${esc(h.to)}<div class="muted">${esc(h.mode)}</div></div><span>${esc(h.status)}</span></div>`).join('')||'<p class="muted">No updates installed yet.</p>'}</div>`;root.querySelector('[data-check]')?.addEventListener('click',async()=>{await checkUpdates();render(root)});root.querySelector('[data-deploy]')?.addEventListener('click',()=>installVercel(lastResult));root.querySelector('[data-load]')?.addEventListener('click',async()=>{const m=await pickManifest();if(m){lastResult={status:cmp(m.version,RELEASE.version)>0?'local-available':'current',remote:m,mode:'local-file',checked:Date.now()};render(root)}});root.querySelector('[data-local]')?.addEventListener('click',()=>applyLocal(lastResult?.remote))}
  function rerender(){const w=windows.get('update');if(w&&!w.classList.contains('hidden'))render(w.querySelector('.window-body'))}
  apps.update={title:'Dev OS Update',icon:'🔄',render};
  const base=renderDesktop;renderDesktop=function(){base();const h=$('#desktop-icons');if(h&&!h.querySelector('[data-open="update"]')){const b=document.createElement('button');b.className='desktop-icon';b.dataset.open='update';b.innerHTML='<span>🔄</span><label>Dev OS Update</label>';h.append(b)}const s=$('#start-menu .start-grid');if(s&&!s.querySelector('[data-open="update"]')){const b=document.createElement('button');b.dataset.open='update';b.innerHTML='<div class="start-icon">🔄</div><span>Dev OS Update</span>';s.append(b)}};
  window.DevOSUpdate={release:RELEASE,mode:MODE,check:checkUpdates,installVercel,applyLocal};
  if(state.update.pending&&cmp(RELEASE.version,state.update.pending)>=0){state.update.status='current';logEvent('Information','DevOS-Update',20,`Update completed. Running ${RELEASE.version}.`,'System');state.update.pending=null;save()}
  if(MODE==='vercel'&&state.update.auto!==false)setTimeout(async()=>{const r=await checkUpdates({silent:true});if(r.status==='available')toast('Dev OS Update',`Version ${r.remote.version} is ready.`);else if(r.status==='waiting')toast('Dev OS Update',`GitHub has ${r.remote.version}; this Vercel deployment is still catching up.`);rerender()},1700);
  setInterval(()=>{if(MODE==='vercel'&&state.update.auto!==false)checkUpdates({silent:true}).then(rerender)},120000);
})();
