'use strict';
(function installDevOSUpdater(){
  const RELEASE={version:'3.1.0',build:30100,channel:'stable',released:'2026-09-11'};
  const RAW_MANIFEST='https://raw.githubusercontent.com/fuugafuu/pclocaltool/main/tools/dev-os/updates/latest.json';
  const PROD_MANIFEST='https://pclocaltool.vercel.app/tools/dev-os/updates/latest.json';
  const PROD_OS='https://pclocaltool.vercel.app/tools/dev-os/index.html';
  const MODE=location.protocol==='file:'?'local':/\.vercel\.app$/i.test(location.hostname)?'vercel':'web';
  window.DEVOS_RELEASE=RELEASE;
  state.update??={lastCheck:0,channel:'stable',history:[],available:null,status:'idle',source:MODE,auto:true};
  let lastResult=null,checking=false;
  const versionParts=v=>String(v||'0').split(/[.-]/).map(x=>parseInt(x,10)||0);
  function compareVersion(a,b){const x=versionParts(a),y=versionParts(b),n=Math.max(x.length,y.length);for(let i=0;i<n;i++){const d=(x[i]||0)-(y[i]||0);if(d)return d>0?1:-1}return 0}
  async function fetchJSON(url,timeout=7000){const c=new AbortController(),tm=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url+(url.includes('?')?'&':'?')+'_='+Date.now(),{cache:'no-store',signal:c.signal,headers:{'Accept':'application/json'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(tm)}}
  function validateManifest(m){if(!m||m.type!=='devos-update'||m.schema!==1||!m.version||!Number.isFinite(Number(m.build))||!Array.isArray(m.files))throw new Error('Invalid Dev OS update manifest.');for(const f of m.files){if(!f.path||f.path.includes('..')||f.path.startsWith('/')||!/^[A-Za-z0-9_./-]+$/.test(f.path))throw new Error('Unsafe update path: '+String(f.path))}return m}
  function statusText(r){if(!r)return 'Not checked';if(r.status==='current')return 'Up to date';if(r.status==='available')return `Version ${r.remote.version} is ready`;if(r.status==='waiting')return `Version ${r.remote.version} found · waiting for Vercel deployment`;if(r.status==='local-available')return `Version ${r.remote.version} available for local update`;if(r.status==='error')return r.message||'Update check failed';return r.status}
  async function checkUpdates({silent=false,manifest=null}={}){if(checking)return lastResult;checking=true;state.update.status='checking';if(!silent)toast('Dev OS Update','Checking for updates…');try{let remote=manifest?validateManifest(manifest):validateManifest(await fetchJSON(RAW_MANIFEST));let status='current',deployed=null;if(compareVersion(remote.version,RELEASE.version)>0||Number(remote.build)>RELEASE.build){if(MODE==='vercel'){try{deployed=validateManifest(await fetchJSON(remote.productionManifest||PROD_MANIFEST));status=compareVersion(deployed.version,remote.version)>=0?'available':'waiting'}catch{status='waiting'}}else status='local-available'}const r={status,remote,deployed,mode:MODE,checked:Date.now()};lastResult=r;state.update.lastCheck=r.checked;state.update.available=status==='current'?null:{version:remote.version,build:remote.build};state.update.status=status;save();logEvent('Information','DevOS-Update',19,`Update check completed: ${status}; local ${RELEASE.version}, remote ${remote.version}.`,'System');if(!silent)toast('Dev OS Update',statusText(r));return r}catch(err){const r={status:'error',message:err.name==='AbortError'?'Update check timed out.':String(err.message||err),checked:Date.now(),mode:MODE};lastResult=r;state.update.lastCheck=r.checked;state.update.status='error';save();if(!silent)toast('Dev OS Update',r.message);return r}finally{checking=false}}
  async function installVercelUpdate(r=lastResult){if(!r||r.status==='waiting'){toast('Dev OS Update','Vercel deployment is not ready yet.');return}if(!r||r.status!=='available'){r=await checkUpdates();if(r.status!=='available')return}state.update.history.unshift({from:RELEASE.version,to:r.remote.version,time:Date.now(),mode:'vercel-reload',status:'started'});state.update.history=state.update.history.slice(0,20);state.update.pending=r.remote.version;logEvent('Information','DevOS-Update',43,`Preparing restart into Dev OS ${r.remote.version}.`,'System');save();const target=(r.remote.productionUrl||PROD_OS)+(String(r.remote.productionUrl||PROD_OS).includes('?')?'&':'?')+'devosUpdate='+encodeURIComponent(r.remote.version)+'&t='+Date.now();location.replace(target)}
  async function readManifestFile(file){const text=await file.text();let m=JSON.parse(text);if(m.type==='devos-update-pointer'&&m.manifestUrl)m=await fetchJSON(m.manifestUrl);return validateManifest(m)}
  async function pickManifest(){return new Promise(resolve=>{const input=document.createElement('input');input.type='file';input.accept='.json,.devupdate.json,application/json';input.onchange=async()=>{try{if(!input.files?.[0])return resolve(null);resolve(await readManifestFile(input.files[0]))}catch(e){toast('Dev OS Update',e.message);resolve(null)}};input.click()})}
  async function dirFileText(dir,path){try{let d=dir;const parts=path.split('/');for(let i=0;i<parts.length-1;i++)d=await d.getDirectoryHandle(parts[i]);const f=await d.getFileHandle(parts.at(-1));return await(await f.getFile()).text()}catch{return null}}
  async function ensureDir(root,parts){let d=root;for(const p of parts)d=await d.getDirectoryHandle(p,{create:true});return d}
  async function writeDirFile(root,path,content){const parts=path.split('/'),name=parts.pop(),dir=await ensureDir(root,parts);const h=await dir.getFileHandle(name,{create:true}),w=await h.createWritable();await w.write(content);await w.close()}
  async function validateDevOSFolder(dir){const html=await dirFileText(dir,'index.html');return !!html&&/Dev OS Lab|DEV OS/i.test(html)&&/core\.js/.test(html)}
  async function applyLocalUpdate(manifest){manifest=validateManifest(manifest||lastResult?.remote);if(compareVersion(manifest.version,RELEASE.version)<=0&&Number(manifest.build)<=RELEASE.build){toast('Dev OS Update','This update is not newer than the current version.');return}if(!('showDirectoryPicker'in window)){toast('Dev OS Update','This browser cannot write the local Dev OS folder. Use Edge/Chrome with File System Access, or use the Vercel version.');return}let dir;try{dir=await showDirectoryPicker({mode:'readwrite'})}catch{return}if(!(await validateDevOSFolder(dir))){toast('Dev OS Update','Selected folder does not look like the Dev OS folder.');return}const stamp=new Date().toISOString().replace(/[:.]/g,'-'),backup=await dir.getDirectoryHandle('.devos-backup',{create:true}),backupVersion=await backup.getDirectoryHandle(`${RELEASE.version}-${stamp}`,{create:true});let done=0;try{for(const item of manifest.files){const old=await dirFileText(dir,item.path);if(old!==null)await writeDirFile(backupVersion,item.path,old);const url=(item.url||`${manifest.rawBase||'https://raw.githubusercontent.com/fuugafuu/pclocaltool/main/tools/dev-os/'}${item.path}`);const res=await fetch(url+(url.includes('?')?'&':'?')+'_='+Date.now(),{cache:'no-store'});if(!res.ok)throw new Error(`Download failed: ${item.path} (${res.status})`);const text=await res.text();await writeDirFile(dir,item.path,text);done++;state.update.status='installing';state.update.progress={done,total:manifest.files.length,file:item.path};save();renderUpdateAppIfOpen()}state.update.history.unshift({from:RELEASE.version,to:manifest.version,time:Date.now(),mode:'local-files',status:'installed',files:done});state.update.pending=manifest.version;state.update.status='restart-required';delete state.update.progress;logEvent('Information','DevOS-Update',44,`Local update ${manifest.version} wrote ${done} files. Backup saved to .devos-backup.`,'System');save();toast('Dev OS Update',`Updated ${done} files. Reopen index.html to boot ${manifest.version}.`);renderUpdateAppIfOpen()}catch(e){state.update.status='error';state.update.error=e.message;delete state.update.progress;save();toast('Dev OS Update',`Update stopped after ${done} files: ${e.message}`);renderUpdateAppIfOpen()}}
  function environmentCard(){const label=MODE==='vercel'?'Vercel deployment':MODE==='local'?'Local file':'Web host';const hint=MODE==='vercel'?`GitHub-linked deployment · ${location.hostname}`:MODE==='local'?'Local index.html · folder update available in supported Chromium browsers':location.hostname;return `<div class="status-card"><div class="status-icon">${MODE==='vercel'?'▲':MODE==='local'?'💾':'🌐'}</div><div style="flex:1"><strong>${label}</strong><div class="muted">${esc(hint)}</div></div><span class="badge">${esc(RELEASE.version)}</span></div>`}
  function renderUpdateApp(root){const r=lastResult,remote=r?.remote,prog=state.update.progress;root.innerHTML=`<div class="content update-page"><div class="hero-row"><div><h2>Dev OS Update</h2><p class="muted">Checks the GitHub release manifest and coordinates Vercel or local-file updates.</p></div><span class="badge">Build ${RELEASE.build}</span></div>${environmentCard()}<div class="update-hero"><div><span class="update-label">CURRENT RELEASE</span><h2>${esc(RELEASE.version)}</h2><p>${remote?`Latest: ${esc(remote.version)} · ${esc(remote.channel||'stable')}`:'Run an update check to compare against GitHub.'}</p></div><div class="update-state ${r?.status||state.update.status}">${esc(statusText(r)||state.update.status)}</div></div>${prog?`<div class="status-card"><div style="flex:1"><strong>Installing ${prog.done}/${prog.total}</strong><div class="muted">${esc(prog.file)}</div><div class="bar"><span style="width:${Math.round(prog.done/prog.total*100)}%"></span></div></div></div>`:''}<div class="toolbar"><button class="btn" data-check>Check GitHub</button>${MODE==='vercel'?`<button class="btn" data-install-vercel ${r?.status==='available'?'':'disabled'}>Update and restart</button>`:`<button class="btn" data-load-pack>Load .devupdate.json</button><button class="btn" data-local-install ${remote&&compareVersion(remote.version,RELEASE.version)>0?'':'disabled'}>Update local folder</button>`}</div>${remote?`<section class="update-notes"><h3>Version ${esc(remote.version)}</h3><div class="muted">Published ${esc(remote.published||'')} · ${remote.files.length} core files</div><ul>${(remote.notes||[]).map(n=>`<li>${esc(n)}</li>`).join('')}</ul></section>`:''}<section class="update-history"><h3>Update history</h3>${(state.update.history||[]).slice(0,8).map(h=>`<div class="log"><span>↻</span><span>${new Date(h.time).toLocaleString()}</span><div>${esc(h.from)} → ${esc(h.to)}<div class="muted">${esc(h.mode)}</div></div><span>${esc(h.status)}</span></div>`).join('')||'<p class="muted">No updates installed yet.</p>'}</section></div>`;root.querySelector('[data-check]')?.addEventListener('click',async()=>{await checkUpdates();renderUpdateApp(root)});root.querySelector('[data-install-vercel]')?.addEventListener('click',()=>installVercelUpdate(lastResult));root.querySelector('[data-load-pack]')?.addEventListener('click',async()=>{const m=await pickManifest();if(m){lastResult={status:compareVersion(m.version,RELEASE.version)>0?'local-available':'current',remote:m,mode:'local-file',checked:Date.now()};renderUpdateApp(root)}});root.querySelector('[data-local-install]')?.addEventListener('click',()=>applyLocalUpdate(lastResult?.remote))}
  function renderUpdateAppIfOpen(){const w=windows.get('update');if(w&&!w.classList.contains('hidden'))renderUpdateApp(w.querySelector('.window-body'))}
  apps.update={title:'Dev OS Update',icon:'🔄',render:renderUpdateApp};
  const previousRenderDesktop=renderDesktop;renderDesktop=function(){previousRenderDesktop();const host=$('#desktop-icons');if(host&&!host.querySelector('[data-open="update"]')){const b=document.createElement('button');b.className='desktop-icon';b.dataset.open='update';b.innerHTML='<span>🔄</span><label>Dev OS Update</label>';host.append(b)}const start=$('#start-menu .start-grid');if(start&&!start.querySelector('[data-open="update"]')){const b=document.createElement('button');b.dataset.open='update';b.innerHTML='<div class="start-icon">🔄</div><span>Dev OS Update</span>';start.append(b)}};
  window.DevOSUpdate={release:RELEASE,mode:MODE,check:checkUpdates,installVercel:installVercelUpdate,applyLocal:applyLocalUpdate};
  if(state.update.pending&&compareVersion(RELEASE.version,state.update.pending)>=0){state.update.history.unshift({from:state.update.pending,to:RELEASE.version,time:Date.now(),mode:'boot-confirmation',status:'completed'});state.update.pending=null;state.update.status='current';logEvent('Information','DevOS-Update',20,`Dev OS update completed. Running ${RELEASE.version}.`,'System');save()}
  const autoCheck=()=>{if(MODE==='vercel'&&state.update.auto!==false)setTimeout(async()=>{const r=await checkUpdates({silent:true});if(r.status==='available')toast('Dev OS Update',`Version ${r.remote.version} is ready to install.`);else if(r.status==='waiting')toast('Dev OS Update',`Version ${r.remote.version} is on GitHub; waiting for Vercel.`);renderUpdateAppIfOpen()},1800)};
  autoCheck();setInterval(()=>{if(MODE==='vercel'&&state.update.auto!==false)checkUpdates({silent:true}).then(renderUpdateAppIfOpen)},120000);
})();