'use strict';
(function installDesktopV3(){
  function ensureDesktopV3(){state.desktop??={positions:{},sort:'name'};state.desktop.positions??={};state.desktop.layoutVersion=3;save()}
  ensureDesktopV3();
  const desktop=$('#desktop'),iconsHost=$('#desktop-icons');
  const usableRect=()=>{const r=iconsHost.getBoundingClientRect();return{left:r.left,top:r.top,width:r.width,height:r.height}};
  function iconSize(el){const r=el.getBoundingClientRect();return{w:Math.max(64,r.width),h:Math.max(64,r.height)}}
  function clampPosition(x,y,el){const a=usableRect(),s=iconSize(el);return{x:clamp(x,0,Math.max(0,a.width-s.w)),y:clamp(y,0,Math.max(0,a.height-s.h))}}
  function defaultPosition(index,el){const a=usableRect(),s=iconSize(el),gapX=Math.max(s.w+12,92),gapY=Math.max(s.h+10,88),rows=Math.max(1,Math.floor(a.height/gapY));const col=Math.floor(index/rows),row=index%rows;return clampPosition(8+col*gapX,8+row*gapY,el)}
  function applyIconPositions(){ensureDesktopV3();const items=$$('.desktop-icon',iconsHost);items.forEach((el,i)=>{const id=el.dataset.open||`icon-${i}`;let p=state.desktop.positions[id];if(!p)p=defaultPosition(i,el);p=clampPosition(Number(p.x)||0,Number(p.y)||0,el);state.desktop.positions[id]=p;el.style.left=p.x+'px';el.style.top=p.y+'px'});save()}
  function clampAllIcons(){let changed=false;$$('.desktop-icon',iconsHost).forEach((el,i)=>{const id=el.dataset.open||`icon-${i}`,old=state.desktop.positions[id]||defaultPosition(i,el),p=clampPosition(old.x,old.y,el);if(p.x!==old.x||p.y!==old.y)changed=true;state.desktop.positions[id]=p;el.style.left=p.x+'px';el.style.top=p.y+'px'});if(changed)save()}
  function installIconDragging(){if(iconsHost.dataset.dragV3)return;iconsHost.dataset.dragV3='1';let drag=null;iconsHost.addEventListener('pointerdown',e=>{const el=e.target.closest('.desktop-icon');if(!el||e.button!==0)return;const id=el.dataset.open,start=state.desktop.positions[id]||{x:el.offsetLeft,y:el.offsetTop};drag={el,id,pointer:e.pointerId,sx:e.clientX,sy:e.clientY,x:start.x,y:start.y,moved:false};el.setPointerCapture?.(e.pointerId)});iconsHost.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.pointer)return;const dx=e.clientX-drag.sx,dy=e.clientY-drag.sy;if(!drag.moved&&Math.hypot(dx,dy)<5)return;drag.moved=true;if(typeof longPressTimer!=='undefined')clearTimeout(longPressTimer);drag.el.classList.add('dragging');const p=clampPosition(drag.x+dx,drag.y+dy,drag.el);drag.el.style.left=p.x+'px';drag.el.style.top=p.y+'px';e.preventDefault()});const end=e=>{if(!drag||e.pointerId!==drag.pointer)return;if(typeof longPressTimer!=='undefined'&&drag.moved)clearTimeout(longPressTimer);const p=clampPosition(parseFloat(drag.el.style.left)||0,parseFloat(drag.el.style.top)||0,drag.el);drag.el.style.left=p.x+'px';drag.el.style.top=p.y+'px';state.desktop.positions[drag.id]=p;drag.el.classList.remove('dragging');if(drag.moved){drag.el.dataset.suppressOpenUntil=String(Date.now()+350);save()}drag=null};iconsHost.addEventListener('pointerup',end);iconsHost.addEventListener('pointercancel',end);desktop.addEventListener('dblclick',e=>{const el=e.target.closest('.desktop-icon');if(el&&Number(el.dataset.suppressOpenUntil||0)>Date.now()){e.stopImmediatePropagation();e.preventDefault()}},true)}
  const baseRenderDesktop=renderDesktop;renderDesktop=function(){baseRenderDesktop();if(typeof malwareActive==='function'&&malwareActive()&&typeof apps!=='undefined'&&apps.nwupdate&&!iconsHost.querySelector('[data-open="nwupdate"]')){const b=document.createElement('button');b.className='desktop-icon';b.dataset.open='nwupdate';b.innerHTML=`<span>${apps.nwupdate.icon||'⬆️'}</span><label>${esc(apps.nwupdate.title||'System Update Helper')}</label>`;iconsHost.append(b)}requestAnimationFrame(()=>{applyIconPositions();installIconDragging();syncMalwareVisuals()})};
  function clampWindow(w){if(!w||w.classList.contains('max')||w.classList.contains('hidden'))return;const area=desktop.getBoundingClientRect(),taskbar=$('.taskbar')?.getBoundingClientRect();const usableBottom=Math.max(120,(taskbar?.top||area.bottom)-area.top-8),maxW=Math.max(120,area.width-16),maxH=Math.max(120,usableBottom-8);const width=Math.min(w.offsetWidth,maxW),height=Math.min(w.offsetHeight,maxH);w.style.width=width+'px';w.style.height=height+'px';const left=clamp(w.offsetLeft,8,Math.max(8,area.width-width-8)),top=clamp(w.offsetTop,8,Math.max(8,usableBottom-height));w.style.left=left+'px';w.style.top=top+'px'}
  function clampWindows(){windows.forEach(clampWindow)}
  const baseOpenApp=openApp;openApp=function(id){baseOpenApp(id);requestAnimationFrame(()=>{clampWindow(windows.get(id));syncMalwareVisuals()})};
  addEventListener('resize',()=>requestAnimationFrame(()=>{clampAllIcons();clampWindows()}));addEventListener('mouseup',()=>requestAnimationFrame(clampWindows));
  function syncMalwareVisuals(){if(!desktop)return;const active=typeof malwareActive==='function'&&malwareActive(),level=state.malware?.infectionLevel||0,stage=!active?0:level<35?1:level<55?2:level<72?3:level<88?4:5;for(let i=1;i<=5;i++)desktop.classList.toggle('malware-stage-'+i,i===stage);let banner=$('#malware-banner');if(active&&stage>=3){if(!banner){banner=document.createElement('div');banner.id='malware-banner';banner.className='malware-banner';desktop.append(banner)}banner.innerHTML=`<div><strong>⚠ DEV OS malware simulation active — stage ${stage}</strong><br><small>NightWorm has modified ${state.malware?.mutations||0} virtual system objects. This is contained inside Dev OS.</small></div><button data-open-security>Open Security</button>`;banner.querySelector('button').onclick=()=>openApp('security')}else banner?.remove()}
  window.syncMalwareVisuals=syncMalwareVisuals;window.emitMalwareGlitch=function(count=2){if(!desktop||desktop.classList.contains('hidden'))return;for(let i=0;i<count;i++){const l=document.createElement('i');l.className='malware-glitch';l.style.top=rnd(8,Math.max(10,innerHeight-80))+'px';l.style.left='-15vw';l.style.width=rnd(90,300)+'px';desktop.append(l);setTimeout(()=>l.remove(),900)}};
  const observer=new MutationObserver(()=>{if(!desktop.classList.contains('hidden'))requestAnimationFrame(()=>{applyIconPositions();installIconDragging();clampWindows();syncMalwareVisuals()})});observer.observe(desktop,{attributes:true,attributeFilter:['class']});
})();